// Code generated by ent, DO NOT EDIT.

package routepoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the routepoint type in the database.
	Label = "route_point"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRouteID holds the string denoting the route_id field in the database.
	FieldRouteID = "route_id"
	// FieldStoreTenantID holds the string denoting the store_tenant_id field in the database.
	FieldStoreTenantID = "store_tenant_id"
	// FieldOrderNum holds the string denoting the order_num field in the database.
	FieldOrderNum = "order_num"
	// FieldVisitID holds the string denoting the visit_id field in the database.
	FieldVisitID = "visit_id"
	// EdgeRoute holds the string denoting the route edge name in mutations.
	EdgeRoute = "route"
	// Table holds the table name of the routepoint in the database.
	Table = "route_points"
	// RouteTable is the table that holds the route relation/edge.
	RouteTable = "route_points"
	// RouteInverseTable is the table name for the Route entity.
	// It exists in this package in order to avoid circular dependency with the "route" package.
	RouteInverseTable = "routes"
	// RouteColumn is the table column denoting the route relation/edge.
	RouteColumn = "route_id"
)

// Columns holds all SQL columns for routepoint fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRouteID,
	FieldStoreTenantID,
	FieldOrderNum,
	FieldVisitID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultVisitID holds the default value on creation for the "visit_id" field.
	DefaultVisitID int64
)

// OrderOption defines the ordering options for the RoutePoint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRouteID orders the results by the route_id field.
func ByRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteID, opts...).ToFunc()
}

// ByStoreTenantID orders the results by the store_tenant_id field.
func ByStoreTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreTenantID, opts...).ToFunc()
}

// ByOrderNum orders the results by the order_num field.
func ByOrderNum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNum, opts...).ToFunc()
}

// ByVisitID orders the results by the visit_id field.
func ByVisitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisitID, opts...).ToFunc()
}

// ByRouteField orders the results by route field.
func ByRouteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRouteStep(), sql.OrderByField(field, opts...))
	}
}
func newRouteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RouteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RouteTable, RouteColumn),
	)
}
