// Code generated by ent, DO NOT EDIT.

package routepoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/agents/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldRouteID, v))
}

// StoreTenantID applies equality check predicate on the "store_tenant_id" field. It's identical to StoreTenantIDEQ.
func StoreTenantID(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldStoreTenantID, v))
}

// OrderNum applies equality check predicate on the "order_num" field. It's identical to OrderNumEQ.
func OrderNum(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldOrderNum, v))
}

// VisitID applies equality check predicate on the "visit_id" field. It's identical to VisitIDEQ.
func VisitID(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldVisitID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldUpdatedAt, v))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldRouteID, vs...))
}

// StoreTenantIDEQ applies the EQ predicate on the "store_tenant_id" field.
func StoreTenantIDEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldStoreTenantID, v))
}

// StoreTenantIDNEQ applies the NEQ predicate on the "store_tenant_id" field.
func StoreTenantIDNEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldStoreTenantID, v))
}

// StoreTenantIDIn applies the In predicate on the "store_tenant_id" field.
func StoreTenantIDIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldStoreTenantID, vs...))
}

// StoreTenantIDNotIn applies the NotIn predicate on the "store_tenant_id" field.
func StoreTenantIDNotIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldStoreTenantID, vs...))
}

// StoreTenantIDGT applies the GT predicate on the "store_tenant_id" field.
func StoreTenantIDGT(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldStoreTenantID, v))
}

// StoreTenantIDGTE applies the GTE predicate on the "store_tenant_id" field.
func StoreTenantIDGTE(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldStoreTenantID, v))
}

// StoreTenantIDLT applies the LT predicate on the "store_tenant_id" field.
func StoreTenantIDLT(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldStoreTenantID, v))
}

// StoreTenantIDLTE applies the LTE predicate on the "store_tenant_id" field.
func StoreTenantIDLTE(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldStoreTenantID, v))
}

// OrderNumEQ applies the EQ predicate on the "order_num" field.
func OrderNumEQ(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldOrderNum, v))
}

// OrderNumNEQ applies the NEQ predicate on the "order_num" field.
func OrderNumNEQ(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldOrderNum, v))
}

// OrderNumIn applies the In predicate on the "order_num" field.
func OrderNumIn(vs ...int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldOrderNum, vs...))
}

// OrderNumNotIn applies the NotIn predicate on the "order_num" field.
func OrderNumNotIn(vs ...int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldOrderNum, vs...))
}

// OrderNumGT applies the GT predicate on the "order_num" field.
func OrderNumGT(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldOrderNum, v))
}

// OrderNumGTE applies the GTE predicate on the "order_num" field.
func OrderNumGTE(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldOrderNum, v))
}

// OrderNumLT applies the LT predicate on the "order_num" field.
func OrderNumLT(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldOrderNum, v))
}

// OrderNumLTE applies the LTE predicate on the "order_num" field.
func OrderNumLTE(v int32) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldOrderNum, v))
}

// VisitIDEQ applies the EQ predicate on the "visit_id" field.
func VisitIDEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldEQ(FieldVisitID, v))
}

// VisitIDNEQ applies the NEQ predicate on the "visit_id" field.
func VisitIDNEQ(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNEQ(FieldVisitID, v))
}

// VisitIDIn applies the In predicate on the "visit_id" field.
func VisitIDIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIn(FieldVisitID, vs...))
}

// VisitIDNotIn applies the NotIn predicate on the "visit_id" field.
func VisitIDNotIn(vs ...int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotIn(FieldVisitID, vs...))
}

// VisitIDGT applies the GT predicate on the "visit_id" field.
func VisitIDGT(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGT(FieldVisitID, v))
}

// VisitIDGTE applies the GTE predicate on the "visit_id" field.
func VisitIDGTE(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldGTE(FieldVisitID, v))
}

// VisitIDLT applies the LT predicate on the "visit_id" field.
func VisitIDLT(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLT(FieldVisitID, v))
}

// VisitIDLTE applies the LTE predicate on the "visit_id" field.
func VisitIDLTE(v int64) predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldLTE(FieldVisitID, v))
}

// VisitIDIsNil applies the IsNil predicate on the "visit_id" field.
func VisitIDIsNil() predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldIsNull(FieldVisitID))
}

// VisitIDNotNil applies the NotNil predicate on the "visit_id" field.
func VisitIDNotNil() predicate.RoutePoint {
	return predicate.RoutePoint(sql.FieldNotNull(FieldVisitID))
}

// HasRoute applies the HasEdge predicate on the "route" edge.
func HasRoute() predicate.RoutePoint {
	return predicate.RoutePoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RouteTable, RouteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRouteWith applies the HasEdge predicate on the "route" edge with a given conditions (other predicates).
func HasRouteWith(preds ...predicate.Route) predicate.RoutePoint {
	return predicate.RoutePoint(func(s *sql.Selector) {
		step := newRouteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoutePoint) predicate.RoutePoint {
	return predicate.RoutePoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoutePoint) predicate.RoutePoint {
	return predicate.RoutePoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoutePoint) predicate.RoutePoint {
	return predicate.RoutePoint(sql.NotPredicates(p))
}
