// Code generated by ent, DO NOT EDIT.

package visitphoto

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the visitphoto type in the database.
	Label = "visit_photo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVisitID holds the string denoting the visit_id field in the database.
	FieldVisitID = "visit_id"
	// FieldMediaURL holds the string denoting the media_url field in the database.
	FieldMediaURL = "media_url"
	// EdgeVisit holds the string denoting the visit edge name in mutations.
	EdgeVisit = "visit"
	// Table holds the table name of the visitphoto in the database.
	Table = "visit_photos"
	// VisitTable is the table that holds the visit relation/edge.
	VisitTable = "visit_photos"
	// VisitInverseTable is the table name for the Visit entity.
	// It exists in this package in order to avoid circular dependency with the "visit" package.
	VisitInverseTable = "visits"
	// VisitColumn is the table column denoting the visit relation/edge.
	VisitColumn = "visit_id"
)

// Columns holds all SQL columns for visitphoto fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVisitID,
	FieldMediaURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MediaURLValidator is a validator for the "media_url" field. It is called by the builders before save.
	MediaURLValidator func(string) error
)

// OrderOption defines the ordering options for the VisitPhoto queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVisitID orders the results by the visit_id field.
func ByVisitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisitID, opts...).ToFunc()
}

// ByMediaURL orders the results by the media_url field.
func ByMediaURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaURL, opts...).ToFunc()
}

// ByVisitField orders the results by visit field.
func ByVisitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVisitStep(), sql.OrderByField(field, opts...))
	}
}
func newVisitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VisitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VisitTable, VisitColumn),
	)
}
