// Code generated by ent, DO NOT EDIT.

package visitphoto

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/agents/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// VisitID applies equality check predicate on the "visit_id" field. It's identical to VisitIDEQ.
func VisitID(v int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldVisitID, v))
}

// MediaURL applies equality check predicate on the "media_url" field. It's identical to MediaURLEQ.
func MediaURL(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldMediaURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLTE(FieldUpdatedAt, v))
}

// VisitIDEQ applies the EQ predicate on the "visit_id" field.
func VisitIDEQ(v int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldVisitID, v))
}

// VisitIDNEQ applies the NEQ predicate on the "visit_id" field.
func VisitIDNEQ(v int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNEQ(FieldVisitID, v))
}

// VisitIDIn applies the In predicate on the "visit_id" field.
func VisitIDIn(vs ...int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldIn(FieldVisitID, vs...))
}

// VisitIDNotIn applies the NotIn predicate on the "visit_id" field.
func VisitIDNotIn(vs ...int64) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNotIn(FieldVisitID, vs...))
}

// MediaURLEQ applies the EQ predicate on the "media_url" field.
func MediaURLEQ(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEQ(FieldMediaURL, v))
}

// MediaURLNEQ applies the NEQ predicate on the "media_url" field.
func MediaURLNEQ(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNEQ(FieldMediaURL, v))
}

// MediaURLIn applies the In predicate on the "media_url" field.
func MediaURLIn(vs ...string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldIn(FieldMediaURL, vs...))
}

// MediaURLNotIn applies the NotIn predicate on the "media_url" field.
func MediaURLNotIn(vs ...string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldNotIn(FieldMediaURL, vs...))
}

// MediaURLGT applies the GT predicate on the "media_url" field.
func MediaURLGT(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGT(FieldMediaURL, v))
}

// MediaURLGTE applies the GTE predicate on the "media_url" field.
func MediaURLGTE(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldGTE(FieldMediaURL, v))
}

// MediaURLLT applies the LT predicate on the "media_url" field.
func MediaURLLT(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLT(FieldMediaURL, v))
}

// MediaURLLTE applies the LTE predicate on the "media_url" field.
func MediaURLLTE(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldLTE(FieldMediaURL, v))
}

// MediaURLContains applies the Contains predicate on the "media_url" field.
func MediaURLContains(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldContains(FieldMediaURL, v))
}

// MediaURLHasPrefix applies the HasPrefix predicate on the "media_url" field.
func MediaURLHasPrefix(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldHasPrefix(FieldMediaURL, v))
}

// MediaURLHasSuffix applies the HasSuffix predicate on the "media_url" field.
func MediaURLHasSuffix(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldHasSuffix(FieldMediaURL, v))
}

// MediaURLEqualFold applies the EqualFold predicate on the "media_url" field.
func MediaURLEqualFold(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldEqualFold(FieldMediaURL, v))
}

// MediaURLContainsFold applies the ContainsFold predicate on the "media_url" field.
func MediaURLContainsFold(v string) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.FieldContainsFold(FieldMediaURL, v))
}

// HasVisit applies the HasEdge predicate on the "visit" edge.
func HasVisit() predicate.VisitPhoto {
	return predicate.VisitPhoto(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VisitTable, VisitColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVisitWith applies the HasEdge predicate on the "visit" edge with a given conditions (other predicates).
func HasVisitWith(preds ...predicate.Visit) predicate.VisitPhoto {
	return predicate.VisitPhoto(func(s *sql.Selector) {
		step := newVisitStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VisitPhoto) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VisitPhoto) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VisitPhoto) predicate.VisitPhoto {
	return predicate.VisitPhoto(sql.NotPredicates(p))
}
