// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/agents/v1/agents.proto

package agents_v1

import (
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Points        []*RoutePointInput     `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRouteRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *CreateRouteRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateRouteRequest) GetPoints() []*RoutePointInput {
	if x != nil {
		return x.Points
	}
	return nil
}

type RoutePointInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreTenantId int64                  `protobuf:"varint,1,opt,name=store_tenant_id,json=storeTenantId,proto3" json:"store_tenant_id,omitempty"`
	OrderNum      int32                  `protobuf:"varint,2,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePointInput) Reset() {
	*x = RoutePointInput{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePointInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePointInput) ProtoMessage() {}

func (x *RoutePointInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePointInput.ProtoReflect.Descriptor instead.
func (*RoutePointInput) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *RoutePointInput) GetStoreTenantId() int64 {
	if x != nil {
		return x.StoreTenantId
	}
	return 0
}

func (x *RoutePointInput) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

type CreateRouteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteReply) Reset() {
	*x = CreateRouteReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteReply) ProtoMessage() {}

func (x *CreateRouteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteReply.ProtoReflect.Descriptor instead.
func (*CreateRouteReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRouteReply) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *GetRouteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRouteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteReply) Reset() {
	*x = GetRouteReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteReply) ProtoMessage() {}

func (x *GetRouteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteReply.ProtoReflect.Descriptor instead.
func (*GetRouteReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *GetRouteReply) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,4,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *ListRoutesRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ListRoutesRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListRoutesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRoutesRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListRoutesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Route               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesReply) Reset() {
	*x = ListRoutesReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesReply) ProtoMessage() {}

func (x *ListRoutesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesReply.ProtoReflect.Descriptor instead.
func (*ListRoutesReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoutesReply) GetItems() []*Route {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRoutesReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutePointId  int64                  `protobuf:"varint,1,opt,name=route_point_id,json=routePointId,proto3" json:"route_point_id,omitempty"`
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           string                 `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{7}
}

func (x *CheckInRequest) GetRoutePointId() int64 {
	if x != nil {
		return x.RoutePointId
	}
	return 0
}

func (x *CheckInRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CheckInRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type CheckInReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *Visit                 `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInReply) Reset() {
	*x = CheckInReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInReply) ProtoMessage() {}

func (x *CheckInReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInReply.ProtoReflect.Descriptor instead.
func (*CheckInReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *CheckInReply) GetVisit() *Visit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type CheckOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutePointId  int64                  `protobuf:"varint,1,opt,name=route_point_id,json=routePointId,proto3" json:"route_point_id,omitempty"`
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           string                 `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *CheckOutRequest) GetRoutePointId() int64 {
	if x != nil {
		return x.RoutePointId
	}
	return 0
}

func (x *CheckOutRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CheckOutRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type CheckOutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visit         *Visit                 `protobuf:"bytes,1,opt,name=visit,proto3" json:"visit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutReply) Reset() {
	*x = CheckOutReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutReply) ProtoMessage() {}

func (x *CheckOutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutReply.ProtoReflect.Descriptor instead.
func (*CheckOutReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *CheckOutReply) GetVisit() *Visit {
	if x != nil {
		return x.Visit
	}
	return nil
}

type ListVisitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,4,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisitsRequest) Reset() {
	*x = ListVisitsRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisitsRequest) ProtoMessage() {}

func (x *ListVisitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisitsRequest.ProtoReflect.Descriptor instead.
func (*ListVisitsRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *ListVisitsRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ListVisitsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListVisitsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *ListVisitsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListVisitsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Visit               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisitsReply) Reset() {
	*x = ListVisitsReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisitsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisitsReply) ProtoMessage() {}

func (x *ListVisitsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisitsReply.ProtoReflect.Descriptor instead.
func (*ListVisitsReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{12}
}

func (x *ListVisitsReply) GetItems() []*Visit {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVisitsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type AddVisitPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitId       int64                  `protobuf:"varint,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVisitPhotoRequest) Reset() {
	*x = AddVisitPhotoRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVisitPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVisitPhotoRequest) ProtoMessage() {}

func (x *AddVisitPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVisitPhotoRequest.ProtoReflect.Descriptor instead.
func (*AddVisitPhotoRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{13}
}

func (x *AddVisitPhotoRequest) GetVisitId() int64 {
	if x != nil {
		return x.VisitId
	}
	return 0
}

func (x *AddVisitPhotoRequest) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

type AddVisitPhotoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photo         *VisitPhoto            `protobuf:"bytes,1,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVisitPhotoReply) Reset() {
	*x = AddVisitPhotoReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVisitPhotoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVisitPhotoReply) ProtoMessage() {}

func (x *AddVisitPhotoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVisitPhotoReply.ProtoReflect.Descriptor instead.
func (*AddVisitPhotoReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{14}
}

func (x *AddVisitPhotoReply) GetPhoto() *VisitPhoto {
	if x != nil {
		return x.Photo
	}
	return nil
}

type GetVisitPhotosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitId       int64                  `protobuf:"varint,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitPhotosRequest) Reset() {
	*x = GetVisitPhotosRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitPhotosRequest) ProtoMessage() {}

func (x *GetVisitPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitPhotosRequest.ProtoReflect.Descriptor instead.
func (*GetVisitPhotosRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{15}
}

func (x *GetVisitPhotosRequest) GetVisitId() int64 {
	if x != nil {
		return x.VisitId
	}
	return 0
}

type GetVisitPhotosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VisitPhoto          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVisitPhotosReply) Reset() {
	*x = GetVisitPhotosReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVisitPhotosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVisitPhotosReply) ProtoMessage() {}

func (x *GetVisitPhotosReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVisitPhotosReply.ProtoReflect.Descriptor instead.
func (*GetVisitPhotosReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{16}
}

func (x *GetVisitPhotosReply) GetItems() []*VisitPhoto {
	if x != nil {
		return x.Items
	}
	return nil
}

type OnboardStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	OwnerPhone    string                 `protobuf:"bytes,2,opt,name=owner_phone,json=ownerPhone,proto3" json:"owner_phone,omitempty"`
	ProductsFile  []byte                 `protobuf:"bytes,3,opt,name=products_file,json=productsFile,proto3" json:"products_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardStoreRequest) Reset() {
	*x = OnboardStoreRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardStoreRequest) ProtoMessage() {}

func (x *OnboardStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardStoreRequest.ProtoReflect.Descriptor instead.
func (*OnboardStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{17}
}

func (x *OnboardStoreRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *OnboardStoreRequest) GetOwnerPhone() string {
	if x != nil {
		return x.OwnerPhone
	}
	return ""
}

func (x *OnboardStoreRequest) GetProductsFile() []byte {
	if x != nil {
		return x.ProductsFile
	}
	return nil
}

type OnboardStoreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewTenantId   int64                  `protobuf:"varint,1,opt,name=new_tenant_id,json=newTenantId,proto3" json:"new_tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardStoreReply) Reset() {
	*x = OnboardStoreReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardStoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardStoreReply) ProtoMessage() {}

func (x *OnboardStoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardStoreReply.ProtoReflect.Descriptor instead.
func (*OnboardStoreReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{18}
}

func (x *OnboardStoreReply) GetNewTenantId() int64 {
	if x != nil {
		return x.NewTenantId
	}
	return 0
}

type GetAgentReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentReportRequest) Reset() {
	*x = GetAgentReportRequest{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentReportRequest) ProtoMessage() {}

func (x *GetAgentReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentReportRequest.ProtoReflect.Descriptor instead.
func (*GetAgentReportRequest) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{19}
}

func (x *GetAgentReportRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *GetAgentReportRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetAgentReportRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetAgentReportReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *AgentReport           `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentReportReply) Reset() {
	*x = GetAgentReportReply{}
	mi := &file_api_agents_v1_agents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentReportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentReportReply) ProtoMessage() {}

func (x *GetAgentReportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_agents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentReportReply.ProtoReflect.Descriptor instead.
func (*GetAgentReportReply) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_agents_proto_rawDescGZIP(), []int{20}
}

func (x *GetAgentReportReply) GetReport() *AgentReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_api_agents_v1_agents_proto protoreflect.FileDescriptor

const file_api_agents_v1_agents_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agents/v1/agents.proto\x12\tagents.v1\x1a\x1aapi/agents/v1/models.proto\x1a\x19api/utils/v1/models.proto\"w\n" +
	"\x12CreateRouteRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x122\n" +
	"\x06points\x18\x03 \x03(\v2\x1a.agents.v1.RoutePointInputR\x06points\"V\n" +
	"\x0fRoutePointInput\x12&\n" +
	"\x0fstore_tenant_id\x18\x01 \x01(\x03R\rstoreTenantId\x12\x1b\n" +
	"\torder_num\x18\x02 \x01(\x05R\borderNum\":\n" +
	"\x10CreateRouteReply\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.agents.v1.RouteR\x05route\"!\n" +
	"\x0fGetRouteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\rGetRouteReply\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.agents.v1.RouteR\x05route\"\x91\x01\n" +
	"\x11ListRoutesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x125\n" +
	"\bpaginate\x18\x04 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"n\n" +
	"\x0fListRoutesReply\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.agents.v1.RouteR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"Z\n" +
	"\x0eCheckInRequest\x12$\n" +
	"\x0eroute_point_id\x18\x01 \x01(\x03R\froutePointId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\tR\x03lon\"6\n" +
	"\fCheckInReply\x12&\n" +
	"\x05visit\x18\x01 \x01(\v2\x10.agents.v1.VisitR\x05visit\"[\n" +
	"\x0fCheckOutRequest\x12$\n" +
	"\x0eroute_point_id\x18\x01 \x01(\x03R\froutePointId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\tR\x03lon\"7\n" +
	"\rCheckOutReply\x12&\n" +
	"\x05visit\x18\x01 \x01(\v2\x10.agents.v1.VisitR\x05visit\"\x9b\x01\n" +
	"\x11ListVisitsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x125\n" +
	"\bpaginate\x18\x04 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"n\n" +
	"\x0fListVisitsReply\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.agents.v1.VisitR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"N\n" +
	"\x14AddVisitPhotoRequest\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\x03R\avisitId\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\"A\n" +
	"\x12AddVisitPhotoReply\x12+\n" +
	"\x05photo\x18\x01 \x01(\v2\x15.agents.v1.VisitPhotoR\x05photo\"2\n" +
	"\x15GetVisitPhotosRequest\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\x03R\avisitId\"B\n" +
	"\x13GetVisitPhotosReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.agents.v1.VisitPhotoR\x05items\"z\n" +
	"\x13OnboardStoreRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x1f\n" +
	"\vowner_phone\x18\x02 \x01(\tR\n" +
	"ownerPhone\x12#\n" +
	"\rproducts_file\x18\x03 \x01(\fR\fproductsFile\"7\n" +
	"\x11OnboardStoreReply\x12\"\n" +
	"\rnew_tenant_id\x18\x01 \x01(\x03R\vnewTenantId\"h\n" +
	"\x15GetAgentReportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\"E\n" +
	"\x13GetAgentReportReply\x12.\n" +
	"\x06report\x18\x01 \x01(\v2\x16.agents.v1.AgentReportR\x06report2\xf4\x05\n" +
	"\rAgentsService\x12I\n" +
	"\vCreateRoute\x12\x1d.agents.v1.CreateRouteRequest\x1a\x1b.agents.v1.CreateRouteReply\x12@\n" +
	"\bGetRoute\x12\x1a.agents.v1.GetRouteRequest\x1a\x18.agents.v1.GetRouteReply\x12F\n" +
	"\n" +
	"ListRoutes\x12\x1c.agents.v1.ListRoutesRequest\x1a\x1a.agents.v1.ListRoutesReply\x12=\n" +
	"\aCheckIn\x12\x19.agents.v1.CheckInRequest\x1a\x17.agents.v1.CheckInReply\x12@\n" +
	"\bCheckOut\x12\x1a.agents.v1.CheckOutRequest\x1a\x18.agents.v1.CheckOutReply\x12F\n" +
	"\n" +
	"ListVisits\x12\x1c.agents.v1.ListVisitsRequest\x1a\x1a.agents.v1.ListVisitsReply\x12O\n" +
	"\rAddVisitPhoto\x12\x1f.agents.v1.AddVisitPhotoRequest\x1a\x1d.agents.v1.AddVisitPhotoReply\x12R\n" +
	"\x0eGetVisitPhotos\x12 .agents.v1.GetVisitPhotosRequest\x1a\x1e.agents.v1.GetVisitPhotosReply\x12L\n" +
	"\fOnboardStore\x12\x1e.agents.v1.OnboardStoreRequest\x1a\x1c.agents.v1.OnboardStoreReply\x12R\n" +
	"\x0eGetAgentReport\x12 .agents.v1.GetAgentReportRequest\x1a\x1e.agents.v1.GetAgentReportReplyB@Z>gitlab.calendaria.team/services/agents/api/agents/v1;agents_v1b\x06proto3"

var (
	file_api_agents_v1_agents_proto_rawDescOnce sync.Once
	file_api_agents_v1_agents_proto_rawDescData []byte
)

func file_api_agents_v1_agents_proto_rawDescGZIP() []byte {
	file_api_agents_v1_agents_proto_rawDescOnce.Do(func() {
		file_api_agents_v1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agents_v1_agents_proto_rawDesc), len(file_api_agents_v1_agents_proto_rawDesc)))
	})
	return file_api_agents_v1_agents_proto_rawDescData
}

var file_api_agents_v1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_agents_v1_agents_proto_goTypes = []any{
	(*CreateRouteRequest)(nil),    // 0: agents.v1.CreateRouteRequest
	(*RoutePointInput)(nil),       // 1: agents.v1.RoutePointInput
	(*CreateRouteReply)(nil),      // 2: agents.v1.CreateRouteReply
	(*GetRouteRequest)(nil),       // 3: agents.v1.GetRouteRequest
	(*GetRouteReply)(nil),         // 4: agents.v1.GetRouteReply
	(*ListRoutesRequest)(nil),     // 5: agents.v1.ListRoutesRequest
	(*ListRoutesReply)(nil),       // 6: agents.v1.ListRoutesReply
	(*CheckInRequest)(nil),        // 7: agents.v1.CheckInRequest
	(*CheckInReply)(nil),          // 8: agents.v1.CheckInReply
	(*CheckOutRequest)(nil),       // 9: agents.v1.CheckOutRequest
	(*CheckOutReply)(nil),         // 10: agents.v1.CheckOutReply
	(*ListVisitsRequest)(nil),     // 11: agents.v1.ListVisitsRequest
	(*ListVisitsReply)(nil),       // 12: agents.v1.ListVisitsReply
	(*AddVisitPhotoRequest)(nil),  // 13: agents.v1.AddVisitPhotoRequest
	(*AddVisitPhotoReply)(nil),    // 14: agents.v1.AddVisitPhotoReply
	(*GetVisitPhotosRequest)(nil), // 15: agents.v1.GetVisitPhotosRequest
	(*GetVisitPhotosReply)(nil),   // 16: agents.v1.GetVisitPhotosReply
	(*OnboardStoreRequest)(nil),   // 17: agents.v1.OnboardStoreRequest
	(*OnboardStoreReply)(nil),     // 18: agents.v1.OnboardStoreReply
	(*GetAgentReportRequest)(nil), // 19: agents.v1.GetAgentReportRequest
	(*GetAgentReportReply)(nil),   // 20: agents.v1.GetAgentReportReply
	(*Route)(nil),                 // 21: agents.v1.Route
	(*v1.PaginateRequest)(nil),    // 22: utils.v1.PaginateRequest
	(*v1.PaginateReply)(nil),      // 23: utils.v1.PaginateReply
	(*Visit)(nil),                 // 24: agents.v1.Visit
	(*VisitPhoto)(nil),            // 25: agents.v1.VisitPhoto
	(*AgentReport)(nil),           // 26: agents.v1.AgentReport
}
var file_api_agents_v1_agents_proto_depIdxs = []int32{
	1,  // 0: agents.v1.CreateRouteRequest.points:type_name -> agents.v1.RoutePointInput
	21, // 1: agents.v1.CreateRouteReply.route:type_name -> agents.v1.Route
	21, // 2: agents.v1.GetRouteReply.route:type_name -> agents.v1.Route
	22, // 3: agents.v1.ListRoutesRequest.paginate:type_name -> utils.v1.PaginateRequest
	21, // 4: agents.v1.ListRoutesReply.items:type_name -> agents.v1.Route
	23, // 5: agents.v1.ListRoutesReply.paginate:type_name -> utils.v1.PaginateReply
	24, // 6: agents.v1.CheckInReply.visit:type_name -> agents.v1.Visit
	24, // 7: agents.v1.CheckOutReply.visit:type_name -> agents.v1.Visit
	22, // 8: agents.v1.ListVisitsRequest.paginate:type_name -> utils.v1.PaginateRequest
	24, // 9: agents.v1.ListVisitsReply.items:type_name -> agents.v1.Visit
	23, // 10: agents.v1.ListVisitsReply.paginate:type_name -> utils.v1.PaginateReply
	25, // 11: agents.v1.AddVisitPhotoReply.photo:type_name -> agents.v1.VisitPhoto
	25, // 12: agents.v1.GetVisitPhotosReply.items:type_name -> agents.v1.VisitPhoto
	26, // 13: agents.v1.GetAgentReportReply.report:type_name -> agents.v1.AgentReport
	0,  // 14: agents.v1.AgentsService.CreateRoute:input_type -> agents.v1.CreateRouteRequest
	3,  // 15: agents.v1.AgentsService.GetRoute:input_type -> agents.v1.GetRouteRequest
	5,  // 16: agents.v1.AgentsService.ListRoutes:input_type -> agents.v1.ListRoutesRequest
	7,  // 17: agents.v1.AgentsService.CheckIn:input_type -> agents.v1.CheckInRequest
	9,  // 18: agents.v1.AgentsService.CheckOut:input_type -> agents.v1.CheckOutRequest
	11, // 19: agents.v1.AgentsService.ListVisits:input_type -> agents.v1.ListVisitsRequest
	13, // 20: agents.v1.AgentsService.AddVisitPhoto:input_type -> agents.v1.AddVisitPhotoRequest
	15, // 21: agents.v1.AgentsService.GetVisitPhotos:input_type -> agents.v1.GetVisitPhotosRequest
	17, // 22: agents.v1.AgentsService.OnboardStore:input_type -> agents.v1.OnboardStoreRequest
	19, // 23: agents.v1.AgentsService.GetAgentReport:input_type -> agents.v1.GetAgentReportRequest
	2,  // 24: agents.v1.AgentsService.CreateRoute:output_type -> agents.v1.CreateRouteReply
	4,  // 25: agents.v1.AgentsService.GetRoute:output_type -> agents.v1.GetRouteReply
	6,  // 26: agents.v1.AgentsService.ListRoutes:output_type -> agents.v1.ListRoutesReply
	8,  // 27: agents.v1.AgentsService.CheckIn:output_type -> agents.v1.CheckInReply
	10, // 28: agents.v1.AgentsService.CheckOut:output_type -> agents.v1.CheckOutReply
	12, // 29: agents.v1.AgentsService.ListVisits:output_type -> agents.v1.ListVisitsReply
	14, // 30: agents.v1.AgentsService.AddVisitPhoto:output_type -> agents.v1.AddVisitPhotoReply
	16, // 31: agents.v1.AgentsService.GetVisitPhotos:output_type -> agents.v1.GetVisitPhotosReply
	18, // 32: agents.v1.AgentsService.OnboardStore:output_type -> agents.v1.OnboardStoreReply
	20, // 33: agents.v1.AgentsService.GetAgentReport:output_type -> agents.v1.GetAgentReportReply
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_agents_v1_agents_proto_init() }
func file_api_agents_v1_agents_proto_init() {
	if File_api_agents_v1_agents_proto != nil {
		return
	}
	file_api_agents_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agents_v1_agents_proto_rawDesc), len(file_api_agents_v1_agents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agents_v1_agents_proto_goTypes,
		DependencyIndexes: file_api_agents_v1_agents_proto_depIdxs,
		MessageInfos:      file_api_agents_v1_agents_proto_msgTypes,
	}.Build()
	File_api_agents_v1_agents_proto = out.File
	file_api_agents_v1_agents_proto_goTypes = nil
	file_api_agents_v1_agents_proto_depIdxs = nil
}
