// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/agents/v1/agents.proto

package agents_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentsService_CreateRoute_FullMethodName    = "/agents.v1.AgentsService/CreateRoute"
	AgentsService_GetRoute_FullMethodName       = "/agents.v1.AgentsService/GetRoute"
	AgentsService_ListRoutes_FullMethodName     = "/agents.v1.AgentsService/ListRoutes"
	AgentsService_CheckIn_FullMethodName        = "/agents.v1.AgentsService/CheckIn"
	AgentsService_CheckOut_FullMethodName       = "/agents.v1.AgentsService/CheckOut"
	AgentsService_ListVisits_FullMethodName     = "/agents.v1.AgentsService/ListVisits"
	AgentsService_AddVisitPhoto_FullMethodName  = "/agents.v1.AgentsService/AddVisitPhoto"
	AgentsService_GetVisitPhotos_FullMethodName = "/agents.v1.AgentsService/GetVisitPhotos"
	AgentsService_OnboardStore_FullMethodName   = "/agents.v1.AgentsService/OnboardStore"
	AgentsService_GetAgentReport_FullMethodName = "/agents.v1.AgentsService/GetAgentReport"
)

// AgentsServiceClient is the client API for AgentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentsServiceClient interface {
	// Story 6.1: Routes
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteReply, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteReply, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesReply, error)
	// Story 6.2: GPS Visits
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInReply, error)
	CheckOut(ctx context.Context, in *CheckOutRequest, opts ...grpc.CallOption) (*CheckOutReply, error)
	ListVisits(ctx context.Context, in *ListVisitsRequest, opts ...grpc.CallOption) (*ListVisitsReply, error)
	// Story 6.3: Photo Reports
	AddVisitPhoto(ctx context.Context, in *AddVisitPhotoRequest, opts ...grpc.CallOption) (*AddVisitPhotoReply, error)
	GetVisitPhotos(ctx context.Context, in *GetVisitPhotosRequest, opts ...grpc.CallOption) (*GetVisitPhotosReply, error)
	// Story 6.4: New Store Onboarding
	OnboardStore(ctx context.Context, in *OnboardStoreRequest, opts ...grpc.CallOption) (*OnboardStoreReply, error)
	// Story 6.5: Agent Reports
	GetAgentReport(ctx context.Context, in *GetAgentReportRequest, opts ...grpc.CallOption) (*GetAgentReportReply, error)
}

type agentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentsServiceClient(cc grpc.ClientConnInterface) AgentsServiceClient {
	return &agentsServiceClient{cc}
}

func (c *agentsServiceClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteReply)
	err := c.cc.Invoke(ctx, AgentsService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteReply)
	err := c.cc.Invoke(ctx, AgentsService_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesReply)
	err := c.cc.Invoke(ctx, AgentsService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInReply)
	err := c.cc.Invoke(ctx, AgentsService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) CheckOut(ctx context.Context, in *CheckOutRequest, opts ...grpc.CallOption) (*CheckOutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOutReply)
	err := c.cc.Invoke(ctx, AgentsService_CheckOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) ListVisits(ctx context.Context, in *ListVisitsRequest, opts ...grpc.CallOption) (*ListVisitsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVisitsReply)
	err := c.cc.Invoke(ctx, AgentsService_ListVisits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) AddVisitPhoto(ctx context.Context, in *AddVisitPhotoRequest, opts ...grpc.CallOption) (*AddVisitPhotoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVisitPhotoReply)
	err := c.cc.Invoke(ctx, AgentsService_AddVisitPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetVisitPhotos(ctx context.Context, in *GetVisitPhotosRequest, opts ...grpc.CallOption) (*GetVisitPhotosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVisitPhotosReply)
	err := c.cc.Invoke(ctx, AgentsService_GetVisitPhotos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) OnboardStore(ctx context.Context, in *OnboardStoreRequest, opts ...grpc.CallOption) (*OnboardStoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnboardStoreReply)
	err := c.cc.Invoke(ctx, AgentsService_OnboardStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsServiceClient) GetAgentReport(ctx context.Context, in *GetAgentReportRequest, opts ...grpc.CallOption) (*GetAgentReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentReportReply)
	err := c.cc.Invoke(ctx, AgentsService_GetAgentReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsServiceServer is the server API for AgentsService service.
// All implementations must embed UnimplementedAgentsServiceServer
// for forward compatibility.
type AgentsServiceServer interface {
	// Story 6.1: Routes
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteReply, error)
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteReply, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesReply, error)
	// Story 6.2: GPS Visits
	CheckIn(context.Context, *CheckInRequest) (*CheckInReply, error)
	CheckOut(context.Context, *CheckOutRequest) (*CheckOutReply, error)
	ListVisits(context.Context, *ListVisitsRequest) (*ListVisitsReply, error)
	// Story 6.3: Photo Reports
	AddVisitPhoto(context.Context, *AddVisitPhotoRequest) (*AddVisitPhotoReply, error)
	GetVisitPhotos(context.Context, *GetVisitPhotosRequest) (*GetVisitPhotosReply, error)
	// Story 6.4: New Store Onboarding
	OnboardStore(context.Context, *OnboardStoreRequest) (*OnboardStoreReply, error)
	// Story 6.5: Agent Reports
	GetAgentReport(context.Context, *GetAgentReportRequest) (*GetAgentReportReply, error)
	mustEmbedUnimplementedAgentsServiceServer()
}

// UnimplementedAgentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentsServiceServer struct{}

func (UnimplementedAgentsServiceServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedAgentsServiceServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedAgentsServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedAgentsServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedAgentsServiceServer) CheckOut(context.Context, *CheckOutRequest) (*CheckOutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckOut not implemented")
}
func (UnimplementedAgentsServiceServer) ListVisits(context.Context, *ListVisitsRequest) (*ListVisitsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVisits not implemented")
}
func (UnimplementedAgentsServiceServer) AddVisitPhoto(context.Context, *AddVisitPhotoRequest) (*AddVisitPhotoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVisitPhoto not implemented")
}
func (UnimplementedAgentsServiceServer) GetVisitPhotos(context.Context, *GetVisitPhotosRequest) (*GetVisitPhotosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVisitPhotos not implemented")
}
func (UnimplementedAgentsServiceServer) OnboardStore(context.Context, *OnboardStoreRequest) (*OnboardStoreReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OnboardStore not implemented")
}
func (UnimplementedAgentsServiceServer) GetAgentReport(context.Context, *GetAgentReportRequest) (*GetAgentReportReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentReport not implemented")
}
func (UnimplementedAgentsServiceServer) mustEmbedUnimplementedAgentsServiceServer() {}
func (UnimplementedAgentsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAgentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentsServiceServer will
// result in compilation errors.
type UnsafeAgentsServiceServer interface {
	mustEmbedUnimplementedAgentsServiceServer()
}

func RegisterAgentsServiceServer(s grpc.ServiceRegistrar, srv AgentsServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentsService_ServiceDesc, srv)
}

func _AgentsService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_CheckOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).CheckOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_CheckOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).CheckOut(ctx, req.(*CheckOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_ListVisits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVisitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).ListVisits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_ListVisits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).ListVisits(ctx, req.(*ListVisitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_AddVisitPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVisitPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).AddVisitPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_AddVisitPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).AddVisitPhoto(ctx, req.(*AddVisitPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetVisitPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetVisitPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetVisitPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetVisitPhotos(ctx, req.(*GetVisitPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_OnboardStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).OnboardStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_OnboardStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).OnboardStore(ctx, req.(*OnboardStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsService_GetAgentReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServiceServer).GetAgentReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsService_GetAgentReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServiceServer).GetAgentReport(ctx, req.(*GetAgentReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentsService_ServiceDesc is the grpc.ServiceDesc for AgentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agents.v1.AgentsService",
	HandlerType: (*AgentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _AgentsService_CreateRoute_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _AgentsService_GetRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _AgentsService_ListRoutes_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _AgentsService_CheckIn_Handler,
		},
		{
			MethodName: "CheckOut",
			Handler:    _AgentsService_CheckOut_Handler,
		},
		{
			MethodName: "ListVisits",
			Handler:    _AgentsService_ListVisits_Handler,
		},
		{
			MethodName: "AddVisitPhoto",
			Handler:    _AgentsService_AddVisitPhoto_Handler,
		},
		{
			MethodName: "GetVisitPhotos",
			Handler:    _AgentsService_GetVisitPhotos_Handler,
		},
		{
			MethodName: "OnboardStore",
			Handler:    _AgentsService_OnboardStore_Handler,
		},
		{
			MethodName: "GetAgentReport",
			Handler:    _AgentsService_GetAgentReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/agents/v1/agents.proto",
}
