// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/agents/v1/models.proto

package agents_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       int64                  `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // PLANNED, IN_PROGRESS, COMPLETED
	Points        []*RoutePoint          `protobuf:"bytes,6,rep,name=points,proto3" json:"points,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_agents_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Route) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Route) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *Route) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Route) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Route) GetPoints() []*RoutePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Route) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Route) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoutePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId       int64                  `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	StoreTenantId int64                  `protobuf:"varint,3,opt,name=store_tenant_id,json=storeTenantId,proto3" json:"store_tenant_id,omitempty"`
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	VisitId       int64                  `protobuf:"varint,5,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePoint) Reset() {
	*x = RoutePoint{}
	mi := &file_api_agents_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePoint) ProtoMessage() {}

func (x *RoutePoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePoint.ProtoReflect.Descriptor instead.
func (*RoutePoint) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *RoutePoint) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutePoint) GetRouteId() int64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *RoutePoint) GetStoreTenantId() int64 {
	if x != nil {
		return x.StoreTenantId
	}
	return 0
}

func (x *RoutePoint) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *RoutePoint) GetVisitId() int64 {
	if x != nil {
		return x.VisitId
	}
	return 0
}

func (x *RoutePoint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Visit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoutePointId    int64                  `protobuf:"varint,3,opt,name=route_point_id,json=routePointId,proto3" json:"route_point_id,omitempty"`
	AgentId         int64                  `protobuf:"varint,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CheckinLat      string                 `protobuf:"bytes,5,opt,name=checkin_lat,json=checkinLat,proto3" json:"checkin_lat,omitempty"`
	CheckinLon      string                 `protobuf:"bytes,6,opt,name=checkin_lon,json=checkinLon,proto3" json:"checkin_lon,omitempty"`
	CheckinAt       string                 `protobuf:"bytes,7,opt,name=checkin_at,json=checkinAt,proto3" json:"checkin_at,omitempty"`
	CheckoutLat     string                 `protobuf:"bytes,8,opt,name=checkout_lat,json=checkoutLat,proto3" json:"checkout_lat,omitempty"`
	CheckoutLon     string                 `protobuf:"bytes,9,opt,name=checkout_lon,json=checkoutLon,proto3" json:"checkout_lon,omitempty"`
	CheckoutAt      string                 `protobuf:"bytes,10,opt,name=checkout_at,json=checkoutAt,proto3" json:"checkout_at,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,11,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Photos          []*VisitPhoto          `protobuf:"bytes,12,rep,name=photos,proto3" json:"photos,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Visit) Reset() {
	*x = Visit{}
	mi := &file_api_agents_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Visit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Visit) ProtoMessage() {}

func (x *Visit) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Visit.ProtoReflect.Descriptor instead.
func (*Visit) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *Visit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Visit) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Visit) GetRoutePointId() int64 {
	if x != nil {
		return x.RoutePointId
	}
	return 0
}

func (x *Visit) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *Visit) GetCheckinLat() string {
	if x != nil {
		return x.CheckinLat
	}
	return ""
}

func (x *Visit) GetCheckinLon() string {
	if x != nil {
		return x.CheckinLon
	}
	return ""
}

func (x *Visit) GetCheckinAt() string {
	if x != nil {
		return x.CheckinAt
	}
	return ""
}

func (x *Visit) GetCheckoutLat() string {
	if x != nil {
		return x.CheckoutLat
	}
	return ""
}

func (x *Visit) GetCheckoutLon() string {
	if x != nil {
		return x.CheckoutLon
	}
	return ""
}

func (x *Visit) GetCheckoutAt() string {
	if x != nil {
		return x.CheckoutAt
	}
	return ""
}

func (x *Visit) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Visit) GetPhotos() []*VisitPhoto {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Visit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type VisitPhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VisitId       int64                  `protobuf:"varint,2,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,3,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitPhoto) Reset() {
	*x = VisitPhoto{}
	mi := &file_api_agents_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitPhoto) ProtoMessage() {}

func (x *VisitPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitPhoto.ProtoReflect.Descriptor instead.
func (*VisitPhoto) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *VisitPhoto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VisitPhoto) GetVisitId() int64 {
	if x != nil {
		return x.VisitId
	}
	return 0
}

func (x *VisitPhoto) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *VisitPhoto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AgentReport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentId              int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DateFrom             string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	VisitsCount          int32                  `protobuf:"varint,4,opt,name=visits_count,json=visitsCount,proto3" json:"visits_count,omitempty"`
	OrdersCount          int32                  `protobuf:"varint,5,opt,name=orders_count,json=ordersCount,proto3" json:"orders_count,omitempty"`
	OnboardingsCount     int32                  `protobuf:"varint,6,opt,name=onboardings_count,json=onboardingsCount,proto3" json:"onboardings_count,omitempty"`
	TotalRoutePoints     int32                  `protobuf:"varint,7,opt,name=total_route_points,json=totalRoutePoints,proto3" json:"total_route_points,omitempty"`
	CompletedRoutePoints int32                  `protobuf:"varint,8,opt,name=completed_route_points,json=completedRoutePoints,proto3" json:"completed_route_points,omitempty"`
	RouteCompletionPct   float64                `protobuf:"fixed64,9,opt,name=route_completion_pct,json=routeCompletionPct,proto3" json:"route_completion_pct,omitempty"`
	TotalDurationSeconds int64                  `protobuf:"varint,10,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentReport) Reset() {
	*x = AgentReport{}
	mi := &file_api_agents_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReport) ProtoMessage() {}

func (x *AgentReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_agents_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReport.ProtoReflect.Descriptor instead.
func (*AgentReport) Descriptor() ([]byte, []int) {
	return file_api_agents_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *AgentReport) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentReport) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *AgentReport) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *AgentReport) GetVisitsCount() int32 {
	if x != nil {
		return x.VisitsCount
	}
	return 0
}

func (x *AgentReport) GetOrdersCount() int32 {
	if x != nil {
		return x.OrdersCount
	}
	return 0
}

func (x *AgentReport) GetOnboardingsCount() int32 {
	if x != nil {
		return x.OnboardingsCount
	}
	return 0
}

func (x *AgentReport) GetTotalRoutePoints() int32 {
	if x != nil {
		return x.TotalRoutePoints
	}
	return 0
}

func (x *AgentReport) GetCompletedRoutePoints() int32 {
	if x != nil {
		return x.CompletedRoutePoints
	}
	return 0
}

func (x *AgentReport) GetRouteCompletionPct() float64 {
	if x != nil {
		return x.RouteCompletionPct
	}
	return 0
}

func (x *AgentReport) GetTotalDurationSeconds() int64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

var File_api_agents_v1_models_proto protoreflect.FileDescriptor

const file_api_agents_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agents/v1/models.proto\x12\tagents.v1\"\xe8\x01\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\x03R\aagentId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12-\n" +
	"\x06points\x18\x06 \x03(\v2\x15.agents.v1.RoutePointR\x06points\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xb6\x01\n" +
	"\n" +
	"RoutePoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\x03R\arouteId\x12&\n" +
	"\x0fstore_tenant_id\x18\x03 \x01(\x03R\rstoreTenantId\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x19\n" +
	"\bvisit_id\x18\x05 \x01(\x03R\avisitId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xb6\x03\n" +
	"\x05Visit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12$\n" +
	"\x0eroute_point_id\x18\x03 \x01(\x03R\froutePointId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\x03R\aagentId\x12\x1f\n" +
	"\vcheckin_lat\x18\x05 \x01(\tR\n" +
	"checkinLat\x12\x1f\n" +
	"\vcheckin_lon\x18\x06 \x01(\tR\n" +
	"checkinLon\x12\x1d\n" +
	"\n" +
	"checkin_at\x18\a \x01(\tR\tcheckinAt\x12!\n" +
	"\fcheckout_lat\x18\b \x01(\tR\vcheckoutLat\x12!\n" +
	"\fcheckout_lon\x18\t \x01(\tR\vcheckoutLon\x12\x1f\n" +
	"\vcheckout_at\x18\n" +
	" \x01(\tR\n" +
	"checkoutAt\x12)\n" +
	"\x10duration_seconds\x18\v \x01(\x03R\x0fdurationSeconds\x12-\n" +
	"\x06photos\x18\f \x03(\v2\x15.agents.v1.VisitPhotoR\x06photos\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"s\n" +
	"\n" +
	"VisitPhoto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvisit_id\x18\x02 \x01(\x03R\avisitId\x12\x1b\n" +
	"\tmedia_url\x18\x03 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x9d\x03\n" +
	"\vAgentReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x12!\n" +
	"\fvisits_count\x18\x04 \x01(\x05R\vvisitsCount\x12!\n" +
	"\forders_count\x18\x05 \x01(\x05R\vordersCount\x12+\n" +
	"\x11onboardings_count\x18\x06 \x01(\x05R\x10onboardingsCount\x12,\n" +
	"\x12total_route_points\x18\a \x01(\x05R\x10totalRoutePoints\x124\n" +
	"\x16completed_route_points\x18\b \x01(\x05R\x14completedRoutePoints\x120\n" +
	"\x14route_completion_pct\x18\t \x01(\x01R\x12routeCompletionPct\x124\n" +
	"\x16total_duration_seconds\x18\n" +
	" \x01(\x03R\x14totalDurationSecondsB@Z>gitlab.calendaria.team/services/agents/api/agents/v1;agents_v1b\x06proto3"

var (
	file_api_agents_v1_models_proto_rawDescOnce sync.Once
	file_api_agents_v1_models_proto_rawDescData []byte
)

func file_api_agents_v1_models_proto_rawDescGZIP() []byte {
	file_api_agents_v1_models_proto_rawDescOnce.Do(func() {
		file_api_agents_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agents_v1_models_proto_rawDesc), len(file_api_agents_v1_models_proto_rawDesc)))
	})
	return file_api_agents_v1_models_proto_rawDescData
}

var file_api_agents_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_agents_v1_models_proto_goTypes = []any{
	(*Route)(nil),       // 0: agents.v1.Route
	(*RoutePoint)(nil),  // 1: agents.v1.RoutePoint
	(*Visit)(nil),       // 2: agents.v1.Visit
	(*VisitPhoto)(nil),  // 3: agents.v1.VisitPhoto
	(*AgentReport)(nil), // 4: agents.v1.AgentReport
}
var file_api_agents_v1_models_proto_depIdxs = []int32{
	1, // 0: agents.v1.Route.points:type_name -> agents.v1.RoutePoint
	3, // 1: agents.v1.Visit.photos:type_name -> agents.v1.VisitPhoto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_agents_v1_models_proto_init() }
func file_api_agents_v1_models_proto_init() {
	if File_api_agents_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agents_v1_models_proto_rawDesc), len(file_api_agents_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_agents_v1_models_proto_goTypes,
		DependencyIndexes: file_api_agents_v1_models_proto_depIdxs,
		MessageInfos:      file_api_agents_v1_models_proto_msgTypes,
	}.Build()
	File_api_agents_v1_models_proto = out.File
	file_api_agents_v1_models_proto_goTypes = nil
	file_api_agents_v1_models_proto_depIdxs = nil
}
