// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OnboardingsColumns holds the columns for the "onboardings" table.
	OnboardingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "agent_id", Type: field.TypeInt64},
		{Name: "new_tenant_id", Type: field.TypeInt64},
		{Name: "store_name", Type: field.TypeString},
		{Name: "owner_phone", Type: field.TypeString},
	}
	// OnboardingsTable holds the schema information for the "onboardings" table.
	OnboardingsTable = &schema.Table{
		Name:       "onboardings",
		Columns:    OnboardingsColumns,
		PrimaryKey: []*schema.Column{OnboardingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "onboarding_tenant_id_agent_id",
				Unique:  false,
				Columns: []*schema.Column{OnboardingsColumns[3], OnboardingsColumns[4]},
			},
		},
	}
	// RoutesColumns holds the columns for the "routes" table.
	RoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "agent_id", Type: field.TypeInt64},
		{Name: "date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PLANNED", "IN_PROGRESS", "COMPLETED"}, Default: "PLANNED"},
	}
	// RoutesTable holds the schema information for the "routes" table.
	RoutesTable = &schema.Table{
		Name:       "routes",
		Columns:    RoutesColumns,
		PrimaryKey: []*schema.Column{RoutesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "route_tenant_id_agent_id_date",
				Unique:  false,
				Columns: []*schema.Column{RoutesColumns[3], RoutesColumns[4], RoutesColumns[5]},
			},
		},
	}
	// RoutePointsColumns holds the columns for the "route_points" table.
	RoutePointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "store_tenant_id", Type: field.TypeInt64},
		{Name: "order_num", Type: field.TypeInt32},
		{Name: "visit_id", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "route_id", Type: field.TypeInt64},
	}
	// RoutePointsTable holds the schema information for the "route_points" table.
	RoutePointsTable = &schema.Table{
		Name:       "route_points",
		Columns:    RoutePointsColumns,
		PrimaryKey: []*schema.Column{RoutePointsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "route_points_routes_points",
				Columns:    []*schema.Column{RoutePointsColumns[6]},
				RefColumns: []*schema.Column{RoutesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "routepoint_route_id_order_num",
				Unique:  false,
				Columns: []*schema.Column{RoutePointsColumns[6], RoutePointsColumns[4]},
			},
		},
	}
	// VisitsColumns holds the columns for the "visits" table.
	VisitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "route_point_id", Type: field.TypeInt64},
		{Name: "agent_id", Type: field.TypeInt64},
		{Name: "checkin_lat", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "checkin_lon", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "checkin_at", Type: field.TypeTime},
		{Name: "checkout_lat", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "checkout_lon", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "checkout_at", Type: field.TypeTime, Nullable: true},
		{Name: "duration_seconds", Type: field.TypeInt64, Nullable: true, Default: 0},
	}
	// VisitsTable holds the schema information for the "visits" table.
	VisitsTable = &schema.Table{
		Name:       "visits",
		Columns:    VisitsColumns,
		PrimaryKey: []*schema.Column{VisitsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "visit_tenant_id_agent_id",
				Unique:  false,
				Columns: []*schema.Column{VisitsColumns[3], VisitsColumns[5]},
			},
			{
				Name:    "visit_route_point_id",
				Unique:  false,
				Columns: []*schema.Column{VisitsColumns[4]},
			},
		},
	}
	// VisitPhotosColumns holds the columns for the "visit_photos" table.
	VisitPhotosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "media_url", Type: field.TypeString},
		{Name: "visit_id", Type: field.TypeInt64},
	}
	// VisitPhotosTable holds the schema information for the "visit_photos" table.
	VisitPhotosTable = &schema.Table{
		Name:       "visit_photos",
		Columns:    VisitPhotosColumns,
		PrimaryKey: []*schema.Column{VisitPhotosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "visit_photos_visits_photos",
				Columns:    []*schema.Column{VisitPhotosColumns[4]},
				RefColumns: []*schema.Column{VisitsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "visitphoto_visit_id",
				Unique:  false,
				Columns: []*schema.Column{VisitPhotosColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OnboardingsTable,
		RoutesTable,
		RoutePointsTable,
		VisitsTable,
		VisitPhotosTable,
	}
)

func init() {
	RoutePointsTable.ForeignKeys[0].RefTable = RoutesTable
	VisitPhotosTable.ForeignKeys[0].RefTable = VisitsTable
}
