// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/makesalekz/agents/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/agents/ent/onboarding"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Onboarding is the client for interacting with the Onboarding builders.
	Onboarding *OnboardingClient
	// Route is the client for interacting with the Route builders.
	Route *RouteClient
	// RoutePoint is the client for interacting with the RoutePoint builders.
	RoutePoint *RoutePointClient
	// Visit is the client for interacting with the Visit builders.
	Visit *VisitClient
	// VisitPhoto is the client for interacting with the VisitPhoto builders.
	VisitPhoto *VisitPhotoClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Onboarding = NewOnboardingClient(c.config)
	c.Route = NewRouteClient(c.config)
	c.RoutePoint = NewRoutePointClient(c.config)
	c.Visit = NewVisitClient(c.config)
	c.VisitPhoto = NewVisitPhotoClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Onboarding: NewOnboardingClient(cfg),
		Route:      NewRouteClient(cfg),
		RoutePoint: NewRoutePointClient(cfg),
		Visit:      NewVisitClient(cfg),
		VisitPhoto: NewVisitPhotoClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Onboarding: NewOnboardingClient(cfg),
		Route:      NewRouteClient(cfg),
		RoutePoint: NewRoutePointClient(cfg),
		Visit:      NewVisitClient(cfg),
		VisitPhoto: NewVisitPhotoClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Onboarding.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Onboarding.Use(hooks...)
	c.Route.Use(hooks...)
	c.RoutePoint.Use(hooks...)
	c.Visit.Use(hooks...)
	c.VisitPhoto.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Onboarding.Intercept(interceptors...)
	c.Route.Intercept(interceptors...)
	c.RoutePoint.Intercept(interceptors...)
	c.Visit.Intercept(interceptors...)
	c.VisitPhoto.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *OnboardingMutation:
		return c.Onboarding.mutate(ctx, m)
	case *RouteMutation:
		return c.Route.mutate(ctx, m)
	case *RoutePointMutation:
		return c.RoutePoint.mutate(ctx, m)
	case *VisitMutation:
		return c.Visit.mutate(ctx, m)
	case *VisitPhotoMutation:
		return c.VisitPhoto.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// OnboardingClient is a client for the Onboarding schema.
type OnboardingClient struct {
	config
}

// NewOnboardingClient returns a client for the Onboarding from the given config.
func NewOnboardingClient(c config) *OnboardingClient {
	return &OnboardingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `onboarding.Hooks(f(g(h())))`.
func (c *OnboardingClient) Use(hooks ...Hook) {
	c.hooks.Onboarding = append(c.hooks.Onboarding, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `onboarding.Intercept(f(g(h())))`.
func (c *OnboardingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Onboarding = append(c.inters.Onboarding, interceptors...)
}

// Create returns a builder for creating a Onboarding entity.
func (c *OnboardingClient) Create() *OnboardingCreate {
	mutation := newOnboardingMutation(c.config, OpCreate)
	return &OnboardingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Onboarding entities.
func (c *OnboardingClient) CreateBulk(builders ...*OnboardingCreate) *OnboardingCreateBulk {
	return &OnboardingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OnboardingClient) MapCreateBulk(slice any, setFunc func(*OnboardingCreate, int)) *OnboardingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OnboardingCreateBulk{err: fmt.Errorf("calling to OnboardingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OnboardingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OnboardingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Onboarding.
func (c *OnboardingClient) Update() *OnboardingUpdate {
	mutation := newOnboardingMutation(c.config, OpUpdate)
	return &OnboardingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OnboardingClient) UpdateOne(o *Onboarding) *OnboardingUpdateOne {
	mutation := newOnboardingMutation(c.config, OpUpdateOne, withOnboarding(o))
	return &OnboardingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OnboardingClient) UpdateOneID(id int64) *OnboardingUpdateOne {
	mutation := newOnboardingMutation(c.config, OpUpdateOne, withOnboardingID(id))
	return &OnboardingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Onboarding.
func (c *OnboardingClient) Delete() *OnboardingDelete {
	mutation := newOnboardingMutation(c.config, OpDelete)
	return &OnboardingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OnboardingClient) DeleteOne(o *Onboarding) *OnboardingDeleteOne {
	return c.DeleteOneID(o.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OnboardingClient) DeleteOneID(id int64) *OnboardingDeleteOne {
	builder := c.Delete().Where(onboarding.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OnboardingDeleteOne{builder}
}

// Query returns a query builder for Onboarding.
func (c *OnboardingClient) Query() *OnboardingQuery {
	return &OnboardingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOnboarding},
		inters: c.Interceptors(),
	}
}

// Get returns a Onboarding entity by its id.
func (c *OnboardingClient) Get(ctx context.Context, id int64) (*Onboarding, error) {
	return c.Query().Where(onboarding.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OnboardingClient) GetX(ctx context.Context, id int64) *Onboarding {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OnboardingClient) Hooks() []Hook {
	return c.hooks.Onboarding
}

// Interceptors returns the client interceptors.
func (c *OnboardingClient) Interceptors() []Interceptor {
	return c.inters.Onboarding
}

func (c *OnboardingClient) mutate(ctx context.Context, m *OnboardingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OnboardingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OnboardingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OnboardingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OnboardingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Onboarding mutation op: %q", m.Op())
	}
}

// RouteClient is a client for the Route schema.
type RouteClient struct {
	config
}

// NewRouteClient returns a client for the Route from the given config.
func NewRouteClient(c config) *RouteClient {
	return &RouteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `route.Hooks(f(g(h())))`.
func (c *RouteClient) Use(hooks ...Hook) {
	c.hooks.Route = append(c.hooks.Route, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `route.Intercept(f(g(h())))`.
func (c *RouteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Route = append(c.inters.Route, interceptors...)
}

// Create returns a builder for creating a Route entity.
func (c *RouteClient) Create() *RouteCreate {
	mutation := newRouteMutation(c.config, OpCreate)
	return &RouteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Route entities.
func (c *RouteClient) CreateBulk(builders ...*RouteCreate) *RouteCreateBulk {
	return &RouteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RouteClient) MapCreateBulk(slice any, setFunc func(*RouteCreate, int)) *RouteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RouteCreateBulk{err: fmt.Errorf("calling to RouteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RouteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RouteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Route.
func (c *RouteClient) Update() *RouteUpdate {
	mutation := newRouteMutation(c.config, OpUpdate)
	return &RouteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RouteClient) UpdateOne(r *Route) *RouteUpdateOne {
	mutation := newRouteMutation(c.config, OpUpdateOne, withRoute(r))
	return &RouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RouteClient) UpdateOneID(id int64) *RouteUpdateOne {
	mutation := newRouteMutation(c.config, OpUpdateOne, withRouteID(id))
	return &RouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Route.
func (c *RouteClient) Delete() *RouteDelete {
	mutation := newRouteMutation(c.config, OpDelete)
	return &RouteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RouteClient) DeleteOne(r *Route) *RouteDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RouteClient) DeleteOneID(id int64) *RouteDeleteOne {
	builder := c.Delete().Where(route.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RouteDeleteOne{builder}
}

// Query returns a query builder for Route.
func (c *RouteClient) Query() *RouteQuery {
	return &RouteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRoute},
		inters: c.Interceptors(),
	}
}

// Get returns a Route entity by its id.
func (c *RouteClient) Get(ctx context.Context, id int64) (*Route, error) {
	return c.Query().Where(route.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RouteClient) GetX(ctx context.Context, id int64) *Route {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPoints queries the points edge of a Route.
func (c *RouteClient) QueryPoints(r *Route) *RoutePointQuery {
	query := (&RoutePointClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(route.Table, route.FieldID, id),
			sqlgraph.To(routepoint.Table, routepoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, route.PointsTable, route.PointsColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RouteClient) Hooks() []Hook {
	return c.hooks.Route
}

// Interceptors returns the client interceptors.
func (c *RouteClient) Interceptors() []Interceptor {
	return c.inters.Route
}

func (c *RouteClient) mutate(ctx context.Context, m *RouteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RouteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RouteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RouteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RouteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Route mutation op: %q", m.Op())
	}
}

// RoutePointClient is a client for the RoutePoint schema.
type RoutePointClient struct {
	config
}

// NewRoutePointClient returns a client for the RoutePoint from the given config.
func NewRoutePointClient(c config) *RoutePointClient {
	return &RoutePointClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `routepoint.Hooks(f(g(h())))`.
func (c *RoutePointClient) Use(hooks ...Hook) {
	c.hooks.RoutePoint = append(c.hooks.RoutePoint, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `routepoint.Intercept(f(g(h())))`.
func (c *RoutePointClient) Intercept(interceptors ...Interceptor) {
	c.inters.RoutePoint = append(c.inters.RoutePoint, interceptors...)
}

// Create returns a builder for creating a RoutePoint entity.
func (c *RoutePointClient) Create() *RoutePointCreate {
	mutation := newRoutePointMutation(c.config, OpCreate)
	return &RoutePointCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RoutePoint entities.
func (c *RoutePointClient) CreateBulk(builders ...*RoutePointCreate) *RoutePointCreateBulk {
	return &RoutePointCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoutePointClient) MapCreateBulk(slice any, setFunc func(*RoutePointCreate, int)) *RoutePointCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoutePointCreateBulk{err: fmt.Errorf("calling to RoutePointClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoutePointCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoutePointCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RoutePoint.
func (c *RoutePointClient) Update() *RoutePointUpdate {
	mutation := newRoutePointMutation(c.config, OpUpdate)
	return &RoutePointUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoutePointClient) UpdateOne(rp *RoutePoint) *RoutePointUpdateOne {
	mutation := newRoutePointMutation(c.config, OpUpdateOne, withRoutePoint(rp))
	return &RoutePointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoutePointClient) UpdateOneID(id int64) *RoutePointUpdateOne {
	mutation := newRoutePointMutation(c.config, OpUpdateOne, withRoutePointID(id))
	return &RoutePointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RoutePoint.
func (c *RoutePointClient) Delete() *RoutePointDelete {
	mutation := newRoutePointMutation(c.config, OpDelete)
	return &RoutePointDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoutePointClient) DeleteOne(rp *RoutePoint) *RoutePointDeleteOne {
	return c.DeleteOneID(rp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoutePointClient) DeleteOneID(id int64) *RoutePointDeleteOne {
	builder := c.Delete().Where(routepoint.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoutePointDeleteOne{builder}
}

// Query returns a query builder for RoutePoint.
func (c *RoutePointClient) Query() *RoutePointQuery {
	return &RoutePointQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRoutePoint},
		inters: c.Interceptors(),
	}
}

// Get returns a RoutePoint entity by its id.
func (c *RoutePointClient) Get(ctx context.Context, id int64) (*RoutePoint, error) {
	return c.Query().Where(routepoint.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoutePointClient) GetX(ctx context.Context, id int64) *RoutePoint {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRoute queries the route edge of a RoutePoint.
func (c *RoutePointClient) QueryRoute(rp *RoutePoint) *RouteQuery {
	query := (&RouteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := rp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(routepoint.Table, routepoint.FieldID, id),
			sqlgraph.To(route.Table, route.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routepoint.RouteTable, routepoint.RouteColumn),
		)
		fromV = sqlgraph.Neighbors(rp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RoutePointClient) Hooks() []Hook {
	return c.hooks.RoutePoint
}

// Interceptors returns the client interceptors.
func (c *RoutePointClient) Interceptors() []Interceptor {
	return c.inters.RoutePoint
}

func (c *RoutePointClient) mutate(ctx context.Context, m *RoutePointMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoutePointCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoutePointUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoutePointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoutePointDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RoutePoint mutation op: %q", m.Op())
	}
}

// VisitClient is a client for the Visit schema.
type VisitClient struct {
	config
}

// NewVisitClient returns a client for the Visit from the given config.
func NewVisitClient(c config) *VisitClient {
	return &VisitClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `visit.Hooks(f(g(h())))`.
func (c *VisitClient) Use(hooks ...Hook) {
	c.hooks.Visit = append(c.hooks.Visit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `visit.Intercept(f(g(h())))`.
func (c *VisitClient) Intercept(interceptors ...Interceptor) {
	c.inters.Visit = append(c.inters.Visit, interceptors...)
}

// Create returns a builder for creating a Visit entity.
func (c *VisitClient) Create() *VisitCreate {
	mutation := newVisitMutation(c.config, OpCreate)
	return &VisitCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Visit entities.
func (c *VisitClient) CreateBulk(builders ...*VisitCreate) *VisitCreateBulk {
	return &VisitCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VisitClient) MapCreateBulk(slice any, setFunc func(*VisitCreate, int)) *VisitCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VisitCreateBulk{err: fmt.Errorf("calling to VisitClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VisitCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VisitCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Visit.
func (c *VisitClient) Update() *VisitUpdate {
	mutation := newVisitMutation(c.config, OpUpdate)
	return &VisitUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VisitClient) UpdateOne(v *Visit) *VisitUpdateOne {
	mutation := newVisitMutation(c.config, OpUpdateOne, withVisit(v))
	return &VisitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VisitClient) UpdateOneID(id int64) *VisitUpdateOne {
	mutation := newVisitMutation(c.config, OpUpdateOne, withVisitID(id))
	return &VisitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Visit.
func (c *VisitClient) Delete() *VisitDelete {
	mutation := newVisitMutation(c.config, OpDelete)
	return &VisitDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VisitClient) DeleteOne(v *Visit) *VisitDeleteOne {
	return c.DeleteOneID(v.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VisitClient) DeleteOneID(id int64) *VisitDeleteOne {
	builder := c.Delete().Where(visit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VisitDeleteOne{builder}
}

// Query returns a query builder for Visit.
func (c *VisitClient) Query() *VisitQuery {
	return &VisitQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVisit},
		inters: c.Interceptors(),
	}
}

// Get returns a Visit entity by its id.
func (c *VisitClient) Get(ctx context.Context, id int64) (*Visit, error) {
	return c.Query().Where(visit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VisitClient) GetX(ctx context.Context, id int64) *Visit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPhotos queries the photos edge of a Visit.
func (c *VisitClient) QueryPhotos(v *Visit) *VisitPhotoQuery {
	query := (&VisitPhotoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := v.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(visit.Table, visit.FieldID, id),
			sqlgraph.To(visitphoto.Table, visitphoto.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, visit.PhotosTable, visit.PhotosColumn),
		)
		fromV = sqlgraph.Neighbors(v.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VisitClient) Hooks() []Hook {
	return c.hooks.Visit
}

// Interceptors returns the client interceptors.
func (c *VisitClient) Interceptors() []Interceptor {
	return c.inters.Visit
}

func (c *VisitClient) mutate(ctx context.Context, m *VisitMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VisitCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VisitUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VisitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VisitDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Visit mutation op: %q", m.Op())
	}
}

// VisitPhotoClient is a client for the VisitPhoto schema.
type VisitPhotoClient struct {
	config
}

// NewVisitPhotoClient returns a client for the VisitPhoto from the given config.
func NewVisitPhotoClient(c config) *VisitPhotoClient {
	return &VisitPhotoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `visitphoto.Hooks(f(g(h())))`.
func (c *VisitPhotoClient) Use(hooks ...Hook) {
	c.hooks.VisitPhoto = append(c.hooks.VisitPhoto, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `visitphoto.Intercept(f(g(h())))`.
func (c *VisitPhotoClient) Intercept(interceptors ...Interceptor) {
	c.inters.VisitPhoto = append(c.inters.VisitPhoto, interceptors...)
}

// Create returns a builder for creating a VisitPhoto entity.
func (c *VisitPhotoClient) Create() *VisitPhotoCreate {
	mutation := newVisitPhotoMutation(c.config, OpCreate)
	return &VisitPhotoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of VisitPhoto entities.
func (c *VisitPhotoClient) CreateBulk(builders ...*VisitPhotoCreate) *VisitPhotoCreateBulk {
	return &VisitPhotoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *VisitPhotoClient) MapCreateBulk(slice any, setFunc func(*VisitPhotoCreate, int)) *VisitPhotoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &VisitPhotoCreateBulk{err: fmt.Errorf("calling to VisitPhotoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*VisitPhotoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &VisitPhotoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for VisitPhoto.
func (c *VisitPhotoClient) Update() *VisitPhotoUpdate {
	mutation := newVisitPhotoMutation(c.config, OpUpdate)
	return &VisitPhotoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *VisitPhotoClient) UpdateOne(vp *VisitPhoto) *VisitPhotoUpdateOne {
	mutation := newVisitPhotoMutation(c.config, OpUpdateOne, withVisitPhoto(vp))
	return &VisitPhotoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *VisitPhotoClient) UpdateOneID(id int64) *VisitPhotoUpdateOne {
	mutation := newVisitPhotoMutation(c.config, OpUpdateOne, withVisitPhotoID(id))
	return &VisitPhotoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for VisitPhoto.
func (c *VisitPhotoClient) Delete() *VisitPhotoDelete {
	mutation := newVisitPhotoMutation(c.config, OpDelete)
	return &VisitPhotoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *VisitPhotoClient) DeleteOne(vp *VisitPhoto) *VisitPhotoDeleteOne {
	return c.DeleteOneID(vp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *VisitPhotoClient) DeleteOneID(id int64) *VisitPhotoDeleteOne {
	builder := c.Delete().Where(visitphoto.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &VisitPhotoDeleteOne{builder}
}

// Query returns a query builder for VisitPhoto.
func (c *VisitPhotoClient) Query() *VisitPhotoQuery {
	return &VisitPhotoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeVisitPhoto},
		inters: c.Interceptors(),
	}
}

// Get returns a VisitPhoto entity by its id.
func (c *VisitPhotoClient) Get(ctx context.Context, id int64) (*VisitPhoto, error) {
	return c.Query().Where(visitphoto.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *VisitPhotoClient) GetX(ctx context.Context, id int64) *VisitPhoto {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryVisit queries the visit edge of a VisitPhoto.
func (c *VisitPhotoClient) QueryVisit(vp *VisitPhoto) *VisitQuery {
	query := (&VisitClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := vp.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(visitphoto.Table, visitphoto.FieldID, id),
			sqlgraph.To(visit.Table, visit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, visitphoto.VisitTable, visitphoto.VisitColumn),
		)
		fromV = sqlgraph.Neighbors(vp.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *VisitPhotoClient) Hooks() []Hook {
	return c.hooks.VisitPhoto
}

// Interceptors returns the client interceptors.
func (c *VisitPhotoClient) Interceptors() []Interceptor {
	return c.inters.VisitPhoto
}

func (c *VisitPhotoClient) mutate(ctx context.Context, m *VisitPhotoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&VisitPhotoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&VisitPhotoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&VisitPhotoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&VisitPhotoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown VisitPhoto mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Onboarding, Route, RoutePoint, Visit, VisitPhoto []ent.Hook
	}
	inters struct {
		Onboarding, Route, RoutePoint, Visit, VisitPhoto []ent.Interceptor
	}
)
