// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/onboarding"
	"github.com/makesalekz/agents/ent/predicate"
)

// OnboardingQuery is the builder for querying Onboarding entities.
type OnboardingQuery struct {
	config
	ctx        *QueryContext
	order      []onboarding.OrderOption
	inters     []Interceptor
	predicates []predicate.Onboarding
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OnboardingQuery builder.
func (oq *OnboardingQuery) Where(ps ...predicate.Onboarding) *OnboardingQuery {
	oq.predicates = append(oq.predicates, ps...)
	return oq
}

// Limit the number of records to be returned by this query.
func (oq *OnboardingQuery) Limit(limit int) *OnboardingQuery {
	oq.ctx.Limit = &limit
	return oq
}

// Offset to start from.
func (oq *OnboardingQuery) Offset(offset int) *OnboardingQuery {
	oq.ctx.Offset = &offset
	return oq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oq *OnboardingQuery) Unique(unique bool) *OnboardingQuery {
	oq.ctx.Unique = &unique
	return oq
}

// Order specifies how the records should be ordered.
func (oq *OnboardingQuery) Order(o ...onboarding.OrderOption) *OnboardingQuery {
	oq.order = append(oq.order, o...)
	return oq
}

// First returns the first Onboarding entity from the query.
// Returns a *NotFoundError when no Onboarding was found.
func (oq *OnboardingQuery) First(ctx context.Context) (*Onboarding, error) {
	nodes, err := oq.Limit(1).All(setContextOp(ctx, oq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{onboarding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oq *OnboardingQuery) FirstX(ctx context.Context) *Onboarding {
	node, err := oq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Onboarding ID from the query.
// Returns a *NotFoundError when no Onboarding ID was found.
func (oq *OnboardingQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = oq.Limit(1).IDs(setContextOp(ctx, oq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{onboarding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oq *OnboardingQuery) FirstIDX(ctx context.Context) int64 {
	id, err := oq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Onboarding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Onboarding entity is found.
// Returns a *NotFoundError when no Onboarding entities are found.
func (oq *OnboardingQuery) Only(ctx context.Context) (*Onboarding, error) {
	nodes, err := oq.Limit(2).All(setContextOp(ctx, oq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{onboarding.Label}
	default:
		return nil, &NotSingularError{onboarding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oq *OnboardingQuery) OnlyX(ctx context.Context) *Onboarding {
	node, err := oq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Onboarding ID in the query.
// Returns a *NotSingularError when more than one Onboarding ID is found.
// Returns a *NotFoundError when no entities are found.
func (oq *OnboardingQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = oq.Limit(2).IDs(setContextOp(ctx, oq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{onboarding.Label}
	default:
		err = &NotSingularError{onboarding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oq *OnboardingQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := oq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Onboardings.
func (oq *OnboardingQuery) All(ctx context.Context) ([]*Onboarding, error) {
	ctx = setContextOp(ctx, oq.ctx, ent.OpQueryAll)
	if err := oq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Onboarding, *OnboardingQuery]()
	return withInterceptors[[]*Onboarding](ctx, oq, qr, oq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oq *OnboardingQuery) AllX(ctx context.Context) []*Onboarding {
	nodes, err := oq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Onboarding IDs.
func (oq *OnboardingQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if oq.ctx.Unique == nil && oq.path != nil {
		oq.Unique(true)
	}
	ctx = setContextOp(ctx, oq.ctx, ent.OpQueryIDs)
	if err = oq.Select(onboarding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oq *OnboardingQuery) IDsX(ctx context.Context) []int64 {
	ids, err := oq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oq *OnboardingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oq.ctx, ent.OpQueryCount)
	if err := oq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oq, querierCount[*OnboardingQuery](), oq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oq *OnboardingQuery) CountX(ctx context.Context) int {
	count, err := oq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oq *OnboardingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oq.ctx, ent.OpQueryExist)
	switch _, err := oq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oq *OnboardingQuery) ExistX(ctx context.Context) bool {
	exist, err := oq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OnboardingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oq *OnboardingQuery) Clone() *OnboardingQuery {
	if oq == nil {
		return nil
	}
	return &OnboardingQuery{
		config:     oq.config,
		ctx:        oq.ctx.Clone(),
		order:      append([]onboarding.OrderOption{}, oq.order...),
		inters:     append([]Interceptor{}, oq.inters...),
		predicates: append([]predicate.Onboarding{}, oq.predicates...),
		// clone intermediate query.
		sql:  oq.sql.Clone(),
		path: oq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Onboarding.Query().
//		GroupBy(onboarding.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oq *OnboardingQuery) GroupBy(field string, fields ...string) *OnboardingGroupBy {
	oq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OnboardingGroupBy{build: oq}
	grbuild.flds = &oq.ctx.Fields
	grbuild.label = onboarding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Onboarding.Query().
//		Select(onboarding.FieldCreatedAt).
//		Scan(ctx, &v)
func (oq *OnboardingQuery) Select(fields ...string) *OnboardingSelect {
	oq.ctx.Fields = append(oq.ctx.Fields, fields...)
	sbuild := &OnboardingSelect{OnboardingQuery: oq}
	sbuild.label = onboarding.Label
	sbuild.flds, sbuild.scan = &oq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OnboardingSelect configured with the given aggregations.
func (oq *OnboardingQuery) Aggregate(fns ...AggregateFunc) *OnboardingSelect {
	return oq.Select().Aggregate(fns...)
}

func (oq *OnboardingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oq); err != nil {
				return err
			}
		}
	}
	for _, f := range oq.ctx.Fields {
		if !onboarding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oq.path != nil {
		prev, err := oq.path(ctx)
		if err != nil {
			return err
		}
		oq.sql = prev
	}
	return nil
}

func (oq *OnboardingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Onboarding, error) {
	var (
		nodes = []*Onboarding{}
		_spec = oq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Onboarding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Onboarding{config: oq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(oq.modifiers) > 0 {
		_spec.Modifiers = oq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oq *OnboardingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oq.querySpec()
	if len(oq.modifiers) > 0 {
		_spec.Modifiers = oq.modifiers
	}
	_spec.Node.Columns = oq.ctx.Fields
	if len(oq.ctx.Fields) > 0 {
		_spec.Unique = oq.ctx.Unique != nil && *oq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oq.driver, _spec)
}

func (oq *OnboardingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(onboarding.Table, onboarding.Columns, sqlgraph.NewFieldSpec(onboarding.FieldID, field.TypeInt64))
	_spec.From = oq.sql
	if unique := oq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oq.path != nil {
		_spec.Unique = true
	}
	if fields := oq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, onboarding.FieldID)
		for i := range fields {
			if fields[i] != onboarding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oq *OnboardingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oq.driver.Dialect())
	t1 := builder.Table(onboarding.Table)
	columns := oq.ctx.Fields
	if len(columns) == 0 {
		columns = onboarding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oq.sql != nil {
		selector = oq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oq.ctx.Unique != nil && *oq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range oq.modifiers {
		m(selector)
	}
	for _, p := range oq.predicates {
		p(selector)
	}
	for _, p := range oq.order {
		p(selector)
	}
	if offset := oq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (oq *OnboardingQuery) Modify(modifiers ...func(s *sql.Selector)) *OnboardingSelect {
	oq.modifiers = append(oq.modifiers, modifiers...)
	return oq.Select()
}

// OnboardingGroupBy is the group-by builder for Onboarding entities.
type OnboardingGroupBy struct {
	selector
	build *OnboardingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ogb *OnboardingGroupBy) Aggregate(fns ...AggregateFunc) *OnboardingGroupBy {
	ogb.fns = append(ogb.fns, fns...)
	return ogb
}

// Scan applies the selector query and scans the result into the given value.
func (ogb *OnboardingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ogb.build.ctx, ent.OpQueryGroupBy)
	if err := ogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OnboardingQuery, *OnboardingGroupBy](ctx, ogb.build, ogb, ogb.build.inters, v)
}

func (ogb *OnboardingGroupBy) sqlScan(ctx context.Context, root *OnboardingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ogb.fns))
	for _, fn := range ogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ogb.flds)+len(ogb.fns))
		for _, f := range *ogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OnboardingSelect is the builder for selecting fields of Onboarding entities.
type OnboardingSelect struct {
	*OnboardingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (os *OnboardingSelect) Aggregate(fns ...AggregateFunc) *OnboardingSelect {
	os.fns = append(os.fns, fns...)
	return os
}

// Scan applies the selector query and scans the result into the given value.
func (os *OnboardingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, os.ctx, ent.OpQuerySelect)
	if err := os.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OnboardingQuery, *OnboardingSelect](ctx, os.OnboardingQuery, os, os.inters, v)
}

func (os *OnboardingSelect) sqlScan(ctx context.Context, root *OnboardingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(os.fns))
	for _, fn := range os.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*os.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := os.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (os *OnboardingSelect) Modify(modifiers ...func(s *sql.Selector)) *OnboardingSelect {
	os.modifiers = append(os.modifiers, modifiers...)
	return os
}
