// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/agents/ent/onboarding"
)

// OnboardingCreate is the builder for creating a Onboarding entity.
type OnboardingCreate struct {
	config
	mutation *OnboardingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (oc *OnboardingCreate) SetCreatedAt(t time.Time) *OnboardingCreate {
	oc.mutation.SetCreatedAt(t)
	return oc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oc *OnboardingCreate) SetNillableCreatedAt(t *time.Time) *OnboardingCreate {
	if t != nil {
		oc.SetCreatedAt(*t)
	}
	return oc
}

// SetUpdatedAt sets the "updated_at" field.
func (oc *OnboardingCreate) SetUpdatedAt(t time.Time) *OnboardingCreate {
	oc.mutation.SetUpdatedAt(t)
	return oc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oc *OnboardingCreate) SetNillableUpdatedAt(t *time.Time) *OnboardingCreate {
	if t != nil {
		oc.SetUpdatedAt(*t)
	}
	return oc
}

// SetTenantID sets the "tenant_id" field.
func (oc *OnboardingCreate) SetTenantID(i int64) *OnboardingCreate {
	oc.mutation.SetTenantID(i)
	return oc
}

// SetAgentID sets the "agent_id" field.
func (oc *OnboardingCreate) SetAgentID(i int64) *OnboardingCreate {
	oc.mutation.SetAgentID(i)
	return oc
}

// SetNewTenantID sets the "new_tenant_id" field.
func (oc *OnboardingCreate) SetNewTenantID(i int64) *OnboardingCreate {
	oc.mutation.SetNewTenantID(i)
	return oc
}

// SetStoreName sets the "store_name" field.
func (oc *OnboardingCreate) SetStoreName(s string) *OnboardingCreate {
	oc.mutation.SetStoreName(s)
	return oc
}

// SetOwnerPhone sets the "owner_phone" field.
func (oc *OnboardingCreate) SetOwnerPhone(s string) *OnboardingCreate {
	oc.mutation.SetOwnerPhone(s)
	return oc
}

// SetID sets the "id" field.
func (oc *OnboardingCreate) SetID(i int64) *OnboardingCreate {
	oc.mutation.SetID(i)
	return oc
}

// Mutation returns the OnboardingMutation object of the builder.
func (oc *OnboardingCreate) Mutation() *OnboardingMutation {
	return oc.mutation
}

// Save creates the Onboarding in the database.
func (oc *OnboardingCreate) Save(ctx context.Context) (*Onboarding, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OnboardingCreate) SaveX(ctx context.Context) *Onboarding {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OnboardingCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OnboardingCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OnboardingCreate) defaults() {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		v := onboarding.DefaultCreatedAt()
		oc.mutation.SetCreatedAt(v)
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		v := onboarding.DefaultUpdatedAt()
		oc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OnboardingCreate) check() error {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Onboarding.created_at"`)}
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Onboarding.updated_at"`)}
	}
	if _, ok := oc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Onboarding.tenant_id"`)}
	}
	if _, ok := oc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Onboarding.agent_id"`)}
	}
	if _, ok := oc.mutation.NewTenantID(); !ok {
		return &ValidationError{Name: "new_tenant_id", err: errors.New(`ent: missing required field "Onboarding.new_tenant_id"`)}
	}
	if _, ok := oc.mutation.StoreName(); !ok {
		return &ValidationError{Name: "store_name", err: errors.New(`ent: missing required field "Onboarding.store_name"`)}
	}
	if _, ok := oc.mutation.OwnerPhone(); !ok {
		return &ValidationError{Name: "owner_phone", err: errors.New(`ent: missing required field "Onboarding.owner_phone"`)}
	}
	return nil
}

func (oc *OnboardingCreate) sqlSave(ctx context.Context) (*Onboarding, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OnboardingCreate) createSpec() (*Onboarding, *sqlgraph.CreateSpec) {
	var (
		_node = &Onboarding{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(onboarding.Table, sqlgraph.NewFieldSpec(onboarding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = oc.conflict
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := oc.mutation.CreatedAt(); ok {
		_spec.SetField(onboarding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := oc.mutation.UpdatedAt(); ok {
		_spec.SetField(onboarding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := oc.mutation.TenantID(); ok {
		_spec.SetField(onboarding.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := oc.mutation.AgentID(); ok {
		_spec.SetField(onboarding.FieldAgentID, field.TypeInt64, value)
		_node.AgentID = value
	}
	if value, ok := oc.mutation.NewTenantID(); ok {
		_spec.SetField(onboarding.FieldNewTenantID, field.TypeInt64, value)
		_node.NewTenantID = value
	}
	if value, ok := oc.mutation.StoreName(); ok {
		_spec.SetField(onboarding.FieldStoreName, field.TypeString, value)
		_node.StoreName = value
	}
	if value, ok := oc.mutation.OwnerPhone(); ok {
		_spec.SetField(onboarding.FieldOwnerPhone, field.TypeString, value)
		_node.OwnerPhone = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Onboarding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnboardingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (oc *OnboardingCreate) OnConflict(opts ...sql.ConflictOption) *OnboardingUpsertOne {
	oc.conflict = opts
	return &OnboardingUpsertOne{
		create: oc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (oc *OnboardingCreate) OnConflictColumns(columns ...string) *OnboardingUpsertOne {
	oc.conflict = append(oc.conflict, sql.ConflictColumns(columns...))
	return &OnboardingUpsertOne{
		create: oc,
	}
}

type (
	// OnboardingUpsertOne is the builder for "upsert"-ing
	//  one Onboarding node.
	OnboardingUpsertOne struct {
		create *OnboardingCreate
	}

	// OnboardingUpsert is the "OnConflict" setter.
	OnboardingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OnboardingUpsert) SetUpdatedAt(v time.Time) *OnboardingUpsert {
	u.Set(onboarding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnboardingUpsert) UpdateUpdatedAt() *OnboardingUpsert {
	u.SetExcluded(onboarding.FieldUpdatedAt)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *OnboardingUpsert) SetAgentID(v int64) *OnboardingUpsert {
	u.Set(onboarding.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *OnboardingUpsert) UpdateAgentID() *OnboardingUpsert {
	u.SetExcluded(onboarding.FieldAgentID)
	return u
}

// AddAgentID adds v to the "agent_id" field.
func (u *OnboardingUpsert) AddAgentID(v int64) *OnboardingUpsert {
	u.Add(onboarding.FieldAgentID, v)
	return u
}

// SetNewTenantID sets the "new_tenant_id" field.
func (u *OnboardingUpsert) SetNewTenantID(v int64) *OnboardingUpsert {
	u.Set(onboarding.FieldNewTenantID, v)
	return u
}

// UpdateNewTenantID sets the "new_tenant_id" field to the value that was provided on create.
func (u *OnboardingUpsert) UpdateNewTenantID() *OnboardingUpsert {
	u.SetExcluded(onboarding.FieldNewTenantID)
	return u
}

// AddNewTenantID adds v to the "new_tenant_id" field.
func (u *OnboardingUpsert) AddNewTenantID(v int64) *OnboardingUpsert {
	u.Add(onboarding.FieldNewTenantID, v)
	return u
}

// SetStoreName sets the "store_name" field.
func (u *OnboardingUpsert) SetStoreName(v string) *OnboardingUpsert {
	u.Set(onboarding.FieldStoreName, v)
	return u
}

// UpdateStoreName sets the "store_name" field to the value that was provided on create.
func (u *OnboardingUpsert) UpdateStoreName() *OnboardingUpsert {
	u.SetExcluded(onboarding.FieldStoreName)
	return u
}

// SetOwnerPhone sets the "owner_phone" field.
func (u *OnboardingUpsert) SetOwnerPhone(v string) *OnboardingUpsert {
	u.Set(onboarding.FieldOwnerPhone, v)
	return u
}

// UpdateOwnerPhone sets the "owner_phone" field to the value that was provided on create.
func (u *OnboardingUpsert) UpdateOwnerPhone() *OnboardingUpsert {
	u.SetExcluded(onboarding.FieldOwnerPhone)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(onboarding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OnboardingUpsertOne) UpdateNewValues() *OnboardingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(onboarding.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(onboarding.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(onboarding.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OnboardingUpsertOne) Ignore() *OnboardingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnboardingUpsertOne) DoNothing() *OnboardingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnboardingCreate.OnConflict
// documentation for more info.
func (u *OnboardingUpsertOne) Update(set func(*OnboardingUpsert)) *OnboardingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnboardingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnboardingUpsertOne) SetUpdatedAt(v time.Time) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnboardingUpsertOne) UpdateUpdatedAt() *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *OnboardingUpsertOne) SetAgentID(v int64) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *OnboardingUpsertOne) AddAgentID(v int64) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *OnboardingUpsertOne) UpdateAgentID() *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateAgentID()
	})
}

// SetNewTenantID sets the "new_tenant_id" field.
func (u *OnboardingUpsertOne) SetNewTenantID(v int64) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetNewTenantID(v)
	})
}

// AddNewTenantID adds v to the "new_tenant_id" field.
func (u *OnboardingUpsertOne) AddNewTenantID(v int64) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.AddNewTenantID(v)
	})
}

// UpdateNewTenantID sets the "new_tenant_id" field to the value that was provided on create.
func (u *OnboardingUpsertOne) UpdateNewTenantID() *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateNewTenantID()
	})
}

// SetStoreName sets the "store_name" field.
func (u *OnboardingUpsertOne) SetStoreName(v string) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetStoreName(v)
	})
}

// UpdateStoreName sets the "store_name" field to the value that was provided on create.
func (u *OnboardingUpsertOne) UpdateStoreName() *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateStoreName()
	})
}

// SetOwnerPhone sets the "owner_phone" field.
func (u *OnboardingUpsertOne) SetOwnerPhone(v string) *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetOwnerPhone(v)
	})
}

// UpdateOwnerPhone sets the "owner_phone" field to the value that was provided on create.
func (u *OnboardingUpsertOne) UpdateOwnerPhone() *OnboardingUpsertOne {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateOwnerPhone()
	})
}

// Exec executes the query.
func (u *OnboardingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnboardingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnboardingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OnboardingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OnboardingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnboardingCreateBulk is the builder for creating many Onboarding entities in bulk.
type OnboardingCreateBulk struct {
	config
	err      error
	builders []*OnboardingCreate
	conflict []sql.ConflictOption
}

// Save creates the Onboarding entities in the database.
func (ocb *OnboardingCreateBulk) Save(ctx context.Context) ([]*Onboarding, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Onboarding, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OnboardingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ocb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OnboardingCreateBulk) SaveX(ctx context.Context) []*Onboarding {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OnboardingCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OnboardingCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Onboarding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OnboardingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ocb *OnboardingCreateBulk) OnConflict(opts ...sql.ConflictOption) *OnboardingUpsertBulk {
	ocb.conflict = opts
	return &OnboardingUpsertBulk{
		create: ocb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ocb *OnboardingCreateBulk) OnConflictColumns(columns ...string) *OnboardingUpsertBulk {
	ocb.conflict = append(ocb.conflict, sql.ConflictColumns(columns...))
	return &OnboardingUpsertBulk{
		create: ocb,
	}
}

// OnboardingUpsertBulk is the builder for "upsert"-ing
// a bulk of Onboarding nodes.
type OnboardingUpsertBulk struct {
	create *OnboardingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(onboarding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OnboardingUpsertBulk) UpdateNewValues() *OnboardingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(onboarding.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(onboarding.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(onboarding.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Onboarding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OnboardingUpsertBulk) Ignore() *OnboardingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OnboardingUpsertBulk) DoNothing() *OnboardingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OnboardingCreateBulk.OnConflict
// documentation for more info.
func (u *OnboardingUpsertBulk) Update(set func(*OnboardingUpsert)) *OnboardingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OnboardingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OnboardingUpsertBulk) SetUpdatedAt(v time.Time) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OnboardingUpsertBulk) UpdateUpdatedAt() *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *OnboardingUpsertBulk) SetAgentID(v int64) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *OnboardingUpsertBulk) AddAgentID(v int64) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *OnboardingUpsertBulk) UpdateAgentID() *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateAgentID()
	})
}

// SetNewTenantID sets the "new_tenant_id" field.
func (u *OnboardingUpsertBulk) SetNewTenantID(v int64) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetNewTenantID(v)
	})
}

// AddNewTenantID adds v to the "new_tenant_id" field.
func (u *OnboardingUpsertBulk) AddNewTenantID(v int64) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.AddNewTenantID(v)
	})
}

// UpdateNewTenantID sets the "new_tenant_id" field to the value that was provided on create.
func (u *OnboardingUpsertBulk) UpdateNewTenantID() *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateNewTenantID()
	})
}

// SetStoreName sets the "store_name" field.
func (u *OnboardingUpsertBulk) SetStoreName(v string) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetStoreName(v)
	})
}

// UpdateStoreName sets the "store_name" field to the value that was provided on create.
func (u *OnboardingUpsertBulk) UpdateStoreName() *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateStoreName()
	})
}

// SetOwnerPhone sets the "owner_phone" field.
func (u *OnboardingUpsertBulk) SetOwnerPhone(v string) *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.SetOwnerPhone(v)
	})
}

// UpdateOwnerPhone sets the "owner_phone" field to the value that was provided on create.
func (u *OnboardingUpsertBulk) UpdateOwnerPhone() *OnboardingUpsertBulk {
	return u.Update(func(s *OnboardingUpsert) {
		s.UpdateOwnerPhone()
	})
}

// Exec executes the query.
func (u *OnboardingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OnboardingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OnboardingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OnboardingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
