// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/agents/ent/onboarding"
)

// Onboarding is the model entity for the Onboarding schema.
type Onboarding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID int64 `json:"agent_id,omitempty"`
	// NewTenantID holds the value of the "new_tenant_id" field.
	NewTenantID int64 `json:"new_tenant_id,omitempty"`
	// StoreName holds the value of the "store_name" field.
	StoreName string `json:"store_name,omitempty"`
	// OwnerPhone holds the value of the "owner_phone" field.
	OwnerPhone   string `json:"owner_phone,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Onboarding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onboarding.FieldID, onboarding.FieldTenantID, onboarding.FieldAgentID, onboarding.FieldNewTenantID:
			values[i] = new(sql.NullInt64)
		case onboarding.FieldStoreName, onboarding.FieldOwnerPhone:
			values[i] = new(sql.NullString)
		case onboarding.FieldCreatedAt, onboarding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Onboarding fields.
func (o *Onboarding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onboarding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int64(value.Int64)
		case onboarding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				o.CreatedAt = value.Time
			}
		case onboarding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				o.UpdatedAt = value.Time
			}
		case onboarding.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				o.TenantID = value.Int64
			}
		case onboarding.FieldAgentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				o.AgentID = value.Int64
			}
		case onboarding.FieldNewTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_tenant_id", values[i])
			} else if value.Valid {
				o.NewTenantID = value.Int64
			}
		case onboarding.FieldStoreName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field store_name", values[i])
			} else if value.Valid {
				o.StoreName = value.String
			}
		case onboarding.FieldOwnerPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_phone", values[i])
			} else if value.Valid {
				o.OwnerPhone = value.String
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Onboarding.
// This includes values selected through modifiers, order, etc.
func (o *Onboarding) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// Update returns a builder for updating this Onboarding.
// Note that you need to call Onboarding.Unwrap() before calling this method if this Onboarding
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Onboarding) Update() *OnboardingUpdateOne {
	return NewOnboardingClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Onboarding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Onboarding) Unwrap() *Onboarding {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Onboarding is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Onboarding) String() string {
	var builder strings.Builder
	builder.WriteString("Onboarding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	builder.WriteString("created_at=")
	builder.WriteString(o.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(o.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", o.TenantID))
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", o.AgentID))
	builder.WriteString(", ")
	builder.WriteString("new_tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", o.NewTenantID))
	builder.WriteString(", ")
	builder.WriteString("store_name=")
	builder.WriteString(o.StoreName)
	builder.WriteString(", ")
	builder.WriteString("owner_phone=")
	builder.WriteString(o.OwnerPhone)
	builder.WriteByte(')')
	return builder.String()
}

// Onboardings is a parsable slice of Onboarding.
type Onboardings []*Onboarding
