// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/predicate"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
)

// RoutePointQuery is the builder for querying RoutePoint entities.
type RoutePointQuery struct {
	config
	ctx        *QueryContext
	order      []routepoint.OrderOption
	inters     []Interceptor
	predicates []predicate.RoutePoint
	withRoute  *RouteQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoutePointQuery builder.
func (rpq *RoutePointQuery) Where(ps ...predicate.RoutePoint) *RoutePointQuery {
	rpq.predicates = append(rpq.predicates, ps...)
	return rpq
}

// Limit the number of records to be returned by this query.
func (rpq *RoutePointQuery) Limit(limit int) *RoutePointQuery {
	rpq.ctx.Limit = &limit
	return rpq
}

// Offset to start from.
func (rpq *RoutePointQuery) Offset(offset int) *RoutePointQuery {
	rpq.ctx.Offset = &offset
	return rpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rpq *RoutePointQuery) Unique(unique bool) *RoutePointQuery {
	rpq.ctx.Unique = &unique
	return rpq
}

// Order specifies how the records should be ordered.
func (rpq *RoutePointQuery) Order(o ...routepoint.OrderOption) *RoutePointQuery {
	rpq.order = append(rpq.order, o...)
	return rpq
}

// QueryRoute chains the current query on the "route" edge.
func (rpq *RoutePointQuery) QueryRoute() *RouteQuery {
	query := (&RouteClient{config: rpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(routepoint.Table, routepoint.FieldID, selector),
			sqlgraph.To(route.Table, route.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, routepoint.RouteTable, routepoint.RouteColumn),
		)
		fromU = sqlgraph.SetNeighbors(rpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoutePoint entity from the query.
// Returns a *NotFoundError when no RoutePoint was found.
func (rpq *RoutePointQuery) First(ctx context.Context) (*RoutePoint, error) {
	nodes, err := rpq.Limit(1).All(setContextOp(ctx, rpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{routepoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rpq *RoutePointQuery) FirstX(ctx context.Context) *RoutePoint {
	node, err := rpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoutePoint ID from the query.
// Returns a *NotFoundError when no RoutePoint ID was found.
func (rpq *RoutePointQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rpq.Limit(1).IDs(setContextOp(ctx, rpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{routepoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rpq *RoutePointQuery) FirstIDX(ctx context.Context) int64 {
	id, err := rpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoutePoint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoutePoint entity is found.
// Returns a *NotFoundError when no RoutePoint entities are found.
func (rpq *RoutePointQuery) Only(ctx context.Context) (*RoutePoint, error) {
	nodes, err := rpq.Limit(2).All(setContextOp(ctx, rpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{routepoint.Label}
	default:
		return nil, &NotSingularError{routepoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rpq *RoutePointQuery) OnlyX(ctx context.Context) *RoutePoint {
	node, err := rpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoutePoint ID in the query.
// Returns a *NotSingularError when more than one RoutePoint ID is found.
// Returns a *NotFoundError when no entities are found.
func (rpq *RoutePointQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = rpq.Limit(2).IDs(setContextOp(ctx, rpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{routepoint.Label}
	default:
		err = &NotSingularError{routepoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rpq *RoutePointQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := rpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoutePoints.
func (rpq *RoutePointQuery) All(ctx context.Context) ([]*RoutePoint, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryAll)
	if err := rpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoutePoint, *RoutePointQuery]()
	return withInterceptors[[]*RoutePoint](ctx, rpq, qr, rpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rpq *RoutePointQuery) AllX(ctx context.Context) []*RoutePoint {
	nodes, err := rpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoutePoint IDs.
func (rpq *RoutePointQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if rpq.ctx.Unique == nil && rpq.path != nil {
		rpq.Unique(true)
	}
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryIDs)
	if err = rpq.Select(routepoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rpq *RoutePointQuery) IDsX(ctx context.Context) []int64 {
	ids, err := rpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rpq *RoutePointQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryCount)
	if err := rpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rpq, querierCount[*RoutePointQuery](), rpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rpq *RoutePointQuery) CountX(ctx context.Context) int {
	count, err := rpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rpq *RoutePointQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryExist)
	switch _, err := rpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rpq *RoutePointQuery) ExistX(ctx context.Context) bool {
	exist, err := rpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoutePointQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rpq *RoutePointQuery) Clone() *RoutePointQuery {
	if rpq == nil {
		return nil
	}
	return &RoutePointQuery{
		config:     rpq.config,
		ctx:        rpq.ctx.Clone(),
		order:      append([]routepoint.OrderOption{}, rpq.order...),
		inters:     append([]Interceptor{}, rpq.inters...),
		predicates: append([]predicate.RoutePoint{}, rpq.predicates...),
		withRoute:  rpq.withRoute.Clone(),
		// clone intermediate query.
		sql:  rpq.sql.Clone(),
		path: rpq.path,
	}
}

// WithRoute tells the query-builder to eager-load the nodes that are connected to
// the "route" edge. The optional arguments are used to configure the query builder of the edge.
func (rpq *RoutePointQuery) WithRoute(opts ...func(*RouteQuery)) *RoutePointQuery {
	query := (&RouteClient{config: rpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rpq.withRoute = query
	return rpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoutePoint.Query().
//		GroupBy(routepoint.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rpq *RoutePointQuery) GroupBy(field string, fields ...string) *RoutePointGroupBy {
	rpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoutePointGroupBy{build: rpq}
	grbuild.flds = &rpq.ctx.Fields
	grbuild.label = routepoint.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RoutePoint.Query().
//		Select(routepoint.FieldCreatedAt).
//		Scan(ctx, &v)
func (rpq *RoutePointQuery) Select(fields ...string) *RoutePointSelect {
	rpq.ctx.Fields = append(rpq.ctx.Fields, fields...)
	sbuild := &RoutePointSelect{RoutePointQuery: rpq}
	sbuild.label = routepoint.Label
	sbuild.flds, sbuild.scan = &rpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoutePointSelect configured with the given aggregations.
func (rpq *RoutePointQuery) Aggregate(fns ...AggregateFunc) *RoutePointSelect {
	return rpq.Select().Aggregate(fns...)
}

func (rpq *RoutePointQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rpq); err != nil {
				return err
			}
		}
	}
	for _, f := range rpq.ctx.Fields {
		if !routepoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rpq.path != nil {
		prev, err := rpq.path(ctx)
		if err != nil {
			return err
		}
		rpq.sql = prev
	}
	return nil
}

func (rpq *RoutePointQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoutePoint, error) {
	var (
		nodes       = []*RoutePoint{}
		_spec       = rpq.querySpec()
		loadedTypes = [1]bool{
			rpq.withRoute != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoutePoint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoutePoint{config: rpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(rpq.modifiers) > 0 {
		_spec.Modifiers = rpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rpq.withRoute; query != nil {
		if err := rpq.loadRoute(ctx, query, nodes, nil,
			func(n *RoutePoint, e *Route) { n.Edges.Route = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rpq *RoutePointQuery) loadRoute(ctx context.Context, query *RouteQuery, nodes []*RoutePoint, init func(*RoutePoint), assign func(*RoutePoint, *Route)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RoutePoint)
	for i := range nodes {
		fk := nodes[i].RouteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(route.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "route_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rpq *RoutePointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rpq.querySpec()
	if len(rpq.modifiers) > 0 {
		_spec.Modifiers = rpq.modifiers
	}
	_spec.Node.Columns = rpq.ctx.Fields
	if len(rpq.ctx.Fields) > 0 {
		_spec.Unique = rpq.ctx.Unique != nil && *rpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rpq.driver, _spec)
}

func (rpq *RoutePointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(routepoint.Table, routepoint.Columns, sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64))
	_spec.From = rpq.sql
	if unique := rpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rpq.path != nil {
		_spec.Unique = true
	}
	if fields := rpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routepoint.FieldID)
		for i := range fields {
			if fields[i] != routepoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rpq.withRoute != nil {
			_spec.Node.AddColumnOnce(routepoint.FieldRouteID)
		}
	}
	if ps := rpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rpq *RoutePointQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rpq.driver.Dialect())
	t1 := builder.Table(routepoint.Table)
	columns := rpq.ctx.Fields
	if len(columns) == 0 {
		columns = routepoint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rpq.sql != nil {
		selector = rpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rpq.ctx.Unique != nil && *rpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range rpq.modifiers {
		m(selector)
	}
	for _, p := range rpq.predicates {
		p(selector)
	}
	for _, p := range rpq.order {
		p(selector)
	}
	if offset := rpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rpq *RoutePointQuery) Modify(modifiers ...func(s *sql.Selector)) *RoutePointSelect {
	rpq.modifiers = append(rpq.modifiers, modifiers...)
	return rpq.Select()
}

// RoutePointGroupBy is the group-by builder for RoutePoint entities.
type RoutePointGroupBy struct {
	selector
	build *RoutePointQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rpgb *RoutePointGroupBy) Aggregate(fns ...AggregateFunc) *RoutePointGroupBy {
	rpgb.fns = append(rpgb.fns, fns...)
	return rpgb
}

// Scan applies the selector query and scans the result into the given value.
func (rpgb *RoutePointGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rpgb.build.ctx, ent.OpQueryGroupBy)
	if err := rpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutePointQuery, *RoutePointGroupBy](ctx, rpgb.build, rpgb, rpgb.build.inters, v)
}

func (rpgb *RoutePointGroupBy) sqlScan(ctx context.Context, root *RoutePointQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rpgb.fns))
	for _, fn := range rpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rpgb.flds)+len(rpgb.fns))
		for _, f := range *rpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoutePointSelect is the builder for selecting fields of RoutePoint entities.
type RoutePointSelect struct {
	*RoutePointQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rps *RoutePointSelect) Aggregate(fns ...AggregateFunc) *RoutePointSelect {
	rps.fns = append(rps.fns, fns...)
	return rps
}

// Scan applies the selector query and scans the result into the given value.
func (rps *RoutePointSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rps.ctx, ent.OpQuerySelect)
	if err := rps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoutePointQuery, *RoutePointSelect](ctx, rps.RoutePointQuery, rps, rps.inters, v)
}

func (rps *RoutePointSelect) sqlScan(ctx context.Context, root *RoutePointQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rps.fns))
	for _, fn := range rps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rps *RoutePointSelect) Modify(modifiers ...func(s *sql.Selector)) *RoutePointSelect {
	rps.modifiers = append(rps.modifiers, modifiers...)
	return rps
}
