// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/enum"
	"github.com/makesalekz/agents/ent/predicate"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
)

// RouteUpdate is the builder for updating Route entities.
type RouteUpdate struct {
	config
	hooks     []Hook
	mutation  *RouteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RouteUpdate builder.
func (ru *RouteUpdate) Where(ps ...predicate.Route) *RouteUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *RouteUpdate) SetUpdatedAt(t time.Time) *RouteUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetAgentID sets the "agent_id" field.
func (ru *RouteUpdate) SetAgentID(i int64) *RouteUpdate {
	ru.mutation.ResetAgentID()
	ru.mutation.SetAgentID(i)
	return ru
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (ru *RouteUpdate) SetNillableAgentID(i *int64) *RouteUpdate {
	if i != nil {
		ru.SetAgentID(*i)
	}
	return ru
}

// AddAgentID adds i to the "agent_id" field.
func (ru *RouteUpdate) AddAgentID(i int64) *RouteUpdate {
	ru.mutation.AddAgentID(i)
	return ru
}

// SetDate sets the "date" field.
func (ru *RouteUpdate) SetDate(t time.Time) *RouteUpdate {
	ru.mutation.SetDate(t)
	return ru
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ru *RouteUpdate) SetNillableDate(t *time.Time) *RouteUpdate {
	if t != nil {
		ru.SetDate(*t)
	}
	return ru
}

// SetStatus sets the "status" field.
func (ru *RouteUpdate) SetStatus(es enum.RouteStatus) *RouteUpdate {
	ru.mutation.SetStatus(es)
	return ru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ru *RouteUpdate) SetNillableStatus(es *enum.RouteStatus) *RouteUpdate {
	if es != nil {
		ru.SetStatus(*es)
	}
	return ru
}

// AddPointIDs adds the "points" edge to the RoutePoint entity by IDs.
func (ru *RouteUpdate) AddPointIDs(ids ...int64) *RouteUpdate {
	ru.mutation.AddPointIDs(ids...)
	return ru
}

// AddPoints adds the "points" edges to the RoutePoint entity.
func (ru *RouteUpdate) AddPoints(r ...*RoutePoint) *RouteUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.AddPointIDs(ids...)
}

// Mutation returns the RouteMutation object of the builder.
func (ru *RouteUpdate) Mutation() *RouteMutation {
	return ru.mutation
}

// ClearPoints clears all "points" edges to the RoutePoint entity.
func (ru *RouteUpdate) ClearPoints() *RouteUpdate {
	ru.mutation.ClearPoints()
	return ru
}

// RemovePointIDs removes the "points" edge to RoutePoint entities by IDs.
func (ru *RouteUpdate) RemovePointIDs(ids ...int64) *RouteUpdate {
	ru.mutation.RemovePointIDs(ids...)
	return ru
}

// RemovePoints removes "points" edges to RoutePoint entities.
func (ru *RouteUpdate) RemovePoints(r ...*RoutePoint) *RouteUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ru.RemovePointIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RouteUpdate) Save(ctx context.Context) (int, error) {
	ru.defaults()
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RouteUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RouteUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RouteUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RouteUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := route.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RouteUpdate) check() error {
	if v, ok := ru.mutation.Status(); ok {
		if err := route.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Route.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ru *RouteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RouteUpdate {
	ru.modifiers = append(ru.modifiers, modifiers...)
	return ru
}

func (ru *RouteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(route.Table, route.Columns, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ru.mutation.AgentID(); ok {
		_spec.SetField(route.FieldAgentID, field.TypeInt64, value)
	}
	if value, ok := ru.mutation.AddedAgentID(); ok {
		_spec.AddField(route.FieldAgentID, field.TypeInt64, value)
	}
	if value, ok := ru.mutation.Date(); ok {
		_spec.SetField(route.FieldDate, field.TypeTime, value)
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeEnum, value)
	}
	if ru.mutation.PointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedPointsIDs(); len(nodes) > 0 && !ru.mutation.PointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.PointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RouteUpdateOne is the builder for updating a single Route entity.
type RouteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RouteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *RouteUpdateOne) SetUpdatedAt(t time.Time) *RouteUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetAgentID sets the "agent_id" field.
func (ruo *RouteUpdateOne) SetAgentID(i int64) *RouteUpdateOne {
	ruo.mutation.ResetAgentID()
	ruo.mutation.SetAgentID(i)
	return ruo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (ruo *RouteUpdateOne) SetNillableAgentID(i *int64) *RouteUpdateOne {
	if i != nil {
		ruo.SetAgentID(*i)
	}
	return ruo
}

// AddAgentID adds i to the "agent_id" field.
func (ruo *RouteUpdateOne) AddAgentID(i int64) *RouteUpdateOne {
	ruo.mutation.AddAgentID(i)
	return ruo
}

// SetDate sets the "date" field.
func (ruo *RouteUpdateOne) SetDate(t time.Time) *RouteUpdateOne {
	ruo.mutation.SetDate(t)
	return ruo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ruo *RouteUpdateOne) SetNillableDate(t *time.Time) *RouteUpdateOne {
	if t != nil {
		ruo.SetDate(*t)
	}
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *RouteUpdateOne) SetStatus(es enum.RouteStatus) *RouteUpdateOne {
	ruo.mutation.SetStatus(es)
	return ruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ruo *RouteUpdateOne) SetNillableStatus(es *enum.RouteStatus) *RouteUpdateOne {
	if es != nil {
		ruo.SetStatus(*es)
	}
	return ruo
}

// AddPointIDs adds the "points" edge to the RoutePoint entity by IDs.
func (ruo *RouteUpdateOne) AddPointIDs(ids ...int64) *RouteUpdateOne {
	ruo.mutation.AddPointIDs(ids...)
	return ruo
}

// AddPoints adds the "points" edges to the RoutePoint entity.
func (ruo *RouteUpdateOne) AddPoints(r ...*RoutePoint) *RouteUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.AddPointIDs(ids...)
}

// Mutation returns the RouteMutation object of the builder.
func (ruo *RouteUpdateOne) Mutation() *RouteMutation {
	return ruo.mutation
}

// ClearPoints clears all "points" edges to the RoutePoint entity.
func (ruo *RouteUpdateOne) ClearPoints() *RouteUpdateOne {
	ruo.mutation.ClearPoints()
	return ruo
}

// RemovePointIDs removes the "points" edge to RoutePoint entities by IDs.
func (ruo *RouteUpdateOne) RemovePointIDs(ids ...int64) *RouteUpdateOne {
	ruo.mutation.RemovePointIDs(ids...)
	return ruo
}

// RemovePoints removes "points" edges to RoutePoint entities.
func (ruo *RouteUpdateOne) RemovePoints(r ...*RoutePoint) *RouteUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return ruo.RemovePointIDs(ids...)
}

// Where appends a list predicates to the RouteUpdate builder.
func (ruo *RouteUpdateOne) Where(ps ...predicate.Route) *RouteUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RouteUpdateOne) Select(field string, fields ...string) *RouteUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Route entity.
func (ruo *RouteUpdateOne) Save(ctx context.Context) (*Route, error) {
	ruo.defaults()
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RouteUpdateOne) SaveX(ctx context.Context) *Route {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RouteUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RouteUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RouteUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := route.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RouteUpdateOne) check() error {
	if v, ok := ruo.mutation.Status(); ok {
		if err := route.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Route.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ruo *RouteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RouteUpdateOne {
	ruo.modifiers = append(ruo.modifiers, modifiers...)
	return ruo
}

func (ruo *RouteUpdateOne) sqlSave(ctx context.Context) (_node *Route, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(route.Table, route.Columns, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Route.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, route.FieldID)
		for _, f := range fields {
			if !route.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != route.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.AgentID(); ok {
		_spec.SetField(route.FieldAgentID, field.TypeInt64, value)
	}
	if value, ok := ruo.mutation.AddedAgentID(); ok {
		_spec.AddField(route.FieldAgentID, field.TypeInt64, value)
	}
	if value, ok := ruo.mutation.Date(); ok {
		_spec.SetField(route.FieldDate, field.TypeTime, value)
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeEnum, value)
	}
	if ruo.mutation.PointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedPointsIDs(); len(nodes) > 0 && !ruo.mutation.PointsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.PointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ruo.modifiers...)
	_node = &Route{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
