// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/predicate"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
)

// RoutePointUpdate is the builder for updating RoutePoint entities.
type RoutePointUpdate struct {
	config
	hooks     []Hook
	mutation  *RoutePointMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RoutePointUpdate builder.
func (rpu *RoutePointUpdate) Where(ps ...predicate.RoutePoint) *RoutePointUpdate {
	rpu.mutation.Where(ps...)
	return rpu
}

// SetUpdatedAt sets the "updated_at" field.
func (rpu *RoutePointUpdate) SetUpdatedAt(t time.Time) *RoutePointUpdate {
	rpu.mutation.SetUpdatedAt(t)
	return rpu
}

// SetRouteID sets the "route_id" field.
func (rpu *RoutePointUpdate) SetRouteID(i int64) *RoutePointUpdate {
	rpu.mutation.SetRouteID(i)
	return rpu
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (rpu *RoutePointUpdate) SetNillableRouteID(i *int64) *RoutePointUpdate {
	if i != nil {
		rpu.SetRouteID(*i)
	}
	return rpu
}

// SetStoreTenantID sets the "store_tenant_id" field.
func (rpu *RoutePointUpdate) SetStoreTenantID(i int64) *RoutePointUpdate {
	rpu.mutation.ResetStoreTenantID()
	rpu.mutation.SetStoreTenantID(i)
	return rpu
}

// SetNillableStoreTenantID sets the "store_tenant_id" field if the given value is not nil.
func (rpu *RoutePointUpdate) SetNillableStoreTenantID(i *int64) *RoutePointUpdate {
	if i != nil {
		rpu.SetStoreTenantID(*i)
	}
	return rpu
}

// AddStoreTenantID adds i to the "store_tenant_id" field.
func (rpu *RoutePointUpdate) AddStoreTenantID(i int64) *RoutePointUpdate {
	rpu.mutation.AddStoreTenantID(i)
	return rpu
}

// SetOrderNum sets the "order_num" field.
func (rpu *RoutePointUpdate) SetOrderNum(i int32) *RoutePointUpdate {
	rpu.mutation.ResetOrderNum()
	rpu.mutation.SetOrderNum(i)
	return rpu
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (rpu *RoutePointUpdate) SetNillableOrderNum(i *int32) *RoutePointUpdate {
	if i != nil {
		rpu.SetOrderNum(*i)
	}
	return rpu
}

// AddOrderNum adds i to the "order_num" field.
func (rpu *RoutePointUpdate) AddOrderNum(i int32) *RoutePointUpdate {
	rpu.mutation.AddOrderNum(i)
	return rpu
}

// SetVisitID sets the "visit_id" field.
func (rpu *RoutePointUpdate) SetVisitID(i int64) *RoutePointUpdate {
	rpu.mutation.ResetVisitID()
	rpu.mutation.SetVisitID(i)
	return rpu
}

// SetNillableVisitID sets the "visit_id" field if the given value is not nil.
func (rpu *RoutePointUpdate) SetNillableVisitID(i *int64) *RoutePointUpdate {
	if i != nil {
		rpu.SetVisitID(*i)
	}
	return rpu
}

// AddVisitID adds i to the "visit_id" field.
func (rpu *RoutePointUpdate) AddVisitID(i int64) *RoutePointUpdate {
	rpu.mutation.AddVisitID(i)
	return rpu
}

// ClearVisitID clears the value of the "visit_id" field.
func (rpu *RoutePointUpdate) ClearVisitID() *RoutePointUpdate {
	rpu.mutation.ClearVisitID()
	return rpu
}

// SetRoute sets the "route" edge to the Route entity.
func (rpu *RoutePointUpdate) SetRoute(r *Route) *RoutePointUpdate {
	return rpu.SetRouteID(r.ID)
}

// Mutation returns the RoutePointMutation object of the builder.
func (rpu *RoutePointUpdate) Mutation() *RoutePointMutation {
	return rpu.mutation
}

// ClearRoute clears the "route" edge to the Route entity.
func (rpu *RoutePointUpdate) ClearRoute() *RoutePointUpdate {
	rpu.mutation.ClearRoute()
	return rpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rpu *RoutePointUpdate) Save(ctx context.Context) (int, error) {
	rpu.defaults()
	return withHooks(ctx, rpu.sqlSave, rpu.mutation, rpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpu *RoutePointUpdate) SaveX(ctx context.Context) int {
	affected, err := rpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rpu *RoutePointUpdate) Exec(ctx context.Context) error {
	_, err := rpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpu *RoutePointUpdate) ExecX(ctx context.Context) {
	if err := rpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rpu *RoutePointUpdate) defaults() {
	if _, ok := rpu.mutation.UpdatedAt(); !ok {
		v := routepoint.UpdateDefaultUpdatedAt()
		rpu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpu *RoutePointUpdate) check() error {
	if rpu.mutation.RouteCleared() && len(rpu.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoutePoint.route"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (rpu *RoutePointUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoutePointUpdate {
	rpu.modifiers = append(rpu.modifiers, modifiers...)
	return rpu
}

func (rpu *RoutePointUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(routepoint.Table, routepoint.Columns, sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64))
	if ps := rpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rpu.mutation.UpdatedAt(); ok {
		_spec.SetField(routepoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := rpu.mutation.StoreTenantID(); ok {
		_spec.SetField(routepoint.FieldStoreTenantID, field.TypeInt64, value)
	}
	if value, ok := rpu.mutation.AddedStoreTenantID(); ok {
		_spec.AddField(routepoint.FieldStoreTenantID, field.TypeInt64, value)
	}
	if value, ok := rpu.mutation.OrderNum(); ok {
		_spec.SetField(routepoint.FieldOrderNum, field.TypeInt32, value)
	}
	if value, ok := rpu.mutation.AddedOrderNum(); ok {
		_spec.AddField(routepoint.FieldOrderNum, field.TypeInt32, value)
	}
	if value, ok := rpu.mutation.VisitID(); ok {
		_spec.SetField(routepoint.FieldVisitID, field.TypeInt64, value)
	}
	if value, ok := rpu.mutation.AddedVisitID(); ok {
		_spec.AddField(routepoint.FieldVisitID, field.TypeInt64, value)
	}
	if rpu.mutation.VisitIDCleared() {
		_spec.ClearField(routepoint.FieldVisitID, field.TypeInt64)
	}
	if rpu.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routepoint.RouteTable,
			Columns: []string{routepoint.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routepoint.RouteTable,
			Columns: []string{routepoint.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(rpu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, rpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routepoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rpu.mutation.done = true
	return n, nil
}

// RoutePointUpdateOne is the builder for updating a single RoutePoint entity.
type RoutePointUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RoutePointMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (rpuo *RoutePointUpdateOne) SetUpdatedAt(t time.Time) *RoutePointUpdateOne {
	rpuo.mutation.SetUpdatedAt(t)
	return rpuo
}

// SetRouteID sets the "route_id" field.
func (rpuo *RoutePointUpdateOne) SetRouteID(i int64) *RoutePointUpdateOne {
	rpuo.mutation.SetRouteID(i)
	return rpuo
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (rpuo *RoutePointUpdateOne) SetNillableRouteID(i *int64) *RoutePointUpdateOne {
	if i != nil {
		rpuo.SetRouteID(*i)
	}
	return rpuo
}

// SetStoreTenantID sets the "store_tenant_id" field.
func (rpuo *RoutePointUpdateOne) SetStoreTenantID(i int64) *RoutePointUpdateOne {
	rpuo.mutation.ResetStoreTenantID()
	rpuo.mutation.SetStoreTenantID(i)
	return rpuo
}

// SetNillableStoreTenantID sets the "store_tenant_id" field if the given value is not nil.
func (rpuo *RoutePointUpdateOne) SetNillableStoreTenantID(i *int64) *RoutePointUpdateOne {
	if i != nil {
		rpuo.SetStoreTenantID(*i)
	}
	return rpuo
}

// AddStoreTenantID adds i to the "store_tenant_id" field.
func (rpuo *RoutePointUpdateOne) AddStoreTenantID(i int64) *RoutePointUpdateOne {
	rpuo.mutation.AddStoreTenantID(i)
	return rpuo
}

// SetOrderNum sets the "order_num" field.
func (rpuo *RoutePointUpdateOne) SetOrderNum(i int32) *RoutePointUpdateOne {
	rpuo.mutation.ResetOrderNum()
	rpuo.mutation.SetOrderNum(i)
	return rpuo
}

// SetNillableOrderNum sets the "order_num" field if the given value is not nil.
func (rpuo *RoutePointUpdateOne) SetNillableOrderNum(i *int32) *RoutePointUpdateOne {
	if i != nil {
		rpuo.SetOrderNum(*i)
	}
	return rpuo
}

// AddOrderNum adds i to the "order_num" field.
func (rpuo *RoutePointUpdateOne) AddOrderNum(i int32) *RoutePointUpdateOne {
	rpuo.mutation.AddOrderNum(i)
	return rpuo
}

// SetVisitID sets the "visit_id" field.
func (rpuo *RoutePointUpdateOne) SetVisitID(i int64) *RoutePointUpdateOne {
	rpuo.mutation.ResetVisitID()
	rpuo.mutation.SetVisitID(i)
	return rpuo
}

// SetNillableVisitID sets the "visit_id" field if the given value is not nil.
func (rpuo *RoutePointUpdateOne) SetNillableVisitID(i *int64) *RoutePointUpdateOne {
	if i != nil {
		rpuo.SetVisitID(*i)
	}
	return rpuo
}

// AddVisitID adds i to the "visit_id" field.
func (rpuo *RoutePointUpdateOne) AddVisitID(i int64) *RoutePointUpdateOne {
	rpuo.mutation.AddVisitID(i)
	return rpuo
}

// ClearVisitID clears the value of the "visit_id" field.
func (rpuo *RoutePointUpdateOne) ClearVisitID() *RoutePointUpdateOne {
	rpuo.mutation.ClearVisitID()
	return rpuo
}

// SetRoute sets the "route" edge to the Route entity.
func (rpuo *RoutePointUpdateOne) SetRoute(r *Route) *RoutePointUpdateOne {
	return rpuo.SetRouteID(r.ID)
}

// Mutation returns the RoutePointMutation object of the builder.
func (rpuo *RoutePointUpdateOne) Mutation() *RoutePointMutation {
	return rpuo.mutation
}

// ClearRoute clears the "route" edge to the Route entity.
func (rpuo *RoutePointUpdateOne) ClearRoute() *RoutePointUpdateOne {
	rpuo.mutation.ClearRoute()
	return rpuo
}

// Where appends a list predicates to the RoutePointUpdate builder.
func (rpuo *RoutePointUpdateOne) Where(ps ...predicate.RoutePoint) *RoutePointUpdateOne {
	rpuo.mutation.Where(ps...)
	return rpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rpuo *RoutePointUpdateOne) Select(field string, fields ...string) *RoutePointUpdateOne {
	rpuo.fields = append([]string{field}, fields...)
	return rpuo
}

// Save executes the query and returns the updated RoutePoint entity.
func (rpuo *RoutePointUpdateOne) Save(ctx context.Context) (*RoutePoint, error) {
	rpuo.defaults()
	return withHooks(ctx, rpuo.sqlSave, rpuo.mutation, rpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpuo *RoutePointUpdateOne) SaveX(ctx context.Context) *RoutePoint {
	node, err := rpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rpuo *RoutePointUpdateOne) Exec(ctx context.Context) error {
	_, err := rpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpuo *RoutePointUpdateOne) ExecX(ctx context.Context) {
	if err := rpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rpuo *RoutePointUpdateOne) defaults() {
	if _, ok := rpuo.mutation.UpdatedAt(); !ok {
		v := routepoint.UpdateDefaultUpdatedAt()
		rpuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpuo *RoutePointUpdateOne) check() error {
	if rpuo.mutation.RouteCleared() && len(rpuo.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoutePoint.route"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (rpuo *RoutePointUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RoutePointUpdateOne {
	rpuo.modifiers = append(rpuo.modifiers, modifiers...)
	return rpuo
}

func (rpuo *RoutePointUpdateOne) sqlSave(ctx context.Context) (_node *RoutePoint, err error) {
	if err := rpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(routepoint.Table, routepoint.Columns, sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64))
	id, ok := rpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoutePoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routepoint.FieldID)
		for _, f := range fields {
			if !routepoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != routepoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rpuo.mutation.UpdatedAt(); ok {
		_spec.SetField(routepoint.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := rpuo.mutation.StoreTenantID(); ok {
		_spec.SetField(routepoint.FieldStoreTenantID, field.TypeInt64, value)
	}
	if value, ok := rpuo.mutation.AddedStoreTenantID(); ok {
		_spec.AddField(routepoint.FieldStoreTenantID, field.TypeInt64, value)
	}
	if value, ok := rpuo.mutation.OrderNum(); ok {
		_spec.SetField(routepoint.FieldOrderNum, field.TypeInt32, value)
	}
	if value, ok := rpuo.mutation.AddedOrderNum(); ok {
		_spec.AddField(routepoint.FieldOrderNum, field.TypeInt32, value)
	}
	if value, ok := rpuo.mutation.VisitID(); ok {
		_spec.SetField(routepoint.FieldVisitID, field.TypeInt64, value)
	}
	if value, ok := rpuo.mutation.AddedVisitID(); ok {
		_spec.AddField(routepoint.FieldVisitID, field.TypeInt64, value)
	}
	if rpuo.mutation.VisitIDCleared() {
		_spec.ClearField(routepoint.FieldVisitID, field.TypeInt64)
	}
	if rpuo.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routepoint.RouteTable,
			Columns: []string{routepoint.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   routepoint.RouteTable,
			Columns: []string{routepoint.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(rpuo.modifiers...)
	_node = &RoutePoint{config: rpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routepoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rpuo.mutation.done = true
	return _node, nil
}
