// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/enum"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
)

// RouteCreate is the builder for creating a Route entity.
type RouteCreate struct {
	config
	mutation *RouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (rc *RouteCreate) SetCreatedAt(t time.Time) *RouteCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RouteCreate) SetNillableCreatedAt(t *time.Time) *RouteCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RouteCreate) SetUpdatedAt(t time.Time) *RouteCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RouteCreate) SetNillableUpdatedAt(t *time.Time) *RouteCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetTenantID sets the "tenant_id" field.
func (rc *RouteCreate) SetTenantID(i int64) *RouteCreate {
	rc.mutation.SetTenantID(i)
	return rc
}

// SetAgentID sets the "agent_id" field.
func (rc *RouteCreate) SetAgentID(i int64) *RouteCreate {
	rc.mutation.SetAgentID(i)
	return rc
}

// SetDate sets the "date" field.
func (rc *RouteCreate) SetDate(t time.Time) *RouteCreate {
	rc.mutation.SetDate(t)
	return rc
}

// SetStatus sets the "status" field.
func (rc *RouteCreate) SetStatus(es enum.RouteStatus) *RouteCreate {
	rc.mutation.SetStatus(es)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *RouteCreate) SetNillableStatus(es *enum.RouteStatus) *RouteCreate {
	if es != nil {
		rc.SetStatus(*es)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *RouteCreate) SetID(i int64) *RouteCreate {
	rc.mutation.SetID(i)
	return rc
}

// AddPointIDs adds the "points" edge to the RoutePoint entity by IDs.
func (rc *RouteCreate) AddPointIDs(ids ...int64) *RouteCreate {
	rc.mutation.AddPointIDs(ids...)
	return rc
}

// AddPoints adds the "points" edges to the RoutePoint entity.
func (rc *RouteCreate) AddPoints(r ...*RoutePoint) *RouteCreate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rc.AddPointIDs(ids...)
}

// Mutation returns the RouteMutation object of the builder.
func (rc *RouteCreate) Mutation() *RouteMutation {
	return rc.mutation
}

// Save creates the Route in the database.
func (rc *RouteCreate) Save(ctx context.Context) (*Route, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RouteCreate) SaveX(ctx context.Context) *Route {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RouteCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RouteCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RouteCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := route.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := route.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.Status(); !ok {
		v := route.DefaultStatus
		rc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RouteCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Route.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Route.updated_at"`)}
	}
	if _, ok := rc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Route.tenant_id"`)}
	}
	if _, ok := rc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Route.agent_id"`)}
	}
	if _, ok := rc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Route.date"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Route.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := route.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Route.status": %w`, err)}
		}
	}
	return nil
}

func (rc *RouteCreate) sqlSave(ctx context.Context) (*Route, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RouteCreate) createSpec() (*Route, *sqlgraph.CreateSpec) {
	var (
		_node = &Route{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(route.Table, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = rc.conflict
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(route.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.TenantID(); ok {
		_spec.SetField(route.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := rc.mutation.AgentID(); ok {
		_spec.SetField(route.FieldAgentID, field.TypeInt64, value)
		_node.AgentID = value
	}
	if value, ok := rc.mutation.Date(); ok {
		_spec.SetField(route.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := rc.mutation.PointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   route.PointsTable,
			Columns: []string{route.PointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(routepoint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Route.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rc *RouteCreate) OnConflict(opts ...sql.ConflictOption) *RouteUpsertOne {
	rc.conflict = opts
	return &RouteUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rc *RouteCreate) OnConflictColumns(columns ...string) *RouteUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RouteUpsertOne{
		create: rc,
	}
}

type (
	// RouteUpsertOne is the builder for "upsert"-ing
	//  one Route node.
	RouteUpsertOne struct {
		create *RouteCreate
	}

	// RouteUpsert is the "OnConflict" setter.
	RouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RouteUpsert) SetUpdatedAt(v time.Time) *RouteUpsert {
	u.Set(route.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RouteUpsert) UpdateUpdatedAt() *RouteUpsert {
	u.SetExcluded(route.FieldUpdatedAt)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *RouteUpsert) SetAgentID(v int64) *RouteUpsert {
	u.Set(route.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *RouteUpsert) UpdateAgentID() *RouteUpsert {
	u.SetExcluded(route.FieldAgentID)
	return u
}

// AddAgentID adds v to the "agent_id" field.
func (u *RouteUpsert) AddAgentID(v int64) *RouteUpsert {
	u.Add(route.FieldAgentID, v)
	return u
}

// SetDate sets the "date" field.
func (u *RouteUpsert) SetDate(v time.Time) *RouteUpsert {
	u.Set(route.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RouteUpsert) UpdateDate() *RouteUpsert {
	u.SetExcluded(route.FieldDate)
	return u
}

// SetStatus sets the "status" field.
func (u *RouteUpsert) SetStatus(v enum.RouteStatus) *RouteUpsert {
	u.Set(route.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RouteUpsert) UpdateStatus() *RouteUpsert {
	u.SetExcluded(route.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(route.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RouteUpsertOne) UpdateNewValues() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(route.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(route.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(route.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Route.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RouteUpsertOne) Ignore() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RouteUpsertOne) DoNothing() *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RouteCreate.OnConflict
// documentation for more info.
func (u *RouteUpsertOne) Update(set func(*RouteUpsert)) *RouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RouteUpsertOne) SetUpdatedAt(v time.Time) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateUpdatedAt() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *RouteUpsertOne) SetAgentID(v int64) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *RouteUpsertOne) AddAgentID(v int64) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateAgentID() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateAgentID()
	})
}

// SetDate sets the "date" field.
func (u *RouteUpsertOne) SetDate(v time.Time) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateDate() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateDate()
	})
}

// SetStatus sets the "status" field.
func (u *RouteUpsertOne) SetStatus(v enum.RouteStatus) *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RouteUpsertOne) UpdateStatus() *RouteUpsertOne {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *RouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RouteCreateBulk is the builder for creating many Route entities in bulk.
type RouteCreateBulk struct {
	config
	err      error
	builders []*RouteCreate
	conflict []sql.ConflictOption
}

// Save creates the Route entities in the database.
func (rcb *RouteCreateBulk) Save(ctx context.Context) ([]*Route, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Route, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RouteCreateBulk) SaveX(ctx context.Context) []*Route {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RouteCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RouteCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Route.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rcb *RouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *RouteUpsertBulk {
	rcb.conflict = opts
	return &RouteUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rcb *RouteCreateBulk) OnConflictColumns(columns ...string) *RouteUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RouteUpsertBulk{
		create: rcb,
	}
}

// RouteUpsertBulk is the builder for "upsert"-ing
// a bulk of Route nodes.
type RouteUpsertBulk struct {
	create *RouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(route.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RouteUpsertBulk) UpdateNewValues() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(route.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(route.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(route.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Route.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RouteUpsertBulk) Ignore() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RouteUpsertBulk) DoNothing() *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RouteCreateBulk.OnConflict
// documentation for more info.
func (u *RouteUpsertBulk) Update(set func(*RouteUpsert)) *RouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RouteUpsertBulk) SetUpdatedAt(v time.Time) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateUpdatedAt() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *RouteUpsertBulk) SetAgentID(v int64) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *RouteUpsertBulk) AddAgentID(v int64) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateAgentID() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateAgentID()
	})
}

// SetDate sets the "date" field.
func (u *RouteUpsertBulk) SetDate(v time.Time) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateDate() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateDate()
	})
}

// SetStatus sets the "status" field.
func (u *RouteUpsertBulk) SetStatus(v enum.RouteStatus) *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RouteUpsertBulk) UpdateStatus() *RouteUpsertBulk {
	return u.Update(func(s *RouteUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *RouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
