// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/agents/ent/route"
	"gitlab.calendaria.team/services/agents/ent/routepoint"
)

// RoutePoint is the model entity for the RoutePoint schema.
type RoutePoint struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID int64 `json:"route_id,omitempty"`
	// StoreTenantID holds the value of the "store_tenant_id" field.
	StoreTenantID int64 `json:"store_tenant_id,omitempty"`
	// OrderNum holds the value of the "order_num" field.
	OrderNum int32 `json:"order_num,omitempty"`
	// VisitID holds the value of the "visit_id" field.
	VisitID int64 `json:"visit_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoutePointQuery when eager-loading is set.
	Edges        RoutePointEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoutePointEdges holds the relations/edges for other nodes in the graph.
type RoutePointEdges struct {
	// Route holds the value of the route edge.
	Route *Route `json:"route,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RouteOrErr returns the Route value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoutePointEdges) RouteOrErr() (*Route, error) {
	if e.Route != nil {
		return e.Route, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: route.Label}
	}
	return nil, &NotLoadedError{edge: "route"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoutePoint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case routepoint.FieldID, routepoint.FieldRouteID, routepoint.FieldStoreTenantID, routepoint.FieldOrderNum, routepoint.FieldVisitID:
			values[i] = new(sql.NullInt64)
		case routepoint.FieldCreatedAt, routepoint.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoutePoint fields.
func (rp *RoutePoint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case routepoint.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rp.ID = int64(value.Int64)
		case routepoint.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rp.CreatedAt = value.Time
			}
		case routepoint.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rp.UpdatedAt = value.Time
			}
		case routepoint.FieldRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				rp.RouteID = value.Int64
			}
		case routepoint.FieldStoreTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field store_tenant_id", values[i])
			} else if value.Valid {
				rp.StoreTenantID = value.Int64
			}
		case routepoint.FieldOrderNum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_num", values[i])
			} else if value.Valid {
				rp.OrderNum = int32(value.Int64)
			}
		case routepoint.FieldVisitID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field visit_id", values[i])
			} else if value.Valid {
				rp.VisitID = value.Int64
			}
		default:
			rp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoutePoint.
// This includes values selected through modifiers, order, etc.
func (rp *RoutePoint) Value(name string) (ent.Value, error) {
	return rp.selectValues.Get(name)
}

// QueryRoute queries the "route" edge of the RoutePoint entity.
func (rp *RoutePoint) QueryRoute() *RouteQuery {
	return NewRoutePointClient(rp.config).QueryRoute(rp)
}

// Update returns a builder for updating this RoutePoint.
// Note that you need to call RoutePoint.Unwrap() before calling this method if this RoutePoint
// was returned from a transaction, and the transaction was committed or rolled back.
func (rp *RoutePoint) Update() *RoutePointUpdateOne {
	return NewRoutePointClient(rp.config).UpdateOne(rp)
}

// Unwrap unwraps the RoutePoint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rp *RoutePoint) Unwrap() *RoutePoint {
	_tx, ok := rp.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoutePoint is not a transactional entity")
	}
	rp.config.driver = _tx.drv
	return rp
}

// String implements the fmt.Stringer.
func (rp *RoutePoint) String() string {
	var builder strings.Builder
	builder.WriteString("RoutePoint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rp.ID))
	builder.WriteString("created_at=")
	builder.WriteString(rp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rp.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("route_id=")
	builder.WriteString(fmt.Sprintf("%v", rp.RouteID))
	builder.WriteString(", ")
	builder.WriteString("store_tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", rp.StoreTenantID))
	builder.WriteString(", ")
	builder.WriteString("order_num=")
	builder.WriteString(fmt.Sprintf("%v", rp.OrderNum))
	builder.WriteString(", ")
	builder.WriteString("visit_id=")
	builder.WriteString(fmt.Sprintf("%v", rp.VisitID))
	builder.WriteByte(')')
	return builder.String()
}

// RoutePoints is a parsable slice of RoutePoint.
type RoutePoints []*RoutePoint
