// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/makesalekz/agents/ent/onboarding"
	"github.com/makesalekz/agents/ent/route"
	"github.com/makesalekz/agents/ent/routepoint"
	"github.com/makesalekz/agents/ent/schema"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	onboardingMixin := schema.Onboarding{}.Mixin()
	onboardingMixinFields0 := onboardingMixin[0].Fields()
	_ = onboardingMixinFields0
	onboardingFields := schema.Onboarding{}.Fields()
	_ = onboardingFields
	// onboardingDescCreatedAt is the schema descriptor for created_at field.
	onboardingDescCreatedAt := onboardingMixinFields0[0].Descriptor()
	// onboarding.DefaultCreatedAt holds the default value on creation for the created_at field.
	onboarding.DefaultCreatedAt = onboardingDescCreatedAt.Default.(func() time.Time)
	// onboardingDescUpdatedAt is the schema descriptor for updated_at field.
	onboardingDescUpdatedAt := onboardingMixinFields0[1].Descriptor()
	// onboarding.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	onboarding.DefaultUpdatedAt = onboardingDescUpdatedAt.Default.(func() time.Time)
	// onboarding.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	onboarding.UpdateDefaultUpdatedAt = onboardingDescUpdatedAt.UpdateDefault.(func() time.Time)
	routeMixin := schema.Route{}.Mixin()
	routeMixinFields0 := routeMixin[0].Fields()
	_ = routeMixinFields0
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescCreatedAt is the schema descriptor for created_at field.
	routeDescCreatedAt := routeMixinFields0[0].Descriptor()
	// route.DefaultCreatedAt holds the default value on creation for the created_at field.
	route.DefaultCreatedAt = routeDescCreatedAt.Default.(func() time.Time)
	// routeDescUpdatedAt is the schema descriptor for updated_at field.
	routeDescUpdatedAt := routeMixinFields0[1].Descriptor()
	// route.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	route.DefaultUpdatedAt = routeDescUpdatedAt.Default.(func() time.Time)
	// route.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	route.UpdateDefaultUpdatedAt = routeDescUpdatedAt.UpdateDefault.(func() time.Time)
	routepointMixin := schema.RoutePoint{}.Mixin()
	routepointMixinFields0 := routepointMixin[0].Fields()
	_ = routepointMixinFields0
	routepointFields := schema.RoutePoint{}.Fields()
	_ = routepointFields
	// routepointDescCreatedAt is the schema descriptor for created_at field.
	routepointDescCreatedAt := routepointMixinFields0[0].Descriptor()
	// routepoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	routepoint.DefaultCreatedAt = routepointDescCreatedAt.Default.(func() time.Time)
	// routepointDescUpdatedAt is the schema descriptor for updated_at field.
	routepointDescUpdatedAt := routepointMixinFields0[1].Descriptor()
	// routepoint.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	routepoint.DefaultUpdatedAt = routepointDescUpdatedAt.Default.(func() time.Time)
	// routepoint.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	routepoint.UpdateDefaultUpdatedAt = routepointDescUpdatedAt.UpdateDefault.(func() time.Time)
	// routepointDescVisitID is the schema descriptor for visit_id field.
	routepointDescVisitID := routepointFields[4].Descriptor()
	// routepoint.DefaultVisitID holds the default value on creation for the visit_id field.
	routepoint.DefaultVisitID = routepointDescVisitID.Default.(int64)
	visitMixin := schema.Visit{}.Mixin()
	visitMixinFields0 := visitMixin[0].Fields()
	_ = visitMixinFields0
	visitFields := schema.Visit{}.Fields()
	_ = visitFields
	// visitDescCreatedAt is the schema descriptor for created_at field.
	visitDescCreatedAt := visitMixinFields0[0].Descriptor()
	// visit.DefaultCreatedAt holds the default value on creation for the created_at field.
	visit.DefaultCreatedAt = visitDescCreatedAt.Default.(func() time.Time)
	// visitDescUpdatedAt is the schema descriptor for updated_at field.
	visitDescUpdatedAt := visitMixinFields0[1].Descriptor()
	// visit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	visit.DefaultUpdatedAt = visitDescUpdatedAt.Default.(func() time.Time)
	// visit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	visit.UpdateDefaultUpdatedAt = visitDescUpdatedAt.UpdateDefault.(func() time.Time)
	// visitDescDurationSeconds is the schema descriptor for duration_seconds field.
	visitDescDurationSeconds := visitFields[10].Descriptor()
	// visit.DefaultDurationSeconds holds the default value on creation for the duration_seconds field.
	visit.DefaultDurationSeconds = visitDescDurationSeconds.Default.(int64)
	visitphotoMixin := schema.VisitPhoto{}.Mixin()
	visitphotoMixinFields0 := visitphotoMixin[0].Fields()
	_ = visitphotoMixinFields0
	visitphotoFields := schema.VisitPhoto{}.Fields()
	_ = visitphotoFields
	// visitphotoDescCreatedAt is the schema descriptor for created_at field.
	visitphotoDescCreatedAt := visitphotoMixinFields0[0].Descriptor()
	// visitphoto.DefaultCreatedAt holds the default value on creation for the created_at field.
	visitphoto.DefaultCreatedAt = visitphotoDescCreatedAt.Default.(func() time.Time)
	// visitphotoDescUpdatedAt is the schema descriptor for updated_at field.
	visitphotoDescUpdatedAt := visitphotoMixinFields0[1].Descriptor()
	// visitphoto.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	visitphoto.DefaultUpdatedAt = visitphotoDescUpdatedAt.Default.(func() time.Time)
	// visitphoto.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	visitphoto.UpdateDefaultUpdatedAt = visitphotoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// visitphotoDescMediaURL is the schema descriptor for media_url field.
	visitphotoDescMediaURL := visitphotoFields[2].Descriptor()
	// visitphoto.MediaURLValidator is a validator for the "media_url" field. It is called by the builders before save.
	visitphoto.MediaURLValidator = visitphotoDescMediaURL.Validators[0].(func(string) error)
}
