// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/agents/ent/predicate"
	"gitlab.calendaria.team/services/agents/ent/visit"
	"gitlab.calendaria.team/services/agents/ent/visitphoto"
)

// VisitPhotoUpdate is the builder for updating VisitPhoto entities.
type VisitPhotoUpdate struct {
	config
	hooks     []Hook
	mutation  *VisitPhotoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the VisitPhotoUpdate builder.
func (vpu *VisitPhotoUpdate) Where(ps ...predicate.VisitPhoto) *VisitPhotoUpdate {
	vpu.mutation.Where(ps...)
	return vpu
}

// SetUpdatedAt sets the "updated_at" field.
func (vpu *VisitPhotoUpdate) SetUpdatedAt(t time.Time) *VisitPhotoUpdate {
	vpu.mutation.SetUpdatedAt(t)
	return vpu
}

// SetVisitID sets the "visit_id" field.
func (vpu *VisitPhotoUpdate) SetVisitID(i int64) *VisitPhotoUpdate {
	vpu.mutation.SetVisitID(i)
	return vpu
}

// SetNillableVisitID sets the "visit_id" field if the given value is not nil.
func (vpu *VisitPhotoUpdate) SetNillableVisitID(i *int64) *VisitPhotoUpdate {
	if i != nil {
		vpu.SetVisitID(*i)
	}
	return vpu
}

// SetMediaURL sets the "media_url" field.
func (vpu *VisitPhotoUpdate) SetMediaURL(s string) *VisitPhotoUpdate {
	vpu.mutation.SetMediaURL(s)
	return vpu
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (vpu *VisitPhotoUpdate) SetNillableMediaURL(s *string) *VisitPhotoUpdate {
	if s != nil {
		vpu.SetMediaURL(*s)
	}
	return vpu
}

// SetVisit sets the "visit" edge to the Visit entity.
func (vpu *VisitPhotoUpdate) SetVisit(v *Visit) *VisitPhotoUpdate {
	return vpu.SetVisitID(v.ID)
}

// Mutation returns the VisitPhotoMutation object of the builder.
func (vpu *VisitPhotoUpdate) Mutation() *VisitPhotoMutation {
	return vpu.mutation
}

// ClearVisit clears the "visit" edge to the Visit entity.
func (vpu *VisitPhotoUpdate) ClearVisit() *VisitPhotoUpdate {
	vpu.mutation.ClearVisit()
	return vpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vpu *VisitPhotoUpdate) Save(ctx context.Context) (int, error) {
	vpu.defaults()
	return withHooks(ctx, vpu.sqlSave, vpu.mutation, vpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vpu *VisitPhotoUpdate) SaveX(ctx context.Context) int {
	affected, err := vpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vpu *VisitPhotoUpdate) Exec(ctx context.Context) error {
	_, err := vpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vpu *VisitPhotoUpdate) ExecX(ctx context.Context) {
	if err := vpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vpu *VisitPhotoUpdate) defaults() {
	if _, ok := vpu.mutation.UpdatedAt(); !ok {
		v := visitphoto.UpdateDefaultUpdatedAt()
		vpu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vpu *VisitPhotoUpdate) check() error {
	if v, ok := vpu.mutation.MediaURL(); ok {
		if err := visitphoto.MediaURLValidator(v); err != nil {
			return &ValidationError{Name: "media_url", err: fmt.Errorf(`ent: validator failed for field "VisitPhoto.media_url": %w`, err)}
		}
	}
	if vpu.mutation.VisitCleared() && len(vpu.mutation.VisitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VisitPhoto.visit"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (vpu *VisitPhotoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VisitPhotoUpdate {
	vpu.modifiers = append(vpu.modifiers, modifiers...)
	return vpu
}

func (vpu *VisitPhotoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := vpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(visitphoto.Table, visitphoto.Columns, sqlgraph.NewFieldSpec(visitphoto.FieldID, field.TypeInt64))
	if ps := vpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vpu.mutation.UpdatedAt(); ok {
		_spec.SetField(visitphoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vpu.mutation.MediaURL(); ok {
		_spec.SetField(visitphoto.FieldMediaURL, field.TypeString, value)
	}
	if vpu.mutation.VisitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visitphoto.VisitTable,
			Columns: []string{visitphoto.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vpu.mutation.VisitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visitphoto.VisitTable,
			Columns: []string{visitphoto.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(vpu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, vpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visitphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vpu.mutation.done = true
	return n, nil
}

// VisitPhotoUpdateOne is the builder for updating a single VisitPhoto entity.
type VisitPhotoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *VisitPhotoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (vpuo *VisitPhotoUpdateOne) SetUpdatedAt(t time.Time) *VisitPhotoUpdateOne {
	vpuo.mutation.SetUpdatedAt(t)
	return vpuo
}

// SetVisitID sets the "visit_id" field.
func (vpuo *VisitPhotoUpdateOne) SetVisitID(i int64) *VisitPhotoUpdateOne {
	vpuo.mutation.SetVisitID(i)
	return vpuo
}

// SetNillableVisitID sets the "visit_id" field if the given value is not nil.
func (vpuo *VisitPhotoUpdateOne) SetNillableVisitID(i *int64) *VisitPhotoUpdateOne {
	if i != nil {
		vpuo.SetVisitID(*i)
	}
	return vpuo
}

// SetMediaURL sets the "media_url" field.
func (vpuo *VisitPhotoUpdateOne) SetMediaURL(s string) *VisitPhotoUpdateOne {
	vpuo.mutation.SetMediaURL(s)
	return vpuo
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (vpuo *VisitPhotoUpdateOne) SetNillableMediaURL(s *string) *VisitPhotoUpdateOne {
	if s != nil {
		vpuo.SetMediaURL(*s)
	}
	return vpuo
}

// SetVisit sets the "visit" edge to the Visit entity.
func (vpuo *VisitPhotoUpdateOne) SetVisit(v *Visit) *VisitPhotoUpdateOne {
	return vpuo.SetVisitID(v.ID)
}

// Mutation returns the VisitPhotoMutation object of the builder.
func (vpuo *VisitPhotoUpdateOne) Mutation() *VisitPhotoMutation {
	return vpuo.mutation
}

// ClearVisit clears the "visit" edge to the Visit entity.
func (vpuo *VisitPhotoUpdateOne) ClearVisit() *VisitPhotoUpdateOne {
	vpuo.mutation.ClearVisit()
	return vpuo
}

// Where appends a list predicates to the VisitPhotoUpdate builder.
func (vpuo *VisitPhotoUpdateOne) Where(ps ...predicate.VisitPhoto) *VisitPhotoUpdateOne {
	vpuo.mutation.Where(ps...)
	return vpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vpuo *VisitPhotoUpdateOne) Select(field string, fields ...string) *VisitPhotoUpdateOne {
	vpuo.fields = append([]string{field}, fields...)
	return vpuo
}

// Save executes the query and returns the updated VisitPhoto entity.
func (vpuo *VisitPhotoUpdateOne) Save(ctx context.Context) (*VisitPhoto, error) {
	vpuo.defaults()
	return withHooks(ctx, vpuo.sqlSave, vpuo.mutation, vpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vpuo *VisitPhotoUpdateOne) SaveX(ctx context.Context) *VisitPhoto {
	node, err := vpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vpuo *VisitPhotoUpdateOne) Exec(ctx context.Context) error {
	_, err := vpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vpuo *VisitPhotoUpdateOne) ExecX(ctx context.Context) {
	if err := vpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vpuo *VisitPhotoUpdateOne) defaults() {
	if _, ok := vpuo.mutation.UpdatedAt(); !ok {
		v := visitphoto.UpdateDefaultUpdatedAt()
		vpuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vpuo *VisitPhotoUpdateOne) check() error {
	if v, ok := vpuo.mutation.MediaURL(); ok {
		if err := visitphoto.MediaURLValidator(v); err != nil {
			return &ValidationError{Name: "media_url", err: fmt.Errorf(`ent: validator failed for field "VisitPhoto.media_url": %w`, err)}
		}
	}
	if vpuo.mutation.VisitCleared() && len(vpuo.mutation.VisitIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VisitPhoto.visit"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (vpuo *VisitPhotoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VisitPhotoUpdateOne {
	vpuo.modifiers = append(vpuo.modifiers, modifiers...)
	return vpuo
}

func (vpuo *VisitPhotoUpdateOne) sqlSave(ctx context.Context) (_node *VisitPhoto, err error) {
	if err := vpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(visitphoto.Table, visitphoto.Columns, sqlgraph.NewFieldSpec(visitphoto.FieldID, field.TypeInt64))
	id, ok := vpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VisitPhoto.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visitphoto.FieldID)
		for _, f := range fields {
			if !visitphoto.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != visitphoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vpuo.mutation.UpdatedAt(); ok {
		_spec.SetField(visitphoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vpuo.mutation.MediaURL(); ok {
		_spec.SetField(visitphoto.FieldMediaURL, field.TypeString, value)
	}
	if vpuo.mutation.VisitCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visitphoto.VisitTable,
			Columns: []string{visitphoto.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vpuo.mutation.VisitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visitphoto.VisitTable,
			Columns: []string{visitphoto.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(vpuo.modifiers...)
	_node = &VisitPhoto{config: vpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visitphoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vpuo.mutation.done = true
	return _node, nil
}
