// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/predicate"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// VisitQuery is the builder for querying Visit entities.
type VisitQuery struct {
	config
	ctx        *QueryContext
	order      []visit.OrderOption
	inters     []Interceptor
	predicates []predicate.Visit
	withPhotos *VisitPhotoQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VisitQuery builder.
func (vq *VisitQuery) Where(ps ...predicate.Visit) *VisitQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *VisitQuery) Limit(limit int) *VisitQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *VisitQuery) Offset(offset int) *VisitQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *VisitQuery) Unique(unique bool) *VisitQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *VisitQuery) Order(o ...visit.OrderOption) *VisitQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// QueryPhotos chains the current query on the "photos" edge.
func (vq *VisitQuery) QueryPhotos() *VisitPhotoQuery {
	query := (&VisitPhotoClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(visit.Table, visit.FieldID, selector),
			sqlgraph.To(visitphoto.Table, visitphoto.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, visit.PhotosTable, visit.PhotosColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Visit entity from the query.
// Returns a *NotFoundError when no Visit was found.
func (vq *VisitQuery) First(ctx context.Context) (*Visit, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{visit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *VisitQuery) FirstX(ctx context.Context) *Visit {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Visit ID from the query.
// Returns a *NotFoundError when no Visit ID was found.
func (vq *VisitQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{visit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *VisitQuery) FirstIDX(ctx context.Context) int64 {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Visit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Visit entity is found.
// Returns a *NotFoundError when no Visit entities are found.
func (vq *VisitQuery) Only(ctx context.Context) (*Visit, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{visit.Label}
	default:
		return nil, &NotSingularError{visit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *VisitQuery) OnlyX(ctx context.Context) *Visit {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Visit ID in the query.
// Returns a *NotSingularError when more than one Visit ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *VisitQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{visit.Label}
	default:
		err = &NotSingularError{visit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *VisitQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Visits.
func (vq *VisitQuery) All(ctx context.Context) ([]*Visit, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryAll)
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Visit, *VisitQuery]()
	return withInterceptors[[]*Visit](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *VisitQuery) AllX(ctx context.Context) []*Visit {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Visit IDs.
func (vq *VisitQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if vq.ctx.Unique == nil && vq.path != nil {
		vq.Unique(true)
	}
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryIDs)
	if err = vq.Select(visit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *VisitQuery) IDsX(ctx context.Context) []int64 {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *VisitQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryCount)
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*VisitQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *VisitQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *VisitQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryExist)
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *VisitQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VisitQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *VisitQuery) Clone() *VisitQuery {
	if vq == nil {
		return nil
	}
	return &VisitQuery{
		config:     vq.config,
		ctx:        vq.ctx.Clone(),
		order:      append([]visit.OrderOption{}, vq.order...),
		inters:     append([]Interceptor{}, vq.inters...),
		predicates: append([]predicate.Visit{}, vq.predicates...),
		withPhotos: vq.withPhotos.Clone(),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// WithPhotos tells the query-builder to eager-load the nodes that are connected to
// the "photos" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VisitQuery) WithPhotos(opts ...func(*VisitPhotoQuery)) *VisitQuery {
	query := (&VisitPhotoClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withPhotos = query
	return vq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Visit.Query().
//		GroupBy(visit.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *VisitQuery) GroupBy(field string, fields ...string) *VisitGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VisitGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = visit.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Visit.Query().
//		Select(visit.FieldCreatedAt).
//		Scan(ctx, &v)
func (vq *VisitQuery) Select(fields ...string) *VisitSelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &VisitSelect{VisitQuery: vq}
	sbuild.label = visit.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VisitSelect configured with the given aggregations.
func (vq *VisitQuery) Aggregate(fns ...AggregateFunc) *VisitSelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *VisitQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !visit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *VisitQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Visit, error) {
	var (
		nodes       = []*Visit{}
		_spec       = vq.querySpec()
		loadedTypes = [1]bool{
			vq.withPhotos != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Visit).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Visit{config: vq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(vq.modifiers) > 0 {
		_spec.Modifiers = vq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vq.withPhotos; query != nil {
		if err := vq.loadPhotos(ctx, query, nodes,
			func(n *Visit) { n.Edges.Photos = []*VisitPhoto{} },
			func(n *Visit, e *VisitPhoto) { n.Edges.Photos = append(n.Edges.Photos, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vq *VisitQuery) loadPhotos(ctx context.Context, query *VisitPhotoQuery, nodes []*Visit, init func(*Visit), assign func(*Visit, *VisitPhoto)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Visit)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(visitphoto.FieldVisitID)
	}
	query.Where(predicate.VisitPhoto(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(visit.PhotosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VisitID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "visit_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (vq *VisitQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	if len(vq.modifiers) > 0 {
		_spec.Modifiers = vq.modifiers
	}
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *VisitQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(visit.Table, visit.Columns, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64))
	_spec.From = vq.sql
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vq.path != nil {
		_spec.Unique = true
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visit.FieldID)
		for i := range fields {
			if fields[i] != visit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *VisitQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(visit.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = visit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range vq.modifiers {
		m(selector)
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vq *VisitQuery) Modify(modifiers ...func(s *sql.Selector)) *VisitSelect {
	vq.modifiers = append(vq.modifiers, modifiers...)
	return vq.Select()
}

// VisitGroupBy is the group-by builder for Visit entities.
type VisitGroupBy struct {
	selector
	build *VisitQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *VisitGroupBy) Aggregate(fns ...AggregateFunc) *VisitGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *VisitGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, ent.OpQueryGroupBy)
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitQuery, *VisitGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *VisitGroupBy) sqlScan(ctx context.Context, root *VisitQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VisitSelect is the builder for selecting fields of Visit entities.
type VisitSelect struct {
	*VisitQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *VisitSelect) Aggregate(fns ...AggregateFunc) *VisitSelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *VisitSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, ent.OpQuerySelect)
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitQuery, *VisitSelect](ctx, vs.VisitQuery, vs, vs.inters, v)
}

func (vs *VisitSelect) sqlScan(ctx context.Context, root *VisitQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vs *VisitSelect) Modify(modifiers ...func(s *sql.Selector)) *VisitSelect {
	vs.modifiers = append(vs.modifiers, modifiers...)
	return vs
}
