// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/agents/ent/visit"
	"gitlab.calendaria.team/services/agents/ent/visitphoto"
)

// VisitCreate is the builder for creating a Visit entity.
type VisitCreate struct {
	config
	mutation *VisitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (vc *VisitCreate) SetCreatedAt(t time.Time) *VisitCreate {
	vc.mutation.SetCreatedAt(t)
	return vc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vc *VisitCreate) SetNillableCreatedAt(t *time.Time) *VisitCreate {
	if t != nil {
		vc.SetCreatedAt(*t)
	}
	return vc
}

// SetUpdatedAt sets the "updated_at" field.
func (vc *VisitCreate) SetUpdatedAt(t time.Time) *VisitCreate {
	vc.mutation.SetUpdatedAt(t)
	return vc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vc *VisitCreate) SetNillableUpdatedAt(t *time.Time) *VisitCreate {
	if t != nil {
		vc.SetUpdatedAt(*t)
	}
	return vc
}

// SetTenantID sets the "tenant_id" field.
func (vc *VisitCreate) SetTenantID(i int64) *VisitCreate {
	vc.mutation.SetTenantID(i)
	return vc
}

// SetRoutePointID sets the "route_point_id" field.
func (vc *VisitCreate) SetRoutePointID(i int64) *VisitCreate {
	vc.mutation.SetRoutePointID(i)
	return vc
}

// SetAgentID sets the "agent_id" field.
func (vc *VisitCreate) SetAgentID(i int64) *VisitCreate {
	vc.mutation.SetAgentID(i)
	return vc
}

// SetCheckinLat sets the "checkin_lat" field.
func (vc *VisitCreate) SetCheckinLat(d decimal.Decimal) *VisitCreate {
	vc.mutation.SetCheckinLat(d)
	return vc
}

// SetCheckinLon sets the "checkin_lon" field.
func (vc *VisitCreate) SetCheckinLon(d decimal.Decimal) *VisitCreate {
	vc.mutation.SetCheckinLon(d)
	return vc
}

// SetCheckinAt sets the "checkin_at" field.
func (vc *VisitCreate) SetCheckinAt(t time.Time) *VisitCreate {
	vc.mutation.SetCheckinAt(t)
	return vc
}

// SetCheckoutLat sets the "checkout_lat" field.
func (vc *VisitCreate) SetCheckoutLat(d decimal.Decimal) *VisitCreate {
	vc.mutation.SetCheckoutLat(d)
	return vc
}

// SetNillableCheckoutLat sets the "checkout_lat" field if the given value is not nil.
func (vc *VisitCreate) SetNillableCheckoutLat(d *decimal.Decimal) *VisitCreate {
	if d != nil {
		vc.SetCheckoutLat(*d)
	}
	return vc
}

// SetCheckoutLon sets the "checkout_lon" field.
func (vc *VisitCreate) SetCheckoutLon(d decimal.Decimal) *VisitCreate {
	vc.mutation.SetCheckoutLon(d)
	return vc
}

// SetNillableCheckoutLon sets the "checkout_lon" field if the given value is not nil.
func (vc *VisitCreate) SetNillableCheckoutLon(d *decimal.Decimal) *VisitCreate {
	if d != nil {
		vc.SetCheckoutLon(*d)
	}
	return vc
}

// SetCheckoutAt sets the "checkout_at" field.
func (vc *VisitCreate) SetCheckoutAt(t time.Time) *VisitCreate {
	vc.mutation.SetCheckoutAt(t)
	return vc
}

// SetNillableCheckoutAt sets the "checkout_at" field if the given value is not nil.
func (vc *VisitCreate) SetNillableCheckoutAt(t *time.Time) *VisitCreate {
	if t != nil {
		vc.SetCheckoutAt(*t)
	}
	return vc
}

// SetDurationSeconds sets the "duration_seconds" field.
func (vc *VisitCreate) SetDurationSeconds(i int64) *VisitCreate {
	vc.mutation.SetDurationSeconds(i)
	return vc
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (vc *VisitCreate) SetNillableDurationSeconds(i *int64) *VisitCreate {
	if i != nil {
		vc.SetDurationSeconds(*i)
	}
	return vc
}

// SetID sets the "id" field.
func (vc *VisitCreate) SetID(i int64) *VisitCreate {
	vc.mutation.SetID(i)
	return vc
}

// AddPhotoIDs adds the "photos" edge to the VisitPhoto entity by IDs.
func (vc *VisitCreate) AddPhotoIDs(ids ...int64) *VisitCreate {
	vc.mutation.AddPhotoIDs(ids...)
	return vc
}

// AddPhotos adds the "photos" edges to the VisitPhoto entity.
func (vc *VisitCreate) AddPhotos(v ...*VisitPhoto) *VisitCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return vc.AddPhotoIDs(ids...)
}

// Mutation returns the VisitMutation object of the builder.
func (vc *VisitCreate) Mutation() *VisitMutation {
	return vc.mutation
}

// Save creates the Visit in the database.
func (vc *VisitCreate) Save(ctx context.Context) (*Visit, error) {
	vc.defaults()
	return withHooks(ctx, vc.sqlSave, vc.mutation, vc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vc *VisitCreate) SaveX(ctx context.Context) *Visit {
	v, err := vc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vc *VisitCreate) Exec(ctx context.Context) error {
	_, err := vc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vc *VisitCreate) ExecX(ctx context.Context) {
	if err := vc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vc *VisitCreate) defaults() {
	if _, ok := vc.mutation.CreatedAt(); !ok {
		v := visit.DefaultCreatedAt()
		vc.mutation.SetCreatedAt(v)
	}
	if _, ok := vc.mutation.UpdatedAt(); !ok {
		v := visit.DefaultUpdatedAt()
		vc.mutation.SetUpdatedAt(v)
	}
	if _, ok := vc.mutation.DurationSeconds(); !ok {
		v := visit.DefaultDurationSeconds
		vc.mutation.SetDurationSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vc *VisitCreate) check() error {
	if _, ok := vc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Visit.created_at"`)}
	}
	if _, ok := vc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Visit.updated_at"`)}
	}
	if _, ok := vc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Visit.tenant_id"`)}
	}
	if _, ok := vc.mutation.RoutePointID(); !ok {
		return &ValidationError{Name: "route_point_id", err: errors.New(`ent: missing required field "Visit.route_point_id"`)}
	}
	if _, ok := vc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Visit.agent_id"`)}
	}
	if _, ok := vc.mutation.CheckinLat(); !ok {
		return &ValidationError{Name: "checkin_lat", err: errors.New(`ent: missing required field "Visit.checkin_lat"`)}
	}
	if _, ok := vc.mutation.CheckinLon(); !ok {
		return &ValidationError{Name: "checkin_lon", err: errors.New(`ent: missing required field "Visit.checkin_lon"`)}
	}
	if _, ok := vc.mutation.CheckinAt(); !ok {
		return &ValidationError{Name: "checkin_at", err: errors.New(`ent: missing required field "Visit.checkin_at"`)}
	}
	return nil
}

func (vc *VisitCreate) sqlSave(ctx context.Context) (*Visit, error) {
	if err := vc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	vc.mutation.id = &_node.ID
	vc.mutation.done = true
	return _node, nil
}

func (vc *VisitCreate) createSpec() (*Visit, *sqlgraph.CreateSpec) {
	var (
		_node = &Visit{config: vc.config}
		_spec = sqlgraph.NewCreateSpec(visit.Table, sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = vc.conflict
	if id, ok := vc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := vc.mutation.CreatedAt(); ok {
		_spec.SetField(visit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := vc.mutation.UpdatedAt(); ok {
		_spec.SetField(visit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := vc.mutation.TenantID(); ok {
		_spec.SetField(visit.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := vc.mutation.RoutePointID(); ok {
		_spec.SetField(visit.FieldRoutePointID, field.TypeInt64, value)
		_node.RoutePointID = value
	}
	if value, ok := vc.mutation.AgentID(); ok {
		_spec.SetField(visit.FieldAgentID, field.TypeInt64, value)
		_node.AgentID = value
	}
	if value, ok := vc.mutation.CheckinLat(); ok {
		_spec.SetField(visit.FieldCheckinLat, field.TypeFloat64, value)
		_node.CheckinLat = value
	}
	if value, ok := vc.mutation.CheckinLon(); ok {
		_spec.SetField(visit.FieldCheckinLon, field.TypeFloat64, value)
		_node.CheckinLon = value
	}
	if value, ok := vc.mutation.CheckinAt(); ok {
		_spec.SetField(visit.FieldCheckinAt, field.TypeTime, value)
		_node.CheckinAt = value
	}
	if value, ok := vc.mutation.CheckoutLat(); ok {
		_spec.SetField(visit.FieldCheckoutLat, field.TypeFloat64, value)
		_node.CheckoutLat = value
	}
	if value, ok := vc.mutation.CheckoutLon(); ok {
		_spec.SetField(visit.FieldCheckoutLon, field.TypeFloat64, value)
		_node.CheckoutLon = value
	}
	if value, ok := vc.mutation.CheckoutAt(); ok {
		_spec.SetField(visit.FieldCheckoutAt, field.TypeTime, value)
		_node.CheckoutAt = &value
	}
	if value, ok := vc.mutation.DurationSeconds(); ok {
		_spec.SetField(visit.FieldDurationSeconds, field.TypeInt64, value)
		_node.DurationSeconds = value
	}
	if nodes := vc.mutation.PhotosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   visit.PhotosTable,
			Columns: []string{visit.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visitphoto.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Visit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (vc *VisitCreate) OnConflict(opts ...sql.ConflictOption) *VisitUpsertOne {
	vc.conflict = opts
	return &VisitUpsertOne{
		create: vc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (vc *VisitCreate) OnConflictColumns(columns ...string) *VisitUpsertOne {
	vc.conflict = append(vc.conflict, sql.ConflictColumns(columns...))
	return &VisitUpsertOne{
		create: vc,
	}
}

type (
	// VisitUpsertOne is the builder for "upsert"-ing
	//  one Visit node.
	VisitUpsertOne struct {
		create *VisitCreate
	}

	// VisitUpsert is the "OnConflict" setter.
	VisitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsert) SetUpdatedAt(v time.Time) *VisitUpsert {
	u.Set(visit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsert) UpdateUpdatedAt() *VisitUpsert {
	u.SetExcluded(visit.FieldUpdatedAt)
	return u
}

// SetRoutePointID sets the "route_point_id" field.
func (u *VisitUpsert) SetRoutePointID(v int64) *VisitUpsert {
	u.Set(visit.FieldRoutePointID, v)
	return u
}

// UpdateRoutePointID sets the "route_point_id" field to the value that was provided on create.
func (u *VisitUpsert) UpdateRoutePointID() *VisitUpsert {
	u.SetExcluded(visit.FieldRoutePointID)
	return u
}

// AddRoutePointID adds v to the "route_point_id" field.
func (u *VisitUpsert) AddRoutePointID(v int64) *VisitUpsert {
	u.Add(visit.FieldRoutePointID, v)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *VisitUpsert) SetAgentID(v int64) *VisitUpsert {
	u.Set(visit.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *VisitUpsert) UpdateAgentID() *VisitUpsert {
	u.SetExcluded(visit.FieldAgentID)
	return u
}

// AddAgentID adds v to the "agent_id" field.
func (u *VisitUpsert) AddAgentID(v int64) *VisitUpsert {
	u.Add(visit.FieldAgentID, v)
	return u
}

// SetCheckinLat sets the "checkin_lat" field.
func (u *VisitUpsert) SetCheckinLat(v decimal.Decimal) *VisitUpsert {
	u.Set(visit.FieldCheckinLat, v)
	return u
}

// UpdateCheckinLat sets the "checkin_lat" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckinLat() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckinLat)
	return u
}

// AddCheckinLat adds v to the "checkin_lat" field.
func (u *VisitUpsert) AddCheckinLat(v decimal.Decimal) *VisitUpsert {
	u.Add(visit.FieldCheckinLat, v)
	return u
}

// SetCheckinLon sets the "checkin_lon" field.
func (u *VisitUpsert) SetCheckinLon(v decimal.Decimal) *VisitUpsert {
	u.Set(visit.FieldCheckinLon, v)
	return u
}

// UpdateCheckinLon sets the "checkin_lon" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckinLon() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckinLon)
	return u
}

// AddCheckinLon adds v to the "checkin_lon" field.
func (u *VisitUpsert) AddCheckinLon(v decimal.Decimal) *VisitUpsert {
	u.Add(visit.FieldCheckinLon, v)
	return u
}

// SetCheckinAt sets the "checkin_at" field.
func (u *VisitUpsert) SetCheckinAt(v time.Time) *VisitUpsert {
	u.Set(visit.FieldCheckinAt, v)
	return u
}

// UpdateCheckinAt sets the "checkin_at" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckinAt() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckinAt)
	return u
}

// SetCheckoutLat sets the "checkout_lat" field.
func (u *VisitUpsert) SetCheckoutLat(v decimal.Decimal) *VisitUpsert {
	u.Set(visit.FieldCheckoutLat, v)
	return u
}

// UpdateCheckoutLat sets the "checkout_lat" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckoutLat() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckoutLat)
	return u
}

// AddCheckoutLat adds v to the "checkout_lat" field.
func (u *VisitUpsert) AddCheckoutLat(v decimal.Decimal) *VisitUpsert {
	u.Add(visit.FieldCheckoutLat, v)
	return u
}

// ClearCheckoutLat clears the value of the "checkout_lat" field.
func (u *VisitUpsert) ClearCheckoutLat() *VisitUpsert {
	u.SetNull(visit.FieldCheckoutLat)
	return u
}

// SetCheckoutLon sets the "checkout_lon" field.
func (u *VisitUpsert) SetCheckoutLon(v decimal.Decimal) *VisitUpsert {
	u.Set(visit.FieldCheckoutLon, v)
	return u
}

// UpdateCheckoutLon sets the "checkout_lon" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckoutLon() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckoutLon)
	return u
}

// AddCheckoutLon adds v to the "checkout_lon" field.
func (u *VisitUpsert) AddCheckoutLon(v decimal.Decimal) *VisitUpsert {
	u.Add(visit.FieldCheckoutLon, v)
	return u
}

// ClearCheckoutLon clears the value of the "checkout_lon" field.
func (u *VisitUpsert) ClearCheckoutLon() *VisitUpsert {
	u.SetNull(visit.FieldCheckoutLon)
	return u
}

// SetCheckoutAt sets the "checkout_at" field.
func (u *VisitUpsert) SetCheckoutAt(v time.Time) *VisitUpsert {
	u.Set(visit.FieldCheckoutAt, v)
	return u
}

// UpdateCheckoutAt sets the "checkout_at" field to the value that was provided on create.
func (u *VisitUpsert) UpdateCheckoutAt() *VisitUpsert {
	u.SetExcluded(visit.FieldCheckoutAt)
	return u
}

// ClearCheckoutAt clears the value of the "checkout_at" field.
func (u *VisitUpsert) ClearCheckoutAt() *VisitUpsert {
	u.SetNull(visit.FieldCheckoutAt)
	return u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VisitUpsert) SetDurationSeconds(v int64) *VisitUpsert {
	u.Set(visit.FieldDurationSeconds, v)
	return u
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VisitUpsert) UpdateDurationSeconds() *VisitUpsert {
	u.SetExcluded(visit.FieldDurationSeconds)
	return u
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VisitUpsert) AddDurationSeconds(v int64) *VisitUpsert {
	u.Add(visit.FieldDurationSeconds, v)
	return u
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (u *VisitUpsert) ClearDurationSeconds() *VisitUpsert {
	u.SetNull(visit.FieldDurationSeconds)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(visit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VisitUpsertOne) UpdateNewValues() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(visit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(visit.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(visit.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VisitUpsertOne) Ignore() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitUpsertOne) DoNothing() *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitCreate.OnConflict
// documentation for more info.
func (u *VisitUpsertOne) Update(set func(*VisitUpsert)) *VisitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsertOne) SetUpdatedAt(v time.Time) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateUpdatedAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoutePointID sets the "route_point_id" field.
func (u *VisitUpsertOne) SetRoutePointID(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetRoutePointID(v)
	})
}

// AddRoutePointID adds v to the "route_point_id" field.
func (u *VisitUpsertOne) AddRoutePointID(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddRoutePointID(v)
	})
}

// UpdateRoutePointID sets the "route_point_id" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateRoutePointID() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateRoutePointID()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *VisitUpsertOne) SetAgentID(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *VisitUpsertOne) AddAgentID(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateAgentID() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateAgentID()
	})
}

// SetCheckinLat sets the "checkin_lat" field.
func (u *VisitUpsertOne) SetCheckinLat(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinLat(v)
	})
}

// AddCheckinLat adds v to the "checkin_lat" field.
func (u *VisitUpsertOne) AddCheckinLat(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckinLat(v)
	})
}

// UpdateCheckinLat sets the "checkin_lat" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckinLat() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinLat()
	})
}

// SetCheckinLon sets the "checkin_lon" field.
func (u *VisitUpsertOne) SetCheckinLon(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinLon(v)
	})
}

// AddCheckinLon adds v to the "checkin_lon" field.
func (u *VisitUpsertOne) AddCheckinLon(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckinLon(v)
	})
}

// UpdateCheckinLon sets the "checkin_lon" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckinLon() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinLon()
	})
}

// SetCheckinAt sets the "checkin_at" field.
func (u *VisitUpsertOne) SetCheckinAt(v time.Time) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinAt(v)
	})
}

// UpdateCheckinAt sets the "checkin_at" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckinAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinAt()
	})
}

// SetCheckoutLat sets the "checkout_lat" field.
func (u *VisitUpsertOne) SetCheckoutLat(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutLat(v)
	})
}

// AddCheckoutLat adds v to the "checkout_lat" field.
func (u *VisitUpsertOne) AddCheckoutLat(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckoutLat(v)
	})
}

// UpdateCheckoutLat sets the "checkout_lat" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckoutLat() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutLat()
	})
}

// ClearCheckoutLat clears the value of the "checkout_lat" field.
func (u *VisitUpsertOne) ClearCheckoutLat() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutLat()
	})
}

// SetCheckoutLon sets the "checkout_lon" field.
func (u *VisitUpsertOne) SetCheckoutLon(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutLon(v)
	})
}

// AddCheckoutLon adds v to the "checkout_lon" field.
func (u *VisitUpsertOne) AddCheckoutLon(v decimal.Decimal) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckoutLon(v)
	})
}

// UpdateCheckoutLon sets the "checkout_lon" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckoutLon() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutLon()
	})
}

// ClearCheckoutLon clears the value of the "checkout_lon" field.
func (u *VisitUpsertOne) ClearCheckoutLon() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutLon()
	})
}

// SetCheckoutAt sets the "checkout_at" field.
func (u *VisitUpsertOne) SetCheckoutAt(v time.Time) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutAt(v)
	})
}

// UpdateCheckoutAt sets the "checkout_at" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateCheckoutAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutAt()
	})
}

// ClearCheckoutAt clears the value of the "checkout_at" field.
func (u *VisitUpsertOne) ClearCheckoutAt() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutAt()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VisitUpsertOne) SetDurationSeconds(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VisitUpsertOne) AddDurationSeconds(v int64) *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VisitUpsertOne) UpdateDurationSeconds() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateDurationSeconds()
	})
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (u *VisitUpsertOne) ClearDurationSeconds() *VisitUpsertOne {
	return u.Update(func(s *VisitUpsert) {
		s.ClearDurationSeconds()
	})
}

// Exec executes the query.
func (u *VisitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VisitUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VisitUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VisitCreateBulk is the builder for creating many Visit entities in bulk.
type VisitCreateBulk struct {
	config
	err      error
	builders []*VisitCreate
	conflict []sql.ConflictOption
}

// Save creates the Visit entities in the database.
func (vcb *VisitCreateBulk) Save(ctx context.Context) ([]*Visit, error) {
	if vcb.err != nil {
		return nil, vcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vcb.builders))
	nodes := make([]*Visit, len(vcb.builders))
	mutators := make([]Mutator, len(vcb.builders))
	for i := range vcb.builders {
		func(i int, root context.Context) {
			builder := vcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VisitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = vcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vcb *VisitCreateBulk) SaveX(ctx context.Context) []*Visit {
	v, err := vcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vcb *VisitCreateBulk) Exec(ctx context.Context) error {
	_, err := vcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcb *VisitCreateBulk) ExecX(ctx context.Context) {
	if err := vcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Visit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (vcb *VisitCreateBulk) OnConflict(opts ...sql.ConflictOption) *VisitUpsertBulk {
	vcb.conflict = opts
	return &VisitUpsertBulk{
		create: vcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (vcb *VisitCreateBulk) OnConflictColumns(columns ...string) *VisitUpsertBulk {
	vcb.conflict = append(vcb.conflict, sql.ConflictColumns(columns...))
	return &VisitUpsertBulk{
		create: vcb,
	}
}

// VisitUpsertBulk is the builder for "upsert"-ing
// a bulk of Visit nodes.
type VisitUpsertBulk struct {
	create *VisitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(visit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VisitUpsertBulk) UpdateNewValues() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(visit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(visit.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(visit.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Visit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VisitUpsertBulk) Ignore() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitUpsertBulk) DoNothing() *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitCreateBulk.OnConflict
// documentation for more info.
func (u *VisitUpsertBulk) Update(set func(*VisitUpsert)) *VisitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitUpsertBulk) SetUpdatedAt(v time.Time) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateUpdatedAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoutePointID sets the "route_point_id" field.
func (u *VisitUpsertBulk) SetRoutePointID(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetRoutePointID(v)
	})
}

// AddRoutePointID adds v to the "route_point_id" field.
func (u *VisitUpsertBulk) AddRoutePointID(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddRoutePointID(v)
	})
}

// UpdateRoutePointID sets the "route_point_id" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateRoutePointID() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateRoutePointID()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *VisitUpsertBulk) SetAgentID(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetAgentID(v)
	})
}

// AddAgentID adds v to the "agent_id" field.
func (u *VisitUpsertBulk) AddAgentID(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateAgentID() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateAgentID()
	})
}

// SetCheckinLat sets the "checkin_lat" field.
func (u *VisitUpsertBulk) SetCheckinLat(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinLat(v)
	})
}

// AddCheckinLat adds v to the "checkin_lat" field.
func (u *VisitUpsertBulk) AddCheckinLat(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckinLat(v)
	})
}

// UpdateCheckinLat sets the "checkin_lat" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckinLat() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinLat()
	})
}

// SetCheckinLon sets the "checkin_lon" field.
func (u *VisitUpsertBulk) SetCheckinLon(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinLon(v)
	})
}

// AddCheckinLon adds v to the "checkin_lon" field.
func (u *VisitUpsertBulk) AddCheckinLon(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckinLon(v)
	})
}

// UpdateCheckinLon sets the "checkin_lon" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckinLon() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinLon()
	})
}

// SetCheckinAt sets the "checkin_at" field.
func (u *VisitUpsertBulk) SetCheckinAt(v time.Time) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckinAt(v)
	})
}

// UpdateCheckinAt sets the "checkin_at" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckinAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckinAt()
	})
}

// SetCheckoutLat sets the "checkout_lat" field.
func (u *VisitUpsertBulk) SetCheckoutLat(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutLat(v)
	})
}

// AddCheckoutLat adds v to the "checkout_lat" field.
func (u *VisitUpsertBulk) AddCheckoutLat(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckoutLat(v)
	})
}

// UpdateCheckoutLat sets the "checkout_lat" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckoutLat() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutLat()
	})
}

// ClearCheckoutLat clears the value of the "checkout_lat" field.
func (u *VisitUpsertBulk) ClearCheckoutLat() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutLat()
	})
}

// SetCheckoutLon sets the "checkout_lon" field.
func (u *VisitUpsertBulk) SetCheckoutLon(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutLon(v)
	})
}

// AddCheckoutLon adds v to the "checkout_lon" field.
func (u *VisitUpsertBulk) AddCheckoutLon(v decimal.Decimal) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddCheckoutLon(v)
	})
}

// UpdateCheckoutLon sets the "checkout_lon" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckoutLon() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutLon()
	})
}

// ClearCheckoutLon clears the value of the "checkout_lon" field.
func (u *VisitUpsertBulk) ClearCheckoutLon() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutLon()
	})
}

// SetCheckoutAt sets the "checkout_at" field.
func (u *VisitUpsertBulk) SetCheckoutAt(v time.Time) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetCheckoutAt(v)
	})
}

// UpdateCheckoutAt sets the "checkout_at" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateCheckoutAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateCheckoutAt()
	})
}

// ClearCheckoutAt clears the value of the "checkout_at" field.
func (u *VisitUpsertBulk) ClearCheckoutAt() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearCheckoutAt()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VisitUpsertBulk) SetDurationSeconds(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VisitUpsertBulk) AddDurationSeconds(v int64) *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VisitUpsertBulk) UpdateDurationSeconds() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.UpdateDurationSeconds()
	})
}

// ClearDurationSeconds clears the value of the "duration_seconds" field.
func (u *VisitUpsertBulk) ClearDurationSeconds() *VisitUpsertBulk {
	return u.Update(func(s *VisitUpsert) {
		s.ClearDurationSeconds()
	})
}

// Exec executes the query.
func (u *VisitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VisitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
