// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// VisitPhotoCreate is the builder for creating a VisitPhoto entity.
type VisitPhotoCreate struct {
	config
	mutation *VisitPhotoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (vpc *VisitPhotoCreate) SetCreatedAt(t time.Time) *VisitPhotoCreate {
	vpc.mutation.SetCreatedAt(t)
	return vpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vpc *VisitPhotoCreate) SetNillableCreatedAt(t *time.Time) *VisitPhotoCreate {
	if t != nil {
		vpc.SetCreatedAt(*t)
	}
	return vpc
}

// SetUpdatedAt sets the "updated_at" field.
func (vpc *VisitPhotoCreate) SetUpdatedAt(t time.Time) *VisitPhotoCreate {
	vpc.mutation.SetUpdatedAt(t)
	return vpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vpc *VisitPhotoCreate) SetNillableUpdatedAt(t *time.Time) *VisitPhotoCreate {
	if t != nil {
		vpc.SetUpdatedAt(*t)
	}
	return vpc
}

// SetVisitID sets the "visit_id" field.
func (vpc *VisitPhotoCreate) SetVisitID(i int64) *VisitPhotoCreate {
	vpc.mutation.SetVisitID(i)
	return vpc
}

// SetMediaURL sets the "media_url" field.
func (vpc *VisitPhotoCreate) SetMediaURL(s string) *VisitPhotoCreate {
	vpc.mutation.SetMediaURL(s)
	return vpc
}

// SetID sets the "id" field.
func (vpc *VisitPhotoCreate) SetID(i int64) *VisitPhotoCreate {
	vpc.mutation.SetID(i)
	return vpc
}

// SetVisit sets the "visit" edge to the Visit entity.
func (vpc *VisitPhotoCreate) SetVisit(v *Visit) *VisitPhotoCreate {
	return vpc.SetVisitID(v.ID)
}

// Mutation returns the VisitPhotoMutation object of the builder.
func (vpc *VisitPhotoCreate) Mutation() *VisitPhotoMutation {
	return vpc.mutation
}

// Save creates the VisitPhoto in the database.
func (vpc *VisitPhotoCreate) Save(ctx context.Context) (*VisitPhoto, error) {
	vpc.defaults()
	return withHooks(ctx, vpc.sqlSave, vpc.mutation, vpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vpc *VisitPhotoCreate) SaveX(ctx context.Context) *VisitPhoto {
	v, err := vpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vpc *VisitPhotoCreate) Exec(ctx context.Context) error {
	_, err := vpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vpc *VisitPhotoCreate) ExecX(ctx context.Context) {
	if err := vpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vpc *VisitPhotoCreate) defaults() {
	if _, ok := vpc.mutation.CreatedAt(); !ok {
		v := visitphoto.DefaultCreatedAt()
		vpc.mutation.SetCreatedAt(v)
	}
	if _, ok := vpc.mutation.UpdatedAt(); !ok {
		v := visitphoto.DefaultUpdatedAt()
		vpc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vpc *VisitPhotoCreate) check() error {
	if _, ok := vpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VisitPhoto.created_at"`)}
	}
	if _, ok := vpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VisitPhoto.updated_at"`)}
	}
	if _, ok := vpc.mutation.VisitID(); !ok {
		return &ValidationError{Name: "visit_id", err: errors.New(`ent: missing required field "VisitPhoto.visit_id"`)}
	}
	if _, ok := vpc.mutation.MediaURL(); !ok {
		return &ValidationError{Name: "media_url", err: errors.New(`ent: missing required field "VisitPhoto.media_url"`)}
	}
	if v, ok := vpc.mutation.MediaURL(); ok {
		if err := visitphoto.MediaURLValidator(v); err != nil {
			return &ValidationError{Name: "media_url", err: fmt.Errorf(`ent: validator failed for field "VisitPhoto.media_url": %w`, err)}
		}
	}
	if len(vpc.mutation.VisitIDs()) == 0 {
		return &ValidationError{Name: "visit", err: errors.New(`ent: missing required edge "VisitPhoto.visit"`)}
	}
	return nil
}

func (vpc *VisitPhotoCreate) sqlSave(ctx context.Context) (*VisitPhoto, error) {
	if err := vpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	vpc.mutation.id = &_node.ID
	vpc.mutation.done = true
	return _node, nil
}

func (vpc *VisitPhotoCreate) createSpec() (*VisitPhoto, *sqlgraph.CreateSpec) {
	var (
		_node = &VisitPhoto{config: vpc.config}
		_spec = sqlgraph.NewCreateSpec(visitphoto.Table, sqlgraph.NewFieldSpec(visitphoto.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = vpc.conflict
	if id, ok := vpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := vpc.mutation.CreatedAt(); ok {
		_spec.SetField(visitphoto.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := vpc.mutation.UpdatedAt(); ok {
		_spec.SetField(visitphoto.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := vpc.mutation.MediaURL(); ok {
		_spec.SetField(visitphoto.FieldMediaURL, field.TypeString, value)
		_node.MediaURL = value
	}
	if nodes := vpc.mutation.VisitIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   visitphoto.VisitTable,
			Columns: []string{visitphoto.VisitColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(visit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VisitID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VisitPhoto.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitPhotoUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (vpc *VisitPhotoCreate) OnConflict(opts ...sql.ConflictOption) *VisitPhotoUpsertOne {
	vpc.conflict = opts
	return &VisitPhotoUpsertOne{
		create: vpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (vpc *VisitPhotoCreate) OnConflictColumns(columns ...string) *VisitPhotoUpsertOne {
	vpc.conflict = append(vpc.conflict, sql.ConflictColumns(columns...))
	return &VisitPhotoUpsertOne{
		create: vpc,
	}
}

type (
	// VisitPhotoUpsertOne is the builder for "upsert"-ing
	//  one VisitPhoto node.
	VisitPhotoUpsertOne struct {
		create *VisitPhotoCreate
	}

	// VisitPhotoUpsert is the "OnConflict" setter.
	VisitPhotoUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitPhotoUpsert) SetUpdatedAt(v time.Time) *VisitPhotoUpsert {
	u.Set(visitphoto.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitPhotoUpsert) UpdateUpdatedAt() *VisitPhotoUpsert {
	u.SetExcluded(visitphoto.FieldUpdatedAt)
	return u
}

// SetVisitID sets the "visit_id" field.
func (u *VisitPhotoUpsert) SetVisitID(v int64) *VisitPhotoUpsert {
	u.Set(visitphoto.FieldVisitID, v)
	return u
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *VisitPhotoUpsert) UpdateVisitID() *VisitPhotoUpsert {
	u.SetExcluded(visitphoto.FieldVisitID)
	return u
}

// SetMediaURL sets the "media_url" field.
func (u *VisitPhotoUpsert) SetMediaURL(v string) *VisitPhotoUpsert {
	u.Set(visitphoto.FieldMediaURL, v)
	return u
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *VisitPhotoUpsert) UpdateMediaURL() *VisitPhotoUpsert {
	u.SetExcluded(visitphoto.FieldMediaURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(visitphoto.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VisitPhotoUpsertOne) UpdateNewValues() *VisitPhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(visitphoto.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(visitphoto.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VisitPhotoUpsertOne) Ignore() *VisitPhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitPhotoUpsertOne) DoNothing() *VisitPhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitPhotoCreate.OnConflict
// documentation for more info.
func (u *VisitPhotoUpsertOne) Update(set func(*VisitPhotoUpsert)) *VisitPhotoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitPhotoUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitPhotoUpsertOne) SetUpdatedAt(v time.Time) *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitPhotoUpsertOne) UpdateUpdatedAt() *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetVisitID sets the "visit_id" field.
func (u *VisitPhotoUpsertOne) SetVisitID(v int64) *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetVisitID(v)
	})
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *VisitPhotoUpsertOne) UpdateVisitID() *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateVisitID()
	})
}

// SetMediaURL sets the "media_url" field.
func (u *VisitPhotoUpsertOne) SetMediaURL(v string) *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetMediaURL(v)
	})
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *VisitPhotoUpsertOne) UpdateMediaURL() *VisitPhotoUpsertOne {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateMediaURL()
	})
}

// Exec executes the query.
func (u *VisitPhotoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitPhotoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitPhotoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VisitPhotoUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VisitPhotoUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VisitPhotoCreateBulk is the builder for creating many VisitPhoto entities in bulk.
type VisitPhotoCreateBulk struct {
	config
	err      error
	builders []*VisitPhotoCreate
	conflict []sql.ConflictOption
}

// Save creates the VisitPhoto entities in the database.
func (vpcb *VisitPhotoCreateBulk) Save(ctx context.Context) ([]*VisitPhoto, error) {
	if vpcb.err != nil {
		return nil, vpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vpcb.builders))
	nodes := make([]*VisitPhoto, len(vpcb.builders))
	mutators := make([]Mutator, len(vpcb.builders))
	for i := range vpcb.builders {
		func(i int, root context.Context) {
			builder := vpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VisitPhotoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = vpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vpcb *VisitPhotoCreateBulk) SaveX(ctx context.Context) []*VisitPhoto {
	v, err := vpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vpcb *VisitPhotoCreateBulk) Exec(ctx context.Context) error {
	_, err := vpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vpcb *VisitPhotoCreateBulk) ExecX(ctx context.Context) {
	if err := vpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VisitPhoto.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VisitPhotoUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (vpcb *VisitPhotoCreateBulk) OnConflict(opts ...sql.ConflictOption) *VisitPhotoUpsertBulk {
	vpcb.conflict = opts
	return &VisitPhotoUpsertBulk{
		create: vpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (vpcb *VisitPhotoCreateBulk) OnConflictColumns(columns ...string) *VisitPhotoUpsertBulk {
	vpcb.conflict = append(vpcb.conflict, sql.ConflictColumns(columns...))
	return &VisitPhotoUpsertBulk{
		create: vpcb,
	}
}

// VisitPhotoUpsertBulk is the builder for "upsert"-ing
// a bulk of VisitPhoto nodes.
type VisitPhotoUpsertBulk struct {
	create *VisitPhotoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(visitphoto.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VisitPhotoUpsertBulk) UpdateNewValues() *VisitPhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(visitphoto.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(visitphoto.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VisitPhoto.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VisitPhotoUpsertBulk) Ignore() *VisitPhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VisitPhotoUpsertBulk) DoNothing() *VisitPhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VisitPhotoCreateBulk.OnConflict
// documentation for more info.
func (u *VisitPhotoUpsertBulk) Update(set func(*VisitPhotoUpsert)) *VisitPhotoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VisitPhotoUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VisitPhotoUpsertBulk) SetUpdatedAt(v time.Time) *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VisitPhotoUpsertBulk) UpdateUpdatedAt() *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetVisitID sets the "visit_id" field.
func (u *VisitPhotoUpsertBulk) SetVisitID(v int64) *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetVisitID(v)
	})
}

// UpdateVisitID sets the "visit_id" field to the value that was provided on create.
func (u *VisitPhotoUpsertBulk) UpdateVisitID() *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateVisitID()
	})
}

// SetMediaURL sets the "media_url" field.
func (u *VisitPhotoUpsertBulk) SetMediaURL(v string) *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.SetMediaURL(v)
	})
}

// UpdateMediaURL sets the "media_url" field to the value that was provided on create.
func (u *VisitPhotoUpsertBulk) UpdateMediaURL() *VisitPhotoUpsertBulk {
	return u.Update(func(s *VisitPhotoUpsert) {
		s.UpdateMediaURL()
	})
}

// Exec executes the query.
func (u *VisitPhotoUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VisitPhotoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VisitPhotoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VisitPhotoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
