// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/agents/ent/visit"
)

// Visit is the model entity for the Visit schema.
type Visit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// RoutePointID holds the value of the "route_point_id" field.
	RoutePointID int64 `json:"route_point_id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID int64 `json:"agent_id,omitempty"`
	// CheckinLat holds the value of the "checkin_lat" field.
	CheckinLat decimal.Decimal `json:"checkin_lat,omitempty"`
	// CheckinLon holds the value of the "checkin_lon" field.
	CheckinLon decimal.Decimal `json:"checkin_lon,omitempty"`
	// CheckinAt holds the value of the "checkin_at" field.
	CheckinAt time.Time `json:"checkin_at,omitempty"`
	// CheckoutLat holds the value of the "checkout_lat" field.
	CheckoutLat decimal.Decimal `json:"checkout_lat,omitempty"`
	// CheckoutLon holds the value of the "checkout_lon" field.
	CheckoutLon decimal.Decimal `json:"checkout_lon,omitempty"`
	// CheckoutAt holds the value of the "checkout_at" field.
	CheckoutAt *time.Time `json:"checkout_at,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds int64 `json:"duration_seconds,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VisitQuery when eager-loading is set.
	Edges        VisitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VisitEdges holds the relations/edges for other nodes in the graph.
type VisitEdges struct {
	// Photos holds the value of the photos edge.
	Photos []*VisitPhoto `json:"photos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PhotosOrErr returns the Photos value or an error if the edge
// was not loaded in eager-loading.
func (e VisitEdges) PhotosOrErr() ([]*VisitPhoto, error) {
	if e.loadedTypes[0] {
		return e.Photos, nil
	}
	return nil, &NotLoadedError{edge: "photos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Visit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case visit.FieldCheckinLat, visit.FieldCheckinLon, visit.FieldCheckoutLat, visit.FieldCheckoutLon:
			values[i] = new(decimal.Decimal)
		case visit.FieldID, visit.FieldTenantID, visit.FieldRoutePointID, visit.FieldAgentID, visit.FieldDurationSeconds:
			values[i] = new(sql.NullInt64)
		case visit.FieldCreatedAt, visit.FieldUpdatedAt, visit.FieldCheckinAt, visit.FieldCheckoutAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Visit fields.
func (v *Visit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case visit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			v.ID = int64(value.Int64)
		case visit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				v.CreatedAt = value.Time
			}
		case visit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				v.UpdatedAt = value.Time
			}
		case visit.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				v.TenantID = value.Int64
			}
		case visit.FieldRoutePointID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_point_id", values[i])
			} else if value.Valid {
				v.RoutePointID = value.Int64
			}
		case visit.FieldAgentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				v.AgentID = value.Int64
			}
		case visit.FieldCheckinLat:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_lat", values[i])
			} else if value != nil {
				v.CheckinLat = *value
			}
		case visit.FieldCheckinLon:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_lon", values[i])
			} else if value != nil {
				v.CheckinLon = *value
			}
		case visit.FieldCheckinAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_at", values[i])
			} else if value.Valid {
				v.CheckinAt = value.Time
			}
		case visit.FieldCheckoutLat:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_lat", values[i])
			} else if value != nil {
				v.CheckoutLat = *value
			}
		case visit.FieldCheckoutLon:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_lon", values[i])
			} else if value != nil {
				v.CheckoutLon = *value
			}
		case visit.FieldCheckoutAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_at", values[i])
			} else if value.Valid {
				v.CheckoutAt = new(time.Time)
				*v.CheckoutAt = value.Time
			}
		case visit.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				v.DurationSeconds = value.Int64
			}
		default:
			v.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Visit.
// This includes values selected through modifiers, order, etc.
func (v *Visit) Value(name string) (ent.Value, error) {
	return v.selectValues.Get(name)
}

// QueryPhotos queries the "photos" edge of the Visit entity.
func (v *Visit) QueryPhotos() *VisitPhotoQuery {
	return NewVisitClient(v.config).QueryPhotos(v)
}

// Update returns a builder for updating this Visit.
// Note that you need to call Visit.Unwrap() before calling this method if this Visit
// was returned from a transaction, and the transaction was committed or rolled back.
func (v *Visit) Update() *VisitUpdateOne {
	return NewVisitClient(v.config).UpdateOne(v)
}

// Unwrap unwraps the Visit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (v *Visit) Unwrap() *Visit {
	_tx, ok := v.config.driver.(*txDriver)
	if !ok {
		panic("ent: Visit is not a transactional entity")
	}
	v.config.driver = _tx.drv
	return v
}

// String implements the fmt.Stringer.
func (v *Visit) String() string {
	var builder strings.Builder
	builder.WriteString("Visit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", v.ID))
	builder.WriteString("created_at=")
	builder.WriteString(v.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(v.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", v.TenantID))
	builder.WriteString(", ")
	builder.WriteString("route_point_id=")
	builder.WriteString(fmt.Sprintf("%v", v.RoutePointID))
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", v.AgentID))
	builder.WriteString(", ")
	builder.WriteString("checkin_lat=")
	builder.WriteString(fmt.Sprintf("%v", v.CheckinLat))
	builder.WriteString(", ")
	builder.WriteString("checkin_lon=")
	builder.WriteString(fmt.Sprintf("%v", v.CheckinLon))
	builder.WriteString(", ")
	builder.WriteString("checkin_at=")
	builder.WriteString(v.CheckinAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("checkout_lat=")
	builder.WriteString(fmt.Sprintf("%v", v.CheckoutLat))
	builder.WriteString(", ")
	builder.WriteString("checkout_lon=")
	builder.WriteString(fmt.Sprintf("%v", v.CheckoutLon))
	builder.WriteString(", ")
	if v := v.CheckoutAt; v != nil {
		builder.WriteString("checkout_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", v.DurationSeconds))
	builder.WriteByte(')')
	return builder.String()
}

// Visits is a parsable slice of Visit.
type Visits []*Visit
