// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// VisitPhoto is the model entity for the VisitPhoto schema.
type VisitPhoto struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// VisitID holds the value of the "visit_id" field.
	VisitID int64 `json:"visit_id,omitempty"`
	// MediaURL holds the value of the "media_url" field.
	MediaURL string `json:"media_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VisitPhotoQuery when eager-loading is set.
	Edges        VisitPhotoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VisitPhotoEdges holds the relations/edges for other nodes in the graph.
type VisitPhotoEdges struct {
	// Visit holds the value of the visit edge.
	Visit *Visit `json:"visit,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VisitOrErr returns the Visit value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VisitPhotoEdges) VisitOrErr() (*Visit, error) {
	if e.Visit != nil {
		return e.Visit, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: visit.Label}
	}
	return nil, &NotLoadedError{edge: "visit"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VisitPhoto) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case visitphoto.FieldID, visitphoto.FieldVisitID:
			values[i] = new(sql.NullInt64)
		case visitphoto.FieldMediaURL:
			values[i] = new(sql.NullString)
		case visitphoto.FieldCreatedAt, visitphoto.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VisitPhoto fields.
func (vp *VisitPhoto) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case visitphoto.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			vp.ID = int64(value.Int64)
		case visitphoto.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				vp.CreatedAt = value.Time
			}
		case visitphoto.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				vp.UpdatedAt = value.Time
			}
		case visitphoto.FieldVisitID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field visit_id", values[i])
			} else if value.Valid {
				vp.VisitID = value.Int64
			}
		case visitphoto.FieldMediaURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_url", values[i])
			} else if value.Valid {
				vp.MediaURL = value.String
			}
		default:
			vp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VisitPhoto.
// This includes values selected through modifiers, order, etc.
func (vp *VisitPhoto) Value(name string) (ent.Value, error) {
	return vp.selectValues.Get(name)
}

// QueryVisit queries the "visit" edge of the VisitPhoto entity.
func (vp *VisitPhoto) QueryVisit() *VisitQuery {
	return NewVisitPhotoClient(vp.config).QueryVisit(vp)
}

// Update returns a builder for updating this VisitPhoto.
// Note that you need to call VisitPhoto.Unwrap() before calling this method if this VisitPhoto
// was returned from a transaction, and the transaction was committed or rolled back.
func (vp *VisitPhoto) Update() *VisitPhotoUpdateOne {
	return NewVisitPhotoClient(vp.config).UpdateOne(vp)
}

// Unwrap unwraps the VisitPhoto entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vp *VisitPhoto) Unwrap() *VisitPhoto {
	_tx, ok := vp.config.driver.(*txDriver)
	if !ok {
		panic("ent: VisitPhoto is not a transactional entity")
	}
	vp.config.driver = _tx.drv
	return vp
}

// String implements the fmt.Stringer.
func (vp *VisitPhoto) String() string {
	var builder strings.Builder
	builder.WriteString("VisitPhoto(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vp.ID))
	builder.WriteString("created_at=")
	builder.WriteString(vp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(vp.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("visit_id=")
	builder.WriteString(fmt.Sprintf("%v", vp.VisitID))
	builder.WriteString(", ")
	builder.WriteString("media_url=")
	builder.WriteString(vp.MediaURL)
	builder.WriteByte(')')
	return builder.String()
}

// VisitPhotos is a parsable slice of VisitPhoto.
type VisitPhotos []*VisitPhoto
