// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/agents/ent/predicate"
	"github.com/makesalekz/agents/ent/visit"
	"github.com/makesalekz/agents/ent/visitphoto"
)

// VisitPhotoQuery is the builder for querying VisitPhoto entities.
type VisitPhotoQuery struct {
	config
	ctx        *QueryContext
	order      []visitphoto.OrderOption
	inters     []Interceptor
	predicates []predicate.VisitPhoto
	withVisit  *VisitQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VisitPhotoQuery builder.
func (vpq *VisitPhotoQuery) Where(ps ...predicate.VisitPhoto) *VisitPhotoQuery {
	vpq.predicates = append(vpq.predicates, ps...)
	return vpq
}

// Limit the number of records to be returned by this query.
func (vpq *VisitPhotoQuery) Limit(limit int) *VisitPhotoQuery {
	vpq.ctx.Limit = &limit
	return vpq
}

// Offset to start from.
func (vpq *VisitPhotoQuery) Offset(offset int) *VisitPhotoQuery {
	vpq.ctx.Offset = &offset
	return vpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vpq *VisitPhotoQuery) Unique(unique bool) *VisitPhotoQuery {
	vpq.ctx.Unique = &unique
	return vpq
}

// Order specifies how the records should be ordered.
func (vpq *VisitPhotoQuery) Order(o ...visitphoto.OrderOption) *VisitPhotoQuery {
	vpq.order = append(vpq.order, o...)
	return vpq
}

// QueryVisit chains the current query on the "visit" edge.
func (vpq *VisitPhotoQuery) QueryVisit() *VisitQuery {
	query := (&VisitClient{config: vpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(visitphoto.Table, visitphoto.FieldID, selector),
			sqlgraph.To(visit.Table, visit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, visitphoto.VisitTable, visitphoto.VisitColumn),
		)
		fromU = sqlgraph.SetNeighbors(vpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VisitPhoto entity from the query.
// Returns a *NotFoundError when no VisitPhoto was found.
func (vpq *VisitPhotoQuery) First(ctx context.Context) (*VisitPhoto, error) {
	nodes, err := vpq.Limit(1).All(setContextOp(ctx, vpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{visitphoto.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vpq *VisitPhotoQuery) FirstX(ctx context.Context) *VisitPhoto {
	node, err := vpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VisitPhoto ID from the query.
// Returns a *NotFoundError when no VisitPhoto ID was found.
func (vpq *VisitPhotoQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vpq.Limit(1).IDs(setContextOp(ctx, vpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{visitphoto.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vpq *VisitPhotoQuery) FirstIDX(ctx context.Context) int64 {
	id, err := vpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VisitPhoto entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VisitPhoto entity is found.
// Returns a *NotFoundError when no VisitPhoto entities are found.
func (vpq *VisitPhotoQuery) Only(ctx context.Context) (*VisitPhoto, error) {
	nodes, err := vpq.Limit(2).All(setContextOp(ctx, vpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{visitphoto.Label}
	default:
		return nil, &NotSingularError{visitphoto.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vpq *VisitPhotoQuery) OnlyX(ctx context.Context) *VisitPhoto {
	node, err := vpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VisitPhoto ID in the query.
// Returns a *NotSingularError when more than one VisitPhoto ID is found.
// Returns a *NotFoundError when no entities are found.
func (vpq *VisitPhotoQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = vpq.Limit(2).IDs(setContextOp(ctx, vpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{visitphoto.Label}
	default:
		err = &NotSingularError{visitphoto.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vpq *VisitPhotoQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := vpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VisitPhotos.
func (vpq *VisitPhotoQuery) All(ctx context.Context) ([]*VisitPhoto, error) {
	ctx = setContextOp(ctx, vpq.ctx, ent.OpQueryAll)
	if err := vpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VisitPhoto, *VisitPhotoQuery]()
	return withInterceptors[[]*VisitPhoto](ctx, vpq, qr, vpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vpq *VisitPhotoQuery) AllX(ctx context.Context) []*VisitPhoto {
	nodes, err := vpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VisitPhoto IDs.
func (vpq *VisitPhotoQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if vpq.ctx.Unique == nil && vpq.path != nil {
		vpq.Unique(true)
	}
	ctx = setContextOp(ctx, vpq.ctx, ent.OpQueryIDs)
	if err = vpq.Select(visitphoto.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vpq *VisitPhotoQuery) IDsX(ctx context.Context) []int64 {
	ids, err := vpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vpq *VisitPhotoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vpq.ctx, ent.OpQueryCount)
	if err := vpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vpq, querierCount[*VisitPhotoQuery](), vpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vpq *VisitPhotoQuery) CountX(ctx context.Context) int {
	count, err := vpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vpq *VisitPhotoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vpq.ctx, ent.OpQueryExist)
	switch _, err := vpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vpq *VisitPhotoQuery) ExistX(ctx context.Context) bool {
	exist, err := vpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VisitPhotoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vpq *VisitPhotoQuery) Clone() *VisitPhotoQuery {
	if vpq == nil {
		return nil
	}
	return &VisitPhotoQuery{
		config:     vpq.config,
		ctx:        vpq.ctx.Clone(),
		order:      append([]visitphoto.OrderOption{}, vpq.order...),
		inters:     append([]Interceptor{}, vpq.inters...),
		predicates: append([]predicate.VisitPhoto{}, vpq.predicates...),
		withVisit:  vpq.withVisit.Clone(),
		// clone intermediate query.
		sql:  vpq.sql.Clone(),
		path: vpq.path,
	}
}

// WithVisit tells the query-builder to eager-load the nodes that are connected to
// the "visit" edge. The optional arguments are used to configure the query builder of the edge.
func (vpq *VisitPhotoQuery) WithVisit(opts ...func(*VisitQuery)) *VisitPhotoQuery {
	query := (&VisitClient{config: vpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vpq.withVisit = query
	return vpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VisitPhoto.Query().
//		GroupBy(visitphoto.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vpq *VisitPhotoQuery) GroupBy(field string, fields ...string) *VisitPhotoGroupBy {
	vpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VisitPhotoGroupBy{build: vpq}
	grbuild.flds = &vpq.ctx.Fields
	grbuild.label = visitphoto.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VisitPhoto.Query().
//		Select(visitphoto.FieldCreatedAt).
//		Scan(ctx, &v)
func (vpq *VisitPhotoQuery) Select(fields ...string) *VisitPhotoSelect {
	vpq.ctx.Fields = append(vpq.ctx.Fields, fields...)
	sbuild := &VisitPhotoSelect{VisitPhotoQuery: vpq}
	sbuild.label = visitphoto.Label
	sbuild.flds, sbuild.scan = &vpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VisitPhotoSelect configured with the given aggregations.
func (vpq *VisitPhotoQuery) Aggregate(fns ...AggregateFunc) *VisitPhotoSelect {
	return vpq.Select().Aggregate(fns...)
}

func (vpq *VisitPhotoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vpq); err != nil {
				return err
			}
		}
	}
	for _, f := range vpq.ctx.Fields {
		if !visitphoto.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vpq.path != nil {
		prev, err := vpq.path(ctx)
		if err != nil {
			return err
		}
		vpq.sql = prev
	}
	return nil
}

func (vpq *VisitPhotoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VisitPhoto, error) {
	var (
		nodes       = []*VisitPhoto{}
		_spec       = vpq.querySpec()
		loadedTypes = [1]bool{
			vpq.withVisit != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VisitPhoto).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VisitPhoto{config: vpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(vpq.modifiers) > 0 {
		_spec.Modifiers = vpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vpq.withVisit; query != nil {
		if err := vpq.loadVisit(ctx, query, nodes, nil,
			func(n *VisitPhoto, e *Visit) { n.Edges.Visit = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vpq *VisitPhotoQuery) loadVisit(ctx context.Context, query *VisitQuery, nodes []*VisitPhoto, init func(*VisitPhoto), assign func(*VisitPhoto, *Visit)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*VisitPhoto)
	for i := range nodes {
		fk := nodes[i].VisitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(visit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "visit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vpq *VisitPhotoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vpq.querySpec()
	if len(vpq.modifiers) > 0 {
		_spec.Modifiers = vpq.modifiers
	}
	_spec.Node.Columns = vpq.ctx.Fields
	if len(vpq.ctx.Fields) > 0 {
		_spec.Unique = vpq.ctx.Unique != nil && *vpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vpq.driver, _spec)
}

func (vpq *VisitPhotoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(visitphoto.Table, visitphoto.Columns, sqlgraph.NewFieldSpec(visitphoto.FieldID, field.TypeInt64))
	_spec.From = vpq.sql
	if unique := vpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vpq.path != nil {
		_spec.Unique = true
	}
	if fields := vpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visitphoto.FieldID)
		for i := range fields {
			if fields[i] != visitphoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if vpq.withVisit != nil {
			_spec.Node.AddColumnOnce(visitphoto.FieldVisitID)
		}
	}
	if ps := vpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vpq *VisitPhotoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vpq.driver.Dialect())
	t1 := builder.Table(visitphoto.Table)
	columns := vpq.ctx.Fields
	if len(columns) == 0 {
		columns = visitphoto.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vpq.sql != nil {
		selector = vpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vpq.ctx.Unique != nil && *vpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range vpq.modifiers {
		m(selector)
	}
	for _, p := range vpq.predicates {
		p(selector)
	}
	for _, p := range vpq.order {
		p(selector)
	}
	if offset := vpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vpq *VisitPhotoQuery) Modify(modifiers ...func(s *sql.Selector)) *VisitPhotoSelect {
	vpq.modifiers = append(vpq.modifiers, modifiers...)
	return vpq.Select()
}

// VisitPhotoGroupBy is the group-by builder for VisitPhoto entities.
type VisitPhotoGroupBy struct {
	selector
	build *VisitPhotoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vpgb *VisitPhotoGroupBy) Aggregate(fns ...AggregateFunc) *VisitPhotoGroupBy {
	vpgb.fns = append(vpgb.fns, fns...)
	return vpgb
}

// Scan applies the selector query and scans the result into the given value.
func (vpgb *VisitPhotoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vpgb.build.ctx, ent.OpQueryGroupBy)
	if err := vpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitPhotoQuery, *VisitPhotoGroupBy](ctx, vpgb.build, vpgb, vpgb.build.inters, v)
}

func (vpgb *VisitPhotoGroupBy) sqlScan(ctx context.Context, root *VisitPhotoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vpgb.fns))
	for _, fn := range vpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vpgb.flds)+len(vpgb.fns))
		for _, f := range *vpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VisitPhotoSelect is the builder for selecting fields of VisitPhoto entities.
type VisitPhotoSelect struct {
	*VisitPhotoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vps *VisitPhotoSelect) Aggregate(fns ...AggregateFunc) *VisitPhotoSelect {
	vps.fns = append(vps.fns, fns...)
	return vps
}

// Scan applies the selector query and scans the result into the given value.
func (vps *VisitPhotoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vps.ctx, ent.OpQuerySelect)
	if err := vps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VisitPhotoQuery, *VisitPhotoSelect](ctx, vps.VisitPhotoQuery, vps, vps.inters, v)
}

func (vps *VisitPhotoSelect) sqlScan(ctx context.Context, root *VisitPhotoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vps.fns))
	for _, fn := range vps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vps *VisitPhotoSelect) Modify(modifiers ...func(s *sql.Selector)) *VisitPhotoSelect {
	vps.modifiers = append(vps.modifiers, modifiers...)
	return vps
}
